### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by HeliX696** [FastReports/FastReport#10]
Is there any plans to add support of PDF export format ?

**Comment by fediachov** [comment]
Hi,

Of course, we have such plans. We will do this feature.

**Comment by Detrav** [comment]
We have added an external plugin for exporting a report to PDF, [Simple PDF Export](https://github.com/FastReports/FastReport/tree/master/Extras/OpenSource/FastReport.OpenSource.Export.PdfSimple).
