### ISSUE TITLE
Xamarin (Android)

### ISSUE THREAD

**Issue by marcosgerene** [FastReports/FastReport#103]
It's Xamarin compatible?

Has a example to preview and/or generate a pdf in Xamarin?

Thanks

**Comment by Detrav** [comment]
Hi, currently not compatible. We are waiting for Core 3.0.

We have a Viewer for android [FastReport Pages](https://play.google.com/store/apps/details?id=com.FastReports.AndroidPages), this is a free product not related to OpenSource.

**Comment by marcosgerene** [comment]
@Detrav 

>Hi, currently not compatible. We are waiting for Core 3.0.

It's no compatible for preview or general use?

>We have a Viewer for android FastReport Pages, this is a free product not related to OpenSource.

Can you send a example (code)  for me for preview with this tool?

**Comment by Detrav** [comment]
FastReport OpenSource has a dependency on CoreCompat, due to which it will not run on android or ios. When .net Core 3.0 comes out, you can use System.Drawing.Common.

I test every preview release. And with `Preview 5` I like what FastReport looks like on System.Drawing.Common. But this is only a preview. :(

Break changes in every release are terrible. Still waiting for major release.

FastReport Pages is a ready-made application, download and use. I do not have access to the code.

**Comment by marcosgerene** [comment]
@Detrav  Thanks so much!

A last question:
Can you send a example with FRPages at android?

**Comment by psohm** [comment]
@Detrav hello
did you test .net core 3 with fast report ?
do you think we can use fast report with android ?
I already tried fast report pages but it can't be used according to our need (use a report with parameters)
tks for your job

**Comment by Detrav** [comment]
I've tested the new FR Core on Android, but System.Drawing.Common does not work on mobile platforms :(

**Comment by psohm** [comment]
tks for your quick answer @Detrav 
is it possible to generate at least pdf file with FR without that component ?

**Comment by Detrav** [comment]
No, this is the basis for calculating the sizes and operation with graphics.

**Comment by marcosgerene** [comment]
@Detrav 

I need to generate reports in Xamarin.Forms (PDF and print).
Is there any version that does this?

**Comment by psohm** [comment]
there is a beta version for .net core 3.1 .. maybe .. :(

**Comment by Detrav** [comment]
As far as I know, it does not work under Android or iOS yet.

**Comment by fredericoregateiro** [comment]
is xamarin going to be suported?

**Comment by psohm** [comment]
What does it mean

**Comment by psohm** [comment]
@Detrav does the situation evolve ?
