### ISSUE TITLE
Missing support to web farms

### ISSUE THREAD

**Issue by edumartins7** [FastReports/FastReport#122]
My application has 4 instances and a load balancer. When I try to open a report it shows intermittent behavior, so sometimes it works but most of the time I get a 404 error like the one below:

![image](https://user-images.githubusercontent.com/7543895/63886663-66a51500-c9b1-11e9-96ca-f5d3802b387a.png)

When I'm running a single application instance it works fine.

**Comment by Detrav** [comment]
Hi, what are you using?

FastReport.Web requires a live object on the server side, try setting up a sticky session.
