### ISSUE TITLE
Page footer overwritten when using auto size with 'canGrow'

### ISSUE THREAD

**Issue by dfrese** [FastReports/FastReport#124]
Hi,

I'm using a PageFooterBand with `Height = 0` and `CanGrow = true`, to autosize it. This works for the footer alone, but the data content is then written over the footer, when the content happens to fit on the page as if there was no footer.

Looking into the code and debugging a little, I found that `ReportEngine.CalcHeight` is only called at the point in time when the footer is rendered, although the footer height is already used earlier (esp. in `ReportEngine.FreeSpace`).

Is this a bug, or am I missing something?

I managed to find a dirty workaround, by handling the `StartPage` event of the page, and then calling `page.PageFooter.CalcHeight` there.

**Comment by fediachov** [comment]
Hello!

Thanks for waiting. We have fixed this issue in FastReport .NET Core. A bugfix here will be available with next sync after few days and in next release too, of course.
