### ISSUE TITLE
Web Designer Functions availability

### ISSUE THREAD

**Issue by Napokue** [FastReports/FastReport#126]
Hello,

I have recently also posted a post on your forums, but still haven't got an answer, see post [here](https://www.fast-report.com/en/forum/index.php?showtopic=15548). 

My question is: when do you expect to implement the functions for the online designer? We are using the desktop version, and recently tried to migrate the desktop solution to the web, but this is blocking our release.

**Comment by Des1re7** [comment]
Please specify which functions you are talking about.

**Comment by Napokue** [comment]
Of course, as far as I know there are only one set of functions available. 

Here is a screenshot of the desktop version, what I am missing in the web version:

![image](https://user-images.githubusercontent.com/6235760/64612568-6c005780-d3d4-11e9-8665-379e5a311fdf.png)

**Comment by Des1re7** [comment]
We have these features in Online Designer.
![Screenshot](https://user-images.githubusercontent.com/17525590/64616077-74f92500-d3e4-11e9-815f-970592cd825e.png)

**Comment by Napokue** [comment]
Yes I mean those functions. This is for us empty, but I think I have found the problem. 

We haven't instantiated the [AssemblyInitializer](https://github.com/FastReports/FastReport/blob/69a000903c58e662129dc0396f84b8ac693d5e52/FastReport.Base/AssemblyInitializer.cs) class, which takes care of registering all the global properties that have to be set, in order to fully initialize the designer.

I assume you also did this manually or is there an initialization that we aren't using?

**Comment by Napokue** [comment]
I have found it and just like I said: https://github.com/FastReports/FastReport/blob/master/FastReport.Core.Web/Controllers/DesignerController.cs#L203 is the problem. The variable rootFunctions is set, but the functions tree is never returned to the front-end.

**Comment by Napokue** [comment]
Alright thank you, I will check that out.
