### ISSUE TITLE
ComboBox Control  could have some problems on WebReport

### ISSUE THREAD

**Issue by yuhangli1991** [FastReports/FastReport#129]
LineComboBox.ComboBox.DisplayMember = "Name";
LineComboBox.ComboBox.ValueMember = "ID";
LineComboBox.ComboBox.DataSource = tempLineList ;

It  works in fastreport,but it doesn't work in webreport. The combobox has no value.

**Comment by Des1re7** [comment]
Hello,
Can you describe your problem in more detail?

**Comment by yuhangli1991** [comment]
![微信图片编辑_20190916171607](https://user-images.githubusercontent.com/23044388/64946596-ce11fe80-d8a5-11e9-91c3-cea99bda0d1e.jpg)

**Comment by yuhangli1991** [comment]
![微信图片编辑_20190916171802](https://user-images.githubusercontent.com/23044388/64946700-0b768c00-d8a6-11e9-813b-970a3e542fab.jpg)

**Comment by Des1re7** [comment]
Please send an example of your report with an error to us in tickets.
http://support.fast-report.com/
