### ISSUE TITLE
FastReport Designer and adding datasource

### ISSUE THREAD

**Issue by yiwan74** [FastReports/FastReport#131]
Is it possible to add custom datasource (e.g. business object) using FastReport Community designer so I can first design report template and later in code register and use data?
Is there any example how it can be achieved?
Thank you

**Comment by danilobreda** [comment]
Same problem here

**Comment by MaximBalaganskiy** [comment]
It depends on which data source you're using.
E.g. for SQL Server, you can add an MS SQL Connection in the community designer, design and test you report. Then, in your code, load the template and modify the connection
```csharp
report.Report.Load(template);
report.Dictionary.Connections[0].ConnectionString = connectionString;
report.Prepare();
```
If you're using in memory `DataSet` then the quickest way is to create a simple app - a custom designer - which prepares the data set, sets it using `report.RegisterData(dataSet, "ds");` and calls `report.Design()`. After you have saved the report template it will be compatible with your main code which will register the same data set.

**Comment by vitorquezada** [comment]
Did you know if I can edit this data set templates (add columns or remove columns) by the open source or demo designer? Or just manually as you comment?

**Comment by Des1re7** [comment]
@vitorquezada It is best to re-register a modified data set.

**Comment by cyberdarius** [comment]
I created my report from code with BusinnesObject with

report.Dictionary.RegisterBusinessObject(myList, "MyData", 5, true);
report.RegisterData(myList, "MyData");
(Save report .frx)

When i open the report in designer the structure is ok, but without data.
In designer preview the data is blank.

How i can attach dummy data in .frx to design better the report and have a preview with dummy data  ?

What is the best approach to design a new report with designer from my custom object data (no direct database), and have in preview dummy data to see a "real preview"  ?

Thanks

**Comment by cyberdarius** [comment]
I tried also jsonobject (no jsondb who doesn' t manage hyerachical data):

It attach dummy data in JsonDataSourceConnection (good) and generate the structure in 
JsonTableDataSource. 

But the types in JsonTableDataSource doesn't only support (string, double, bool.... NO datetime, decimal, nullable<T>   and other.

I tried including jsonschema (from newtosoft jsonschema)
            JSchemaGenerator generator = new JSchemaGenerator();
            JSchema myJsonSchema = generator.Generate(typeof(myObject));

            Report report = new Report();
            var jDSCSB = new FastReport.Data.JsonConnection.JsonDataSourceConnectionStringBuilder();
            jDSCSB.JsonSchema = myJsonSchema.ToString() ;
            jDSCSB.Json = myJson;

            var jDSC = new FastReport.Data.JsonConnection.JsonDataSourceConnection();
            jDSC.ConnectionString = jDSCSB.ConnectionString;
            jDSC.CreateAllTables(string.IsNullOrWhiteSpace(pJsonSchema));
            report.Dictionary.Connections.Add(jDSC);
            return SaveReport(report, myReportFileName);

How i can create a new report from code or designer with full schema datatypes like RegisterBusinessObject do  ? 

Even i change the type on designer, the next time my jsonobject change the engine revert all to basic types (string ...)

Thanks

**Comment by haraldkofler** [comment]
I just tried to register an object by doing as you suggested:

registered the Data by 

> report.registerData(dataset);

but the method Design() is not known?

Any suggestions on how to import this function?

Thanks

**Comment by 0legK** [comment]
Hi,

FastReport OpenSource does not include Designer. It's available in FastReport .NET.

Best Regards,
Oleg.

**Comment by BogdanStegachev** [comment]
I'm sending you a test example of using the BusinessObject connection and using it in the report designer below

Application: https://drive.google.com/file/d/1qekxtTnNYi3elh_snKjY9rFOBXGYoSVJ/view?usp=sharing

Best regards,
Bogdan
