### ISSUE TITLE
Documentation for 2019.4

### ISSUE THREAD

**Issue by Detrav** [FastReports/FastReport#132]
Need to update documentation for FastReport.OpenSource 2019.4. Use DocFX to build documentation. Also try to build a PDF.

----

Task list:

- [x] Fork, clone and obtain a copy of documentation and FR repo.
- [x] Build a new documentation for reference
- [x] R&D for PDF plugins for DocFX
- [x] Try to create PDF documentation for FastReport.OpenSource

----

Related links:

[Documentation](https://github.com/FastReports/FastReport.Documentation)
[DocFX](https://dotnet.github.io/docfx/)

**Comment by GlebStryukov** [comment]
[FastReports Documentation.pdf](https://github.com/FastReports/FastReport/files/3750327/FastReports.Documentation.pdf)
[ClassReference Documentation.pdf](https://github.com/FastReports/FastReport/files/3750328/ClassReference.Documentation.pdf)
