### ISSUE TITLE
not working about Viewer.exe *.fpx /P

### ISSUE THREAD

**Issue by Memento1990** [FastReports/FastReport#133]
I want to use `View.exe *.fpx /P` to print report, but no response after running this command. Also running command `View.exe /P` directly.

**Comment by Detrav** [comment]
In the OpenSource version, you are not able to print with a viewer or designer, only browser and web report. https://fastreports.github.io/FastReport.Documentation/COMPARISON.html

**Comment by Memento1990** [comment]
😄 thanks for your prompt reply. I got it!
