### ISSUE TITLE
Web Designer Functions availability

### ISSUE THREAD

**Issue by natsuzz** [FastReports/FastReport#135]
Hello,

I have recently also posted a post on your forums, but still haven't got an answer.

I was told to make a new issue with a reverence to the old one (https://github.com/FastReports/FastReport/issues/126)

My question is: when do you expect to implement the functions for the online designer? We are using the desktop version, and recently tried to migrate the desktop solution to the web, but this is blocking our release.

Here is a screenshot of the desktop version, what I am missing in the web version:
![64612568-6c005780-d3d4-11e9-8665-379e5a311fdf](https://user-images.githubusercontent.com/14810196/69346429-056ca500-0c73-11ea-8b91-a2510fdef8cf.png)

**Comment by 8VAid8** [comment]
Hello!
There were implemented fixes for  functions in Core and Open Source versions. Check it out and write us if you still having issues.
