### ISSUE TITLE
FastReport.OpenSource.Web support .Net Core 3.0?

### ISSUE THREAD

**Issue by Juandah88** [FastReports/FastReport#139]
I have this problem when I render the report. I render the report like this: 
`@ViewBag.WebReport.Render();`

`               var webReport = new WebReport();
                webReport.Report.Load(@"\report.frx");
                foreach (var item in paramether)
                {
                    webReport.Report.SetParameterValue(item.Key, item.Value);
                }
                webReport.Report.RegisterData(datos, "Mydata");
                 ViewBag.WebReport = webReport;`

**System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[Microsoft.AspNetCore.Html.HtmlString,FastReport.Web.WebReport+<Render>d__107]**

**Comment by Detrav** [comment]
Yes, FR supports .NET Core 3, try to add await to render. `@await ViewBag.WebReport.Render();`
