### ISSUE TITLE
FastReport.OpenSource "Barcode" object, DataMatrix type, control codes handling

### ISSUE THREAD

**Issue by vvche69** [FastReports/FastReport#142]
The "Barcode" object, with type "DataMatrix" treats sequence "&1;" in incoming data as a control code FNC1. Sometimes it's not necessary and incoming string must be encoded "as is", There is a property "AutoEncode", but it works only for Code128 barcodes. Is it possible to add this property to DataMatrix barcodes?

Thank you.

**Comment by Detrav** [comment]
I've added feature to a task list for development team.

**Comment by vvche69** [comment]
Thank you.

**Comment by vvche69** [comment]
Upon reflection, I think there would be another problem - how to create GS1-DataMatrix barcodes? GS1-DataMatrix  contains FNC1 as a first symbol, so in such case we need a sequence "&1;" to create FNC1, but only if such sequence starts an input string. 
If "&1;" is located inside an input string, it shouldn't be treated as special code.  Conflicting requirements?

Or maybe, is it possible to implement a separate type for GS!-DataMatrix barcodes?

**Comment by KirillKornienko** [comment]
Hello. Please download the latest version and check. Perhaps this bug was fixed.

**Comment by vvche69** [comment]
> 
> 
> Hello. Please download the latest version and check. Perhaps this bug was fixed.

Добрый день!
У объекта Barcode c типом "DataMatrix" появилась возможность задать тип GS1? 
Сходу не увидел, если можно, покажите, пожалуйста, как?
Спасибо.
