### ISSUE TITLE
PdfSimpleExport fails to generate pdf file

### ISSUE THREAD

**Issue by bacr** [FastReports/FastReport#144]
PdfSimpleExport throws error: 
`Could not load file or assembly 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'`

The reason is because FastReport.OpenSource.Export.PdfSimple project is still referencing FastReport.OpenSource 2020.1.0 which used CoreCompat.System.Drawing instead of System.Drawing.Common

**Comment by jeftegoesdev** [comment]
Same problem

**Comment by cursorme** [comment]
Hi.. same situation here.... if I Add CoreCompat.System.Drawing from nuget (1.0.0-beta006) then I geta different error: An exception of type 'System.MissingMethodException' occurred in FastReport.OpenSource.Export.PdfSimple.dll but was not handled in user code: 'Method not found: 'Void FastReport.Utils.FRPaintEventArgs..ctor(System.Drawing.Graphics, Single, Single, FastReport.GraphicCache)'.

**Comment by Detrav** [comment]
I think is needed to rebuild the plugin with a new link to FastReport Open Source nuget package. I added a task for fr.net team.

https://github.com/FastReports/FastReport/blob/3404cf6b77ac560552b2307b77982a3547a51158/Extras/OpenSource/FastReport.OpenSource.Export.PdfSimple/FastReport.OpenSource.Export.PdfSimple/FastReport.OpenSource.Export.PdfSimple.csproj#L27

**Comment by cursorme** [comment]
Thanks for the quick feedback. Will keep an eye on the nuget package to see when a new version is available.

**Comment by progeriof** [comment]
> Hi.. same situation here.... if I Add CoreCompat.System.Drawing from nuget (1.0.0-beta006) then I geta different error: An exception of type 'System.MissingMethodException' occurred in FastReport.OpenSource.Export.PdfSimple.dll but was not handled in user code: 'Method not found: 'Void FastReport.Utils.FRPaintEventArgs..ctor(System.Drawing.Graphics, Single, Single, FastReport.GraphicCache)'.

Confirmed this has also happened to me. 

Watching over a fix

**Comment by Juandah88** [comment]
> Same problem

could you solve it?

**Comment by Juandah88** [comment]
> PdfSimpleExport throws error:
> `Could not load file or assembly 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'`
> 
> The reason is because FastReport.OpenSource.Export.PdfSimple project is still referencing FastReport.OpenSource 2020.1.0 which used CoreCompat.System.Drawing instead of System.Drawing.Common

Could you solve it?

**Comment by cursorme** [comment]
> > PdfSimpleExport throws error:
> > `Could not load file or assembly 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'`
> > The reason is because FastReport.OpenSource.Export.PdfSimple project is still referencing FastReport.OpenSource 2020.1.0 which used CoreCompat.System.Drawing instead of System.Drawing.Common
> 
> Could you solve it?

I think problem is already solved. We are waiting for a new nuget package or you can try to compile it on your own.

**Comment by mpatdev** [comment]
Hello, i have the same problem. With FastReport.OpenSource 2020.1.0. Any solution?

**Comment by Juandah88** [comment]
I changed the version to 2019.4.0

**Comment by Juandah88** [comment]
> Hello, i have the same problem. With FastReport.OpenSource 2020.1.0. Any solution?

I changed the version to 2019.4.0

**Comment by DerNobbi** [comment]
> I think, is needed to rebuild the plugin with a new link to FastReport Open Source nuget package. I added a task for fr.net team.
> 
> https://github.com/FastReports/FastReport/blob/3404cf6b77ac560552b2307b77982a3547a51158/Extras/OpenSource/FastReport.OpenSource.Export.PdfSimple/FastReport.OpenSource.Export.PdfSimple/FastReport.OpenSource.Export.PdfSimple.csproj#L27

That worked for me. Link the release assembly into your project (no NuGet Package).

**Comment by danilobreda** [comment]
Same problem on 2020.1
