### ISSUE TITLE
FastReport does not load resources 2020.1.0

### ISSUE THREAD

**Issue by jeftegoesdev** [FastReports/FastReport#145]
Hi!

Version 2019.4.0
![work](https://user-images.githubusercontent.com/15343678/70579443-665f0d00-1b8f-11ea-8364-4a5d2b8e1b87.PNG)

Version 2020.1.0
![dont work](https://user-images.githubusercontent.com/15343678/70579442-665f0d00-1b8f-11ea-86d5-b3bddad638f8.PNG)

I even updated the project demo (FastReport.OpenSource.Web.MVC) itself and it gave the same problem.

**Comment by cnkker** [comment]
yes,i have same problem

**Comment by Des1re7** [comment]
We reproduced the problem. I added task to the development team.

**Comment by Braytiner** [comment]
Same problem here.

**Comment by mjftechnology** [comment]
Resources are being retrieved with an incorrect namespace in the Resources.cs file. The method is GetBytes() .

This line returns the wrong assembly name and hence the resources do not get resolved:

var resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(fullname);

**Comment by mjftechnology** [comment]
@Des1re7 Added a PR if you get chance to review

**Comment by mjftechnology** [comment]
Any progress guys?

**Comment by KirillKornienko** [comment]
Hello! We fixed this error in the last MR #178. Nuget package version: 2020.2.9 (https://www.nuget.org/packages/FastReport.OpenSource/2020.2.9). Please, try this changes and share your opinion.

**Comment by Braytiner** [comment]
I updated and the error remains.

**Comment by KirillKornienko** [comment]
@Braytiner you updated FastReport.OpenSource or FastReport.OpenSource.Web? In the latest version FastReport.OpenSource.Web (2020.2.9) this bug is missing.
@mjftechnology , please, share your opinion.

**Comment by mjftechnology** [comment]
@KirillKornienko Yes its fixed for me, thank you

**Comment by Braytiner** [comment]
I updated FastReport.OpenSource and FastReport.OpenSource.Web.

![fastreport](https://user-images.githubusercontent.com/11064602/79382908-ac135400-7f3a-11ea-8d29-52d4de76ccbb.png)

**Comment by Braytiner** [comment]
I forgot to add

app.UseFastReport();

in my Startup class, Configure method.

After do this, it worked showing all icons

Sorry for inconvenience
