### ISSUE TITLE
Some Shapes do not appear

### ISSUE THREAD

**Issue by jeftegoes** [FastReports/FastReport#148]
Works Perfect on FastReport Community (Preview)
![preview ok](https://user-images.githubusercontent.com/15343678/71198680-14934280-2273-11ea-848b-f5fb16d76578.PNG)

Works Perfect on WebReport
![webreport ok](https://user-images.githubusercontent.com/15343678/71198697-22e15e80-2273-11ea-8a8e-03d7ab2155e6.PNG)

But when I send it to the printer, whatever it is, it doesn't print some shapes
![print or export](https://user-images.githubusercontent.com/15343678/71198741-3d1b3c80-2273-11ea-8064-da3d41a0a693.PNG)

**Comment by jeftegoesdev** [comment]
I saw that I had a 2019.4.0 fix for 2020.1.0 related to shapes, I tested with 2020.1.0 and the same problem happens

**Comment by Des1re7** [comment]
The problem was reproduced.
The task was created 👌
