### ISSUE TITLE
Picture Image Base64

### ISSUE THREAD

**Issue by jeftegoes** [FastReports/FastReport#149]
Hi,

My webapi return this json sctructure
![myjson](https://user-images.githubusercontent.com/15343678/71497872-d8468000-2838-11ea-83c0-be5c30b81219.PNG)

this name-value "marca" image is in base64 format, works perfectly when converting and also works in fastreport when using TextRenderType = HtmlTags property
![work fine](https://user-images.githubusercontent.com/15343678/71497981-48550600-2839-11ea-9cbe-0b84fce26be4.PNG)

**First problem:**
![problems](https://user-images.githubusercontent.com/15343678/71498028-789ca480-2839-11ea-904c-9affc32a487c.PNG)
![dont respect](https://user-images.githubusercontent.com/15343678/71498196-21e39a80-283a-11ea-9df2-c4f2627c9059.PNG)

fastreport community renders the image but doesn't respect the html width and heigth tags so I can resize the image, detail that the object is a text and not a picture
**Obs: works fine on webreport**

**Second problem:**
Simply placing the object formatted by the designer in the report generates the following error:
![problem 2](https://user-images.githubusercontent.com/15343678/71498144-ef39a200-2839-11ea-80c4-35126ea62438.PNG)
![problem 3](https://user-images.githubusercontent.com/15343678/71498148-f19bfc00-2839-11ea-8ad6-42e4bbaaca2b.PNG)

**In CrystalReport(SAP) when I made this bind I used the picture object (fastreport don't work), 
as it is today, I have to manipulate the image to upload it to be right in the report**

**Comment by tngo8** [comment]
Hi you might already found a solution for yourself, but I want to add mine just in case. You can actually Right click on the **JSON** table then click on **new Calculated Column** and on the property panel of the new calculated column, set DataType to Byte[], expand the Expression popup editor and type in 
Convert.FromBase64String([JSON.item.Image]) whereas JSON.item.Image is your Base64 string column
