### ISSUE TITLE
Report Viewer Menu images not shown

### ISSUE THREAD

**Issue by EasyLOB** [FastReports/FastReport#151]
Hi,
I created am ASP.NET Core MVC example following your instructions.
The report is shown but the Report Viewer Menu icons are not shown.
The following URL is not found:

**https://localhost:44315/_fr/resources.getResource?resourceName=reload.svg&contentType=image%2Fsvg%2Bxml**

Should I copy the *.svg files somewhere in my Project ? wwwroot ?

The report images, like the one below, are shown correctly:

**https://localhost:44315/_fr/preview.getPicture?reportId=fb75003bfca3405fa6a869b562dbfd44&pictureId==65F5CDB906DC0D3B1F5504044AACED48**

Thanks

**Comment by jeftegoesdev** [comment]
Hi,

Look this [https://github.com/FastReports/FastReport/issues/145](url)

**Comment by KirillKornienko** [comment]
Hello! We fixed this error in the last MR #178. Nuget package version: 2020.2.9 (https://www.nuget.org/packages/FastReport.OpenSource/2020.2.9). Please, try this changes and share your opinion.

**Comment by mjftechnology** [comment]
This is broken again in 2020.3.0. I am unable to use a new version due to Issue #192
