### ISSUE TITLE
Save and Open *.fr3 extension

### ISSUE THREAD

**Issue by jeftegoesdev** [FastReports/FastReport#153]
Hi!

The communit version by designer allows saving to * .fr3 but cannot open.

Save as windows:
![save fr3](https://user-images.githubusercontent.com/15343678/71698862-e85fe180-2d9b-11ea-93f4-92ef342f154f.png)

Open window:
![dont open fr3](https://user-images.githubusercontent.com/15343678/71698866-e9910e80-2d9b-11ea-8261-6bd895383925.png)

* .Fr3 extension works correctly in delphi

**Comment by Des1re7** [comment]
This format is used for export to FR VCL. It shouldn't open in FR.Net

**Comment by sokolinivan** [comment]
> Этот формат используется для экспорта в FR VCL. Он не должен открываться в FR.Net


Hello. Is there a way to convert in the opposite direction? Fp3 to fpx? We have a code that generated reports under VCL, and now there is a code that, it seems, cannot work with fp3.
