### ISSUE TITLE
support Postgresql version 12 and version 4.x of Npgsql driver

### ISSUE THREAD

**Issue by githubfanster** [FastReports/FastReport#154]
Hello!

Just downloaded FastReport Community Designer.
we're using Postgresql version 12 and latest version (4.x) of Npgsql.

When creating a Data Source for my first Report Template, the test connection for Postgresql i specified succeeded but when i tried to select a table for use in my report template, i got the following error:
ERROR: 42703 column ad.adsrc does not exist

which seems related to:

https://github.com/npgsql/EntityFramework6.Npgsql/issues/138

I believe Npgsql's latest driver does not have this problem, but it seems FastReport is still using version 3 of Npgsql and has not updated to version 4?

Please see attached PNG for additional info.

Thanks!
![Error_Column does not exit-FastReportCommunity](https://user-images.githubusercontent.com/35359869/71801679-94544600-3096-11ea-8b73-0274c651d4fa.png)
![Error_Column does not exit-FastReportCommunity](https://user-images.githubusercontent.com/35359869/71801693-a209cb80-3096-11ea-99de-df8749e651ab.png)

**Comment by githubfanster** [comment]
is it possible to recompile FastReport.Data.Postgres using version 4.x of Npgsql instead? 

would setting 
    public static bool EnableSystemSchemas { get; set; }
to false in PostgresDataConnection be a possible workaround as well?

**Comment by JeremyWu917** [comment]
NEED HELP!!!
I ran into the same problem when I selected the tables.
And I'm using the latest version.
[FastReport Open Source 2020.4.0](https://github.com/FastReports/FastReport/releases)

**Comment by drechema** [comment]
I also have the same problem... [there is a change between PG versions](https://stackoverflow.com/questions/58789024/postgres-error-column-d-adsrc-does-not-exist)

There is any workaround in order to edit a Report from the designer?

**Comment by kilonzo4** [comment]
Am also getting the same error with postgres 12. (ERROR: 42703 column ad.adsrc does not exist)
Did anyone find a workaround?

**Comment by drechema** [comment]
My only workaround was downgrade to PG 11 👎

**Comment by ascanoid-dev** [comment]
Hello,
I had/have the same problem! Unfortunately I can't downgrade to PG 11.....blocked with my current tasks :-(
Any updates?
Thanks

**Comment by sandord** [comment]
I've encountered the same problem today.

As far as I can tell, the community designer is not part of this repository so there's no way for us to create a fork and fix the issue.

I've managed to work around it though:

- Add a data source
  - Set up or select a proper database connection.
  - Don't select any tables but click *Add SQL Query* instead.
  - Click *Next*.
  - Enter a valid SQL query.
  - Click *Next* twice.
  - Click *OK* when the "ad.adsrc" error shows.
  - Click *Finish* twice.
- Manually add the columns.
  - In the Data tree, expand Data Sources, Connection and Table (or whatever you called your query).
  - Right-click on the Table item and add use "New calculated column" to add a calculated column for each query column you'd like to use on the report.
  - Set 'Calculated' to *False* for each calculated column and update the alias to match the SQL column name.

You can now drag the column nodes from the Data tree onto the desired band.

**Comment by ascanoid-dev** [comment]
Great workaround indeed! It works for me (PG12)!
Thank you!

**Comment by sandord** [comment]
By the way, you can always do a lot more by editing the report file by hand. I sometimes create something (e.g. a relation) for SQL server and then convert it to Postgres by editing the XML.
