### ISSUE TITLE
autosize bug?

### ISSUE THREAD

**Issue by zengzhaoyuan** [FastReports/FastReport#155]
![image](https://user-images.githubusercontent.com/7639603/71865408-97eed800-313d-11ea-97d8-96b727c9e18e.png)

![image](https://user-images.githubusercontent.com/7639603/71864800-d7b4c000-313b-11ea-99a6-e7028606abf5.png)

The text cannot be automatically resized when it is set
TableCell Name="Cell6" Border.Lines="All" Border.Color="Silver" Text="**深蓝色简约大气风格双肩包**"
![image](https://user-images.githubusercontent.com/7639603/71864904-2eba9500-313c-11ea-9fab-46b97e5c70cf.png)

In another case, it's OK
TableCell Name="Cell6" Border.Lines="All" Border.Color="Silver" Text="**这是内容啊啊啊啊啊啊啊啊啊啊啊**"
![image](https://user-images.githubusercontent.com/7639603/71865106-bb655300-313c-11ea-9892-0d0fe35ca9d0.png)

I guess the width of the content word is set as a positive multiple of the width, so there is no problem？

How can I display all the words？

**Comment by ATZ-FR** [comment]
Have you tried this with full version (FastReport.Net Demo is enough)? It works well on my Win7 PC. 
![изображение](https://user-images.githubusercontent.com/44577155/83556506-b6080b00-a518-11ea-87e2-7d4cd1bafb19.png)
