### ISSUE TITLE
Error when passing an ordered list in Report.RegisterData

### ISSUE THREAD

**Issue by Braytiner** [FastReports/FastReport#157]
I'm using business objects, so when I use:

webReport.Report.RegisterData(itens.OrderBy(i => i.Description), "Products");

and execute the report I have the following error:

NotSupportedException: Specified method is not supported. 

It works when I remove .OrderBy

**Comment by Des1re7** [comment]
Try use **ToArray** after **OrderBy** command

**Comment by Braytiner** [comment]
Thanks! It worked!

**Comment by contronics-naveed** [comment]
ToArray also worked for me.. Thanks @Des1re7
