### ISSUE TITLE
Report.Print() ?

### ISSUE THREAD

**Issue by EJLANDETAR** [FastReports/FastReport#159]
Is it on the agenda to add a method to print directly?

**Comment by fediachov** [comment]
We have no such plans yet.

**Comment by rftd** [comment]
https://github.com/rftd/FastReport.OpenSource.Winforms

**Comment by nm-1216** [comment]
![image](https://user-images.githubusercontent.com/16759471/121394224-b46eef80-c983-11eb-90d2-c0474208e9ed.png)

**Comment by fediachov** [comment]
WinForms printing and many other features are available in FastReport .NET https://www.fast-report.com/en/product/fast-report-net/
Look on the Comparison https://www.fast-report.com/en/fast-report-comparison/
