### ISSUE TITLE
.netcoreapp 3.0 winforms support for FastReport.OpenSource

### ISSUE THREAD

**Issue by dag23** [FastReports/FastReport#160]
When I install NuGet package in a .netcore 3.0 winforms app there is a conflict with the classes in the file WindowsFormsReplacement.cs. ¿Could you add new target framework for .netcoreapp3.0?

**Comment by KirillKornienko** [comment]
Hello! In the latest version FastReport.OpenSource 2020.3 we fixed this problem. Please, try this changes and share your opinion.

**Comment by dag23** [comment]
Thank you. It seems to compile now.
