### ISSUE TITLE
Printed bar code is not recognized by barcode reader

### ISSUE THREAD

**Issue by Braytiner** [FastReports/FastReport#161]
After many problems with different barcodes, I follow theses recommendations and it worked for EAN 13 and Code 128: 

Set the barcode AutoSize = false, zoom = 1, and set barcode width = 27.77 mm

but other symbologies aren't recognized by barcode reader.

**Comment by Des1re7** [comment]
Send the barcode data on which I can reproduce it. For me, both barcodes work correctly with default parameters.

**Comment by Braytiner** [comment]
You can download the report file [here](https://1drv.ms/u/s!As0ugFqi9gYmspgRN8kcmFi9zrjqfQ?e=4irwNU)

Code 128 aren't recognized too.

Barcode data:

34768 (Code 128)
34717 (Code 128)
20-0079 (Code 128)
00192018227200 (Code 128)

718037810775 (UPC-A)
718037779911 (UPC-A)
718037858494 (UPC-A)

65833254 (EAN 8)
40170725 (EAN 8)
95050003 (EAN 8)

Thanks for you help! :)

**Comment by Des1re7** [comment]
I still recognize all codes with default settings. [Here ](http://ipic.su/img/img7/fs/kiss_554kb.1579614256.jpg) is my export result in picture.

**Comment by Braytiner** [comment]
I'm printing these labels using Argox OS 214. On paper, barcodes cannot be read by barcode scanner.

When barcode is large its works, but when is narrow, doesn't. Some bars of code didn't print with correctly width.

Problem occurs when I print the barcode.

I read something about GDI and the way FatsReport render barcodes and how its impact printed barcodes.

**Comment by Des1re7** [comment]
This a limitation of your printer. The print width of the line does not match the print width of the printer. For fix it, you need to manually select the necessary Zoom parameter for your printer.

**Comment by Braytiner** [comment]
When I print out Fast report it works. So it's not limitation of my printer.

**Comment by fediachov** [comment]
FastReport Open Source does not support direct printing. What did you print? Through web application? Web page has small dpi value for barcode printing.

**Comment by Braytiner** [comment]
> FastReport Open Source does not support direct printing. What did you print? Through web application? Web page has small dpi value for barcode printing.

Yes, I'm printing through web application. Is There another way?

**Comment by Braytiner** [comment]
> FastReport Open Source does not support direct printing. 

Searching topics, I saw direct print is in RoadMap. 

What is the current status for this feature?

**Comment by Alekarfes** [comment]
Please try enabling the AutoEncode option and tell us if that helped or not.
