### ISSUE TITLE
After updating to asp.net core 3.1 report icon is bugged.

### ISSUE THREAD

**Issue by xshiiiidev** [FastReports/FastReport#163]
I already see that the dependency requirements of the fast report is only asp.net core 2.X

But I still proceeded and use it on my asp.net core 3.1 project because I don't have any other good choice for reporting.

So everything works great, the only problem I encountered so far is this.

![image](https://user-images.githubusercontent.com/19402130/73429285-3b668d80-4376-11ea-8206-343e3642c945.png)

The icons are missing for the 

> Refresh Report
> Save File
> Print
> Zoom

Note that, only the icons are missing their functions are still working great!

Hoping for a fix soon or a fully compatible asp.net core 3.1 fast report.

Thanks guys!

**Comment by mnourn** [comment]
Try downgrade FastReport version to '2019.4.0', it's working fine for me.

**Comment by xshiiiidev** [comment]
It works thanks mate!

**Comment by xshiiiidev** [comment]
I will close this for now, but any one wanted to open it go ahead. This fix is only temporary and did not really fixed the main problem.
