### ISSUE TITLE
PDFSimpleExport failing on 2020.1

### ISSUE THREAD

**Issue by danilobreda** [FastReports/FastReport#165]
PdfSimpleExport throws error:

> Could not load file or assembly 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

#144 
_.net core 3.1_
2019.3.19 works...

**Comment by Des1re7** [comment]
Recent versions using [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/) instead of CoreCompat.System.Drawing

**Comment by danilobreda** [comment]
> 
> 
> Recent versions using [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/) instead of CoreCompat.System.Drawing

The nuget is using System.Drawing.Common, but the error persists, the only nugets on my project are  the pdfsimple and fastreport

**Comment by fredericoregateiro** [comment]
just updated to version 2020.1.20 and tested on a avaloniaui v0.9.3 on dotnet core 3.1
The PDFSimpleExport is working

**Comment by KirillKornienko** [comment]
Hello! @danilobreda We fixed this problem early. Do you still have difficulty with this? Thanks.

**Comment by danilobreda** [comment]
Problem resolved! 👍
