### ISSUE TITLE
Bar code generated in linux

### ISSUE THREAD

**Issue by Elmina241** [FastReports/FastReport#166]
Bar code generated in Windows looks like this:
![image](https://user-images.githubusercontent.com/14195711/74909541-44420080-5404-11ea-99dc-0df576de5cff.png)
But after deployment on server (CentOS 7) the same bar code looks like this:
![image](https://user-images.githubusercontent.com/14195711/74909935-0db8b580-5405-11ea-911a-07bb800ae31b.png)
 What could be the reason?

**Comment by tvavrda** [comment]
Did you solve this issue?
