### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by fredericoregateiro** [FastReports/FastReport#167]
I tried this on Xamarin and i got a not supported platform exeception.
Will Xamarin be supported?

**Comment by elbeshenrique** [comment]
I was wondering that too

**Comment by Julibazzi** [comment]
Any news about this situation?

**Comment by Detrav** [comment]
Xamarin is still not supported. :( :( :( #103 

Fast reporting is heavily dependent on the use of System.Drawing, mainly text measures and image sizes. 

So far, because of the Enteriprise, I don’t think that the FR.Net team will replace System.Drawing with something else. I really hoped for Microsoft, but in Core 3 and in Net 5 System.Drawing is not become part of the xamarin platform.

**Comment by psohm** [comment]
@Detrav hello there is a new release with .net 5 RC, did you try it ? 👍

**Comment by Detrav** [comment]
Yes, I tested it, there is no news, in general FR works on net 5 rc.1, but System.Drawing.Common is still not available.

I have ideas for moving the graphics engine into a separate module, this will allow drawing reports on android, ios, wasm (e.g.  skiasharp).  But this is not a priority for the FR.Net team yet… As far as I know.

There are several limitations why reporting on mobile is bad:
1. This is downloading data from DB, it is not safe.
2. Resources for building a report. No matter how quickly it is built, it all the same eats memory. 300mb-1gb medium to large report.
3. It is aesthetically wrong to build a report on the user's phone.
4. The battery will be discharged.

A good solution is to build a report on the server. And make a mobile application through api.

The full version of FastReport has svg export, which looks good on the phone. For OpenSource, this is the html version and the web report.

But I'm still in favor of the graphics engine separation! :)

**Comment by psohm** [comment]
@Detrav hello, there is a new beta version of .net core 6
can you look after ? :)

**Comment by Detrav** [comment]
Quite a bit watching the news, haven't tested anything yet. 
I will text with the result, maybe skip preview 1.

**Comment by dfyx** [comment]
> 1. This is downloading data from DB, it is not safe.
> 2. Resources for building a report. No matter how quickly it is built, it all the same eats memory. 300mb-1gb medium to large report.
> 3. It is aesthetically wrong to build a report on the user's phone.
> 4. The battery will be discharged.

While I generally agree with you, there are more use cases than just classic database reporting. For example, we have an application that ships with reports that are prebuilt by the developers and baked into the executable. At runtime they are populated with locally-available data. We use this for example to insert names and addresses into forms that then get printed and completed by hand or for invoices.

Regarding the missing `System.Drawing`, Microsoft has released a NuGet package called `System.Drawing.Common` that makes most of `System.Drawing` available cross-platform. I've never tried it in Xamarin but generally it should work.

**Comment by SLenik** [comment]
@devjama hello! I've just found out that commercial version of FastReport supports Skia (see https://www.fast-report.com/en/news/show/fastreport-net-2022.3/)

**Comment by alexsherkhan** [comment]
At the moment, the team has no plans to add Skia support to FastReport Open Source.
But you can use Skia support in the paid version which will allow you to use Xamarin.
Read about all the advantages of Skia in this article:
https://www.fast-report.com/en/blog/show/fastreport-core-skia/

**Comment by psohm** [comment]
does someone test it under mobile version with xamarin ?

**Comment by alexsherkhan** [comment]
At the moment, since the team has not officially announced Xamarin support, the team cannot guarantee full Xamarin support. But I've been running tests on Android, and most likely Xamarin support will be announced later, perhaps even in the next minor release.

**Comment by psohm** [comment]
any news on this enhancement ?
