### ISSUE TITLE
PDFSimpleExport exports arabic words in LTR direction instead of RTL

### ISSUE THREAD

**Issue by vkuttyp** [FastReports/FastReport#172]
Fast-reports is really gaining popularity every day. 
When I tried to export a .frx report which contains Arabic characters, I noticed that Arabic words are exported to pdf in the LTR order.
The easiest way to check the issue is by using the online report supplied by fast-report.com at the URL:  https://www.fast-report.com:2018/11
This URL points to .net core sample interactive forms. Try typing an Arabic word for example المملكة العربية السعودية (Kingdom of Saudi Arabia)
After writing the above word and export it as PDF. You will see that the Arabic words are misplaced.
[Interactive Forms.pdf](https://github.com/FastReports/FastReport/files/4362902/Interactive.Forms.pdf)

**Comment by vkuttyp** [comment]
I did my research on this issue. I could find a similar problem with iTextsharp at [http://geekswithblogs.net/JaydPage/archive/2011/11/02/using-itextsharp-to-correctly-display-hebrew--arabic-text-right.aspx](url)  and [https://stackoverflow.com/questions/34528259/arabic-in-pdf-using-itextsharp-in-c-sharp](url)

**Comment by fediachov** [comment]
Thanks for your request! We need some time to fix this issue.

**Comment by fediachov** [comment]
Please read the article that can solve this problem https://opensource.fast-report.com/2020/10/building-libgdiplus-library-from-source.html
