### ISSUE TITLE
FastReport.OpenSource Generate Report and attach dummy data for design preview

### ISSUE THREAD

**Issue by cyberdarius** [FastReports/FastReport#173]
I created my report from code with BusinnesObject with

report.Dictionary.RegisterBusinessObject(myList, "MyData", 5, true);
report.RegisterData(myList, "MyData");
(Save report .frx)

When i open the designer to design my newly created report the structure is ok, but without data.
In designer preview the data is blank so i can't see the result of work.

How i can attach dummy data in .frx to better design the report and have a preview with dummy data (BusinnessObject) ?

What is the best approach to design a new report with designer from my custom object data (no database), and have in preview dummy data to see a "real preview" ?

Thanks

**Comment by cyberdarius** [comment]
I tried also jsonobject (no jsondb who doesn' t manage hyerachical data):

It attach dummy data in JsonDataSourceConnection (good) and generate the structure in 
JsonTableDataSource. 

But the types in JsonTableDataSource doesn't support (string, double, bool yes .... NO datetime, decimal, nullable<T> and other).

I tried including jsonschema (from newtosoft jsonschema) without success.

            JSchemaGenerator generator = new JSchemaGenerator();
            JSchema myJsonSchema = generator.Generate(typeof(myObject));

            Report report = new Report();
            var jDSCSB = new FastReport.Data.JsonConnection.JsonDataSourceConnectionStringBuilder();
            jDSCSB.JsonSchema = myJsonSchema.ToString() ;
            jDSCSB.Json = myJson;

            var jDSC = new FastReport.Data.JsonConnection.JsonDataSourceConnection();
            jDSC.ConnectionString = jDSCSB.ConnectionString;
            jDSC.CreateAllTables(true);
            report.Dictionary.Connections.Add(jDSC);
            return SaveReport(report, myReportFileName);

How i can create a new report from code or designer with full correct schema with datatypes like RegisterBusinessObject do  ? 

Even if i change the type on designer, later the next time my jsonobject changes and i reapply the schema the engine revert all to basic types (string ...)

Thanks

**Comment by haraldkofler** [comment]
Have you found a solution for this?
I'm stuck on the same point. Documentation lacks on examples for the business object interface and how to get those definitions in the report(-designer)

**Comment by cyberdarius** [comment]
With BusinnessObject in unusable because we can't have data at design time ....

We are trying to use di Json Object data approach, but the generation of JsonSchema described up does not work.

At now we are trying to :
1. generate a new report from code with JsonDataSourceConnectionStringBuilder
then save the newly created report (.frx).

2. After this (always from code) we open the .frx and substitute each properties from "System.String" to .net datatypes using reflection on source poco object.

ex.
```
      <JsonTableDataSource Name="JSON" DataType="FastReport.Data.JsonConnection.JsonParser.JsonArray" Enabled="true" TableName="JSON">
            <Column Name="FromDate" DataType="System.String"/>
      </JsonTableDataSource>
```

become :
```
      <JsonTableDataSource Name="JSON" DataType="FastReport.Data.JsonConnection.JsonParser.JsonArray" Enabled="true" TableName="JSON">

              <Column Name="FromDate" DataType="System.DateTime"/>

      </JsonTableDataSource>
```
3. And now we open the winforms designer to design the report.


Without the possibility to design with dummy data the report from BusinnessObjectData (POCO) or an easy way to generate correct JSON Schema, FastReport can't be used in real world applications ... this should be a top priority; (or at least a dummy string with system type in preview)

The best approach would be implementing to the Dictionary of BusinnessObject (1st post) who generate the correct datatypes; adding a new property with the serialized poco instance ignored at runtime but to used at design time. (Like JsonDataSourceConnection.ConnectionString do for the json approach)

We are considering whether it deserves to use it or not.

**Comment by haraldkofler** [comment]
@cyberdarius Thanks for explaining your work in progress.

Just to better understand: With the approach of your 1st post (registerBusinesssObject, ...) you have been able to generate a report.frx containing the definition of the properties for the report. With this definition you have been able to design a report containing these properties and you have been able to "populate" those field with data from runtime?

If so, could you then please port a snippet with the save method etc.? I do not understand how to generate this frx with property definition. (Seeing example data in the designer would then be my next problem ;)

**Comment by cyberdarius** [comment]
> @cyberdarius Thanks for explaining your work in progress.
> 
> Just to better understand: With the approach of your 1st post (registerBusinesssObject, ...) you have been able to generate a report.frx containing the definition of the properties for the report. With this definition you have been able to design a report containing these properties and you have been able to "populate" those field with data from runtime?
> 

YES

> If so, could you then please post a snippet with the save method etc.? I do not understand how to generate this frx with property definition. (Seeing example data in the designer would then be my next problem ;)

I'm a beginner too, so my information can be wrong (for this i asked help here)

Generate report from BusinnessObject:
```
Report report = new Report();
report.Dictionary.RegisterBusinessObject(myList, "MyData", 5, true); //Create the data structure
report.RegisterData(myList, "MyData"); // Register and enable data

//Saving Report using memory stream
System.IO.MemoryStream reportMS = new System.IO.MemoryStream();
report.Save(reportMS);

// Read the memory stream and write to file .FRX
reportMS.Position = 0;
System.IO.StreamReader sr = new System.IO.StreamReader(reportMS);
string reportFRXString = sr.ReadToEnd();
// Save the frx
System.IO.File.WriteAllText("myReport.frx", reportFRXString);
```

- DESIGN WITH WinForm designer (drag and drop some datafields in report, because without data in the report return blank/null at runtime)

- Launch the report with data at runtime:
```
Report report = new Report();
report.Load("myReport.frx"); // Load the report
report.RegisterData(myList, "MyData"); // Pass real data
report.Prepare();
// export ...
```
The only problem is to have the poco data or dummy data in winforms designer preview. For this we tried the json approach, but the BusinnessObject approach is the best  ... (but without data in preview)

**Comment by cyberdarius** [comment]
Here https://github.com/FastReports/FastReport/issues/131

suggest to call 

`report.Design();
`
But the method doesn't exist.

**Comment by fediachov** [comment]
The method report.Desing() available in FastReport .NET or FastReport Core for .NET Core 3.1
https://opensource.fast-report.com/p/the-feature-comparison-table-for.html
