### ISSUE TITLE
Export to HTML Page Breaks not working

### ISSUE THREAD

**Issue by huang-tianwen** [FastReports/FastReport#174]
Try to design a multipage report. Export the result to html.
I am expecting we can open the html file from browser and print it. But instead, the page break is not working and Page header get shifted on every page.

**Comment by jeftegoesdev** [comment]
This problem happens more when using band Footer and TextObject property TextRenderType = HtmlTags, it is as if the css was mounted in the wrong way and the class that would be to break to the other page, has no effect.

I found that you have 2 options
1ª Don't use TextRenderType 
2ª Export to Pdf/Image

**Comment by jimbrew** [comment]
Same thing happens with me when trying to print from browser as PDF and I am not using TextRenderType = Default on my footer.

**Comment by jimbrew** [comment]
This still appears to be a bug

**Comment by ksakz** [comment]
Hi.
This was helpful for me:
```
HTMLExport html = new HTMLExport();
html.EnableMargins = true;
```

**Comment by leoperetti** [comment]
The way i found is work on html response. In each aparition of tag <a name="PageN"> add before the next tag <div style="break-after:page"></div>
