### ISSUE TITLE
Localization Files

### ISSUE THREAD

**Issue by EasyLOB** [FastReports/FastReport#179]
Hi,

I am trying to use localization files with the following command:

**webReport.LocalizationFile = Path.Combine(directory, "Portuguese (Brazil).frl");**

The file comes from FastReport.NET DEMO.
I did not find any translation file in GitHub repository.

But it does not work and shows the toolbar in English.
Is this the correct file and the correct way of loading ?

Thanks

**Comment by fediachov** [comment]
WebReport Core does not support localization at the moment. We will add it in near feature.

**Comment by fediachov** [comment]
Hi,

You can use the localization files form FastReport .NET https://github.com/FastReports/FastReport.NET/tree/main/Localization

**Comment by EasyLOB** [comment]
Hi,
I got the "Portuguese (Brazil).frl" from the repository above and loaded with FastReport:

webReport.LocalizationFile = Path.Combine(directory, "Portuguese (Brazil).frl");

But as you can see in the image below just the "Save" tooltip is translated: everythng else is still in English !
I read the Fast Report Community source code, found a "Refresh" resource in WebReport and created it: but it is not shown either.
I also included an "123" string to be sure the "frl" is really loaded: it is loaded.  
Is there something else I have to do ?

![FR](https://user-images.githubusercontent.com/18384835/95634435-48d52b00-0a60-11eb-95c9-01ea44ac44d8.PNG)
