### ISSUE TITLE
What is the difference between use FastReport.OpenSource and FastReport.OpenSource.Web?

### ISSUE THREAD

**Issue by Braytiner** [FastReports/FastReport#182]
I have two doubts: 

What is the difference between FastReport.OpenSource and FastReport.OpenSource.Web?

and 

When I use one and another one?

Thanks for help.

**Comment by ProyekRiad** [comment]
I think, if you want use web control like web preview, you should use FastReport.OpenSource.Web. 
FastReport.OpenSource is enough for generating report only.

**Comment by KirillKornienko** [comment]
Yes, @ProyekRiad is right. In FastReport.OpenSource include report-engine, preview-engine and export-engine. In FastReport.OpenSource.Web include asp.net component with resources for web-preview.
