### ISSUE TITLE
Can't find object MSChartObject

### ISSUE THREAD

**Issue by psutradhar** [FastReports/FastReport#184]
In my Report i have some chats. When I try to load the the report from .net core 3.1 project it throws the error "'Can't find object MSChartObject'"

How to resolve this?

I have the list of nuget packages installed:
1. FastReport.Compat 2020.2.2
2.FastReport.Core 2020.2.0-demo
3. FastReport.DataVisualization 2020.2.2
4. FastReport.OpenSource 2020.2.0
5. FastReport.OpenSource.Export.PdfSimle 2020.2.0
6. FastReport.OpenSource.Data.MsSql 2020.2.0
7. FastReport.OpenSource.Web 2020.2.9

What else I am missing ?

Any help will be appreciated.

**Comment by KirillKornienko** [comment]
Hello! MSChartObject is currently not available for OpenSource version. https://github.com/FastReports/FastReport.Documentation/blob/master/COMPARISON.md

**Comment by AhmadSawalhah** [comment]
**Are there any intentions to add them in future**?? it is most important feature, Please complete you favorite and add it 💯

**Comment by fediachov** [comment]
Same request here https://github.com/FastReports/FastReport/issues/95
