### ISSUE TITLE
how can i change base path url  

### ISSUE THREAD

**Issue by sirawpol** [FastReports/FastReport#185]
when program render preview report or click print button the system auto generate url this
href=\"/_fr/preview.printReport?reportId=d7fe198fe91243889233f596feb4e8dd&printMode=html
src="https://localhost/_fr/resources.getResource?resourceName=print.svg

how can i setting base path report before _fr example : https://localhost/report/_fr/

**Comment by Gavinluo** [comment]
have any update?

**Comment by KirillKornienko** [comment]
Hi, try running app.UseFastReport (setup => setup.RouteBasePath = "/ report / _fr") ;.
