### ISSUE TITLE
Deploying to subfolder - RouteBasePath

### ISSUE THREAD

**Issue by josea** [FastReports/FastReport#186]
ASP.NET core 3.1, FastReports.OpenSource.Web. 2020.2.9.

Our site is being deployed to an Application under the Default Web Site in IIS (in other words: it is in a subfolder), eg: http://localhost/{NameOfWebApp}/. 

While the project works perfectly on development, when deployed the resources do not load (similar to issue https://github.com/FastReports/FastReport/issues/145).

Tracing the problem to the code, the Urls generated by FastReports point to the root (http://localhost), which is wrong, it is missing the subfolder. 

We tried to work around it by modifying the `app.UseFastReports()` in Startup.cs to: 
`app.UseFastReport(options => options.RouteBasePath = "/{NameOfWebApp}/_fr");`

However, that didn't really work (the Url is correct, but the controller is not responding to requests anyways). 

Thanks.

Error when trying to run a report, the baseRootFolder is missing:

Detailed Error Information:
Module	   IIS Web Core
Notification	   MapRequestHandler
Handler	   StaticFile
Error Code	   0x80070002
Requested URL	   http://localhost:80/_fr/preview.getReport?reportId=1da39f7ae89243e284d25722eef6bcbf&renderBody=yes
Physical Path	   C:\inetpub\wwwroot\_fr\preview.getReport
Logon Method	   Anonymous
Logon User	   Anonymous

**Comment by jc0814** [comment]
any progress?   I'm having the same proplem...

**Comment by KirillKornienko** [comment]
Hi @josea  @jc0814 , this bug has been fixed recently! Try the latest version. Important: you must call app.UseFastReport() before UseEndpoints / UseMVC for this fix to work correctly.

**Comment by LuisVelica** [comment]
I have the same problem if it is solved for you?

**Comment by PrismhrSean** [comment]
I am having this issue using Blazor it looks like this has not been fixed yet does anyone have this working in blazor

**Comment by AhmedEssa1** [comment]
I am having this issue in razor page any fix
