### ISSUE TITLE
centos PdfExport Incomplete display of Chinese characters

### ISSUE THREAD

**Issue by yung-chu** [FastReports/FastReport#187]
window display ok, but on centos PdfExport  display Incomplete 

![error](https://user-images.githubusercontent.com/13956042/81243868-924dc400-9043-11ea-8742-766f85c99a50.jpg)
![ok](https://user-images.githubusercontent.com/13956042/81243879-9843a500-9043-11ea-913e-443e5467aa36.jpg)

https://publicvisitdata.oss-cn-shenzhen.aliyuncs.com/2019-11-5/ok.jpg
https://publicvisitdata.oss-cn-shenzhen.aliyuncs.com/2019-11-5/error.jpg

Provide the following information：

1.Rule out the possibility of fonts, because i move  C:\Windows\Fonts all Fonts  to centos 
2.Chinese characters include  '\n' 
3.I use the latest version 2020 nuget  FastReport.OpenSource and FastReport.OpenSource.Export.PdfSimple

**Comment by fediachov** [comment]
Seems same problem here https://github.com/FastReports/FastReport/issues/168
Perhaps the problem is in additional system packages:
`# yum groupinstall "Chinese Support"
`
It is also possible that the information on this link will help you https://forums.centos.org/viewtopic.php?t=2987

**Comment by cnkker** [comment]
at centos7 has same problem

**Comment by fediachov** [comment]
Please read the article that can solve this problem https://opensource.fast-report.com/2020/10/building-libgdiplus-library-from-source.html
