### ISSUE TITLE
Table cell borders spacing

### ISSUE THREAD

**Issue by araujofrancisco** [FastReports/FastReport#188]
ASP.NET core 3.1, FastReports.OpenSource.Web. 2020.2.9, FastReport Community Edition 2020.1.0.

We want to use Table (TableObject) to show some data in our report, it works, but when we set it to show borders on cells there is a gap between cells that seems we cannot get rid of, tried this in a new report to verify we are not including something that cause the issue and even when the report designer preview shows it right when we open the web page is not showing in the same way.

On preview table looks like this:

![table_preview](https://user-images.githubusercontent.com/3943185/81445828-a844ad00-9147-11ea-9aa3-ff00b4243d47.png)

When running web site it looks like this:

![table_site](https://user-images.githubusercontent.com/3943185/81445835-aaa70700-9147-11ea-96a6-fa8b3156b9f3.png)

**Comment by jeftegoesdev** [comment]
similar problem #148

**Comment by KirillKornienko** [comment]
Hello! I dont reproduce your problem. I use FastReport.OpenSource 2020.3.0 and i export (because in web-preview we use HTML-export) empty table 2x2 report to HTML (i tried layers and table-style export). In Microsoft Edge 44, Google Chrome 81 this report looks good. I attach *.frx and *.html. Please, send your report.


![image](https://user-images.githubusercontent.com/40214463/82540118-3b71df80-9b57-11ea-83c2-709f15c2764e.png)
[Table.zip](https://github.com/FastReports/FastReport/files/4661401/Table.zip)

**Comment by araujofrancisco** [comment]
This is the code we are using to actually show the report in the page and attached is the report file we are using to test table.

![image](https://user-images.githubusercontent.com/3943185/82561036-a368fb80-9b40-11ea-93c3-b63dd04bca71.png)
[table_test.zip](https://github.com/FastReports/FastReport/files/4662502/table_test.zip)

**Comment by KirillKornienko** [comment]
I have same result from your report. I use FastReport.OpenSource 2020.2.9 and FastReport.OpenSource 2020.3.1. 
![image](https://user-images.githubusercontent.com/40214463/82804508-164cdc00-9e8b-11ea-92e0-395799086e8f.png)
Please, try web-preview this report in FastReport.OpenSource.Web.MVC demo https://github.com/FastReports/FastReport/blob/master/Demos/OpenSource/FastReport.OpenSource.Web.MVC/Controllers/HomeController.cs

**Comment by fediachov** [comment]
There may be a problem in the CSS styles in application.

**Comment by araujofrancisco** [comment]
> There may be a problem in the CSS styles in application.

I did check for this and you were right, issue is being generated by the styles coming from bootstrap, specifically from box-sizing. 

![image](https://user-images.githubusercontent.com/3943185/83034660-7c11a300-a006-11ea-8d73-e1da93d907d2.png)
