### ISSUE TITLE
.Net Core Mac/Linux/Windows Text styling issues

### ISSUE THREAD

**Issue by JustPowell** [FastReports/FastReport#191]
Hi, We've been using FastReports Open source for our .net core applications. We use MacOs for local development and have been deploying to both Windows and Linux server environments. We are using .Net core 2.1 in each environment and using the included PdfSimple to export to an image pdf.

We are running into issues with text styling differences between the different environments. 

`<TextObject Left="450" Width="300" Height="28.35" Text="Direct inquiries to:" Font="Calibri, 9pt, style=Italic, Bold" />`

The included code displays 3 different ways in the 3 different server environments. 
MacOs: No bold, No Italic styling
Linux: No Italic styling
Windows: All styling works as intended.

Is this intended behavior or is this a bug?
Thanks

**Comment by fediachov** [comment]
Hello,
The .NET Core implementation of text drawing functions on different platforms may vary. Let's hope that Microsoft will fix everything in future versions of the .NET Core.

Also, you can try normal PDF export (text as text with embedded fonts) [in FastReport .NET ](https://www.fast-report.com/en/download/fast-report-net/)

Thanks for your message!

**Comment by JustPowell** [comment]
Hi,
Yeah. We just tried going back to the demo version of FastReport.Net and all the text styling works as intended in each environment. So it definitely seems to be just an OpenSource issue.

**Comment by fediachov** [comment]
Please read the article to solve this problem https://opensource.fast-report.com/2020/10/building-libgdiplus-library-from-source.html

**Comment by ddignani** [comment]
Hi, same situation here.
@fediachov advice actually solved the problem.
Just wanted to thank you a lot!

**Comment by noknokcody** [comment]
Had issues with .NET SDK 6 but @fediachov's fix worked perfectly. Had to change things up a little to work with my dockerfile

```
...

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends libpango1.0-dev libc6-dev libx11-dev fontconfig libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev git \
    && git clone --depth 1 --branch 6.1 https://github.com/mono/libgdiplus.git \
    && cd libgdiplus \
    && ./autogen.sh --with-pango --prefix=/usr \
    && make \
    && make install \
    && cd .. \
    && apt-get clean \
    && fc-cache -f -v

COPY --from=build /app ./

```
