### ISSUE TITLE
Support for .Net Core 3x

### ISSUE THREAD

**Issue by lucas-pollus** [FastReports/FastReport#192]
Hi I tried using it with WinForms with .Net Core 3.1 and I was not successful.
Do you have plans to make available for .Net Core 3x?

Thank you!!!

**Comment by fediachov** [comment]
Hi!

FastReport Open Source can work with WinForms as described here:
https://opensource.fast-report.com/2019/04/how-to-use-fastreport-open-source-in.html
https://opensource.fast-report.com/2019/04/how-to-use-fastreport-open-source-in_30.html

Project should work with .NET Core 3.1 because FastReport Open Source built for .NET Standard 2.1

**Comment by lucas-pollus** [comment]
Hi,
I tried again, I did a small console project using .NET core 3.1. The code is below:
[https://gist.github.com/lucas-pollus/109db5b94f731ebe3682f925c627eb4a](url)

`When running, an exception is raised:
System.TypeInitializationException: 'The type initializer for 'FastReport.Report' threw an exception.'`

Looking inside the InnerException:

`Could not load file or assembly 'FastReport.Compat, Version=2020.3.2.0, Culture=neutral, PublicKeyToken=406e1f4c3c8ef97e'. The system cannot find the file specified.`

**Comment by mjftechnology** [comment]
I have the same issue as @lucas-pollus when upgrading to FastReport.OpenSource.Web 2020.3.4. The last working version for me is v2020.3.0.

**Comment by KirillKornienko** [comment]
Hello! Did you try add package FastReport.Compat? https://www.nuget.org/packages/FastReport.Compat/

**Comment by KirillKornienko** [comment]
@lucas-pollus @mjftechnology Hello! We fixed this error in the last update (https://www.nuget.org/packages/FastReport.OpenSource/2020.3.10). Please, try this changes and share your opinion.

**Comment by lucas-pollus** [comment]
@KirillKornienko Hello! I did the tests with the new version and everything worked correctly. Thank you for this correction.
