### ISSUE TITLE
Matrix report with additional column after the total (right side)

### ISSUE THREAD

**Issue by valanjdr** [FastReports/FastReport#194]
Hi,

We are using FastReport.Opensource.web for generating reports.

I have a report with the below columns. In the below columns the columns marked as "**" are row values which needs to be converted as column values (like a matrix report).

Opening/Transactions | Transaction no. | Currency | **Cash chips | **NNeg chips | **Non-RFID chips | [-] Denomination | Chip code | Total chips |   | Total Value | Date_time | Remarks

My problem is that I have more columns after the columns which are converted from row values. I don't know how to specify them in the matrix report. Please let me know how this can be achieved. Is matrix report is the right way to do this report?

Your help is greatly appreciated.

**Comment by ATZ-FR** [comment]
Hello,
Sorry but I don't understand what you want to do. Can you explain it with pictures, maybe?

**Comment by valanjdr** [comment]
Hi,

Thanks for contacting for more information.
The report should look like the below one. The currency (Red box) and the Chips (Purple box) are the one to come as a matrix report. My question was, If I am defining this as a Matrix report, how do I define the rest of the columns in the report?

[cid:image001.png@01D64F03.24F4AF80]
Regards,

Valanarasu J.

**Comment by ATZ-FR** [comment]
It seems the picture in your message is lost. Try to repost or write to support at fast-report.com.

**Comment by valanjdr** [comment]
Hi,

I have attached the image here for your reference. If you still didn’t get the image please let me know.

Regards,

Valanarasu J, Technical Manager
valan@xuvi.com<mailto:valan@xuvi.com>

[cid:image001.png@01D650A6.E9EB3F30]

This e-mail message is a confidential communication and is intended only for the named recipient(s) above. It may contain information that is a XUVI trade secret, is proprietary or privileged. If you have received this message in error or are not the named or intended recipient(s), please immediately notify the sender and delete this e-mail message and any attachments from your workstation or network mail system.

**Comment by ATZ-FR** [comment]
Nope, just a string "[cid:image001.png@01D650A6.E9EB3F30]"

**Comment by valanjdr** [comment]
![report-requirement](https://user-images.githubusercontent.com/67587434/86380132-60ef1e80-bca9-11ea-94c1-846700fa9613.png)

Attached the file

**Comment by valanjdr** [comment]
Hi,

I’ve attached it as a PNG file now in github. It is appearing. Also I’ve attached here as the PNG again.



Valanarasu J, Technical Manager
valan@xuvi.com<mailto:valan@xuvi.com>

[cid:image001.png@01D650B6.62D27D00]

This e-mail message is a confidential communication and is intended only for the named recipient(s) above. It may contain information that is a XUVI trade secret, is proprietary or privileged. If you have received this message in error or are not the named or intended recipient(s), please immediately notify the sender and delete this e-mail message and any attachments from your workstation or network mail system.

**Comment by ATZ-FR** [comment]
I'm afraid it is not the kind of data required for matrix-type reports.
https://www.fast-report.com/public_download/html/UserManFrNET-en/matrixtheory.htm
You may try to use Table object and fill it dynamically.

**Comment by valanjdr** [comment]
Thank you very much for the support. I will try with table.

Regards,

Valanarasu J.

**Comment by valanjdr** [comment]
Thank for the support.

Valanarasu J.
