### ISSUE TITLE
Report Viewer images are broken again

### ISSUE THREAD

**Issue by mjftechnology** [FastReports/FastReport#195]
FastReport.OpenSource.Web 2020.3.0 has broken the Report Viewer images again as per Issue #151 in ASP.NET Core MVC. I am unable to use a newer version due to Issue #192 

The report is show but the loading spinner and toolbar icons are broken links.

The following is show in the browser console:

GET https://localhost:44356/_fr/resources.getResource?resourceName=spinner.svg&contentType=image%2Fsvg%2Bxml 404
GET https://localhost:44356/_fr/resources.getResource?resourceName=reload.svg&contentType=image%2Fsvg%2Bxml 404
GET https://localhost:44356/_fr/resources.getResource?resourceName=save.svg&contentType=image%2Fsvg%2Bxml 404
GET https://localhost:44356/_fr/resources.getResource?resourceName=print.svg&contentType=image%2Fsvg%2Bxml 404
GET https://localhost:44356/_fr/resources.getResource?resourceName=magnifier.svg&contentType=image%2Fsvg%2Bxml 404
GET https://localhost:44356/_fr/resources.getResource?resourceName=angle-double-left.svg&contentType=image%2Fsvg%2Bxml 404
GET https://localhost:44356/_fr/resources.getResource?resourceName=angle-left.svg&contentType=image%2Fsvg%2Bxml 404
GET https://localhost:44356/_fr/resources.getResource?resourceName=slash.svg&contentType=image%2Fsvg%2Bxml 404
GET https://localhost:44356/_fr/resources.getResource?resourceName=angle-right.svg&contentType=image%2Fsvg%2Bxml 404
GET https://localhost:44356/_fr/resources.getResource?resourceName=angle-double-right.svg&contentType=image%2Fsvg%2Bxml 404

**Comment by KirillKornienko** [comment]
@mjftechnology Hello, we fixed Issue #192. Do you still have problems with this?
