### ISSUE TITLE
Plans for Blazor?

### ISSUE THREAD

**Issue by newbiE247** [FastReports/FastReport#197]
Hi, do you have plans to make FastReport useable as a Blazor Component?

**Comment by 8VAid8** [comment]
Hi, @newbiE247!
Yes, we have such plans. Please, stand by.

**Comment by newbiE247** [comment]
Thanks for the quick response. Can you estimate the the release date or at least a preview?

**Comment by 8VAid8** [comment]
The task is in a backlog yet. Raw estimate - in 4 months.

**Comment by 8VAid8** [comment]
Hi, @newbiE247! We've implemented Blazor components in the [FastReport.Net](https://www.fast-report.com/en/product/fast-report-net/).

**Comment by behroozbc** [comment]
Hi @8VAid8 , Is FastReport opensource support blazor?

**Comment by 8VAid8** [comment]
@behroozbc No. But you can find it there - https://www.fast-report.com/en/product/fast-report-net/
