### ISSUE TITLE
 Problem with Data From Business Object

### ISSUE THREAD

**Issue by lucasjrnany** [FastReports/FastReport#200]
Hello ,

I'm having trouble adding data, follow the object's link, before I register.
https://prnt.sc/tma872

After I register I check the DataSources the columns are null
https://prnt.sc/tmaaam

One thing you notice is that the reference property is bringing the data
https://prnt.sc/tmabhr

follows the reporter file, the property remains null, if I try to enable it I get an exception
https://prnt.sc/tmacrs

Thanks good night.

**Comment by ATZ-FR** [comment]
Hello,

Could you make a simple test project that demonstrates the problem?

**Comment by lucasjrnany** [comment]
Hello, I created a simple example based on my routines.

Thank you

[TestBusinessObject.zip](https://github.com/FastReports/FastReport/files/4960090/TestBusinessObject.zip)

**Comment by ATZ-FR** [comment]
Hello,

Thank you for the test project. You should register data in the following way to enable nested data sources:

_report.RegisterData(_objectBusiness, "Order", 3); // where 3 is the max nesting level
