### ISSUE TITLE
Unable to run a report with more than 3 tables

### ISSUE THREAD

**Issue by affanyiek** [FastReports/FastReport#201]
I created a report with 4 tables (TableDataSource) which worked perfectly when previewed in the Designer. However when I embedded it into my web application and try to preview same, there was an unhandled server error (500) that shows on the WebReport preview control that the 4th table is not recognized. Basically, anywhere the 4th table was used in the report (even in expressions), it was not recognized with snipet of a long error message below:
**FastReport.Utils.CompilerException: (GroupHeader2): Error CS1525: Invalid expression term '[' (Column): Error CS1026: ) expected (Column): Error CS1002: ; expected (Column): Error CS1513: } expected (Column): Error CS1002: ; expected (Column): Error CS1513: } expected (Column): Error CS1002: ; expected (Column): Error CS1513: } expected (TaxDescription): Error CS1525: Invalid expression term......**

Meanwhile after experimenting to recompose the report with up to 3 tables, it worked perfectly.
Is it the case that the **FastReport.OpenSource**  library is restricted to work with not more than 3 tables

**Comment by KirillKornienko** [comment]
Hello, @affanyiek ! Please send us a report with this problem.

**Comment by affanyiek** [comment]
> Hello, @affanyiek ! Please send us a report with this problem.


[4 table FastReport_CAN preview on Designer.zip](https://github.com/FastReports/FastReport/files/4974919/4.table.FastReport_CAN.preview.on.Designer.zip)

Hi @KirillKornienko , thanks for the swift response. Attached are sample FRX files (contained in the zip file) for your perusal. I hope this is what you are looking for.

**Comment by codepend** [comment]
> > Hello, @affanyiek ! Please send us a report with this problem.
> 
> [4 table FastReport_CAN preview on Designer.zip](https://github.com/FastReports/FastReport/files/4974919/4.table.FastReport_CAN.preview.on.Designer.zip)
> 
> Hi @KirillKornienko , thanks for the swift response. Attached are sample FRX files (contained in the zip file) for your perusal. I hope this is what you are looking for.
> 
> The 4th table that could not be recognized on FastReport.OpenSource is the RptTaxes table.

Hi @affanyiek , Not sure if this is related but I looked at the Data Sources on each report and the one labeled CANNOT run does not have a Connection listed under the data source (compared to the other one).

**Comment by Alekarfes** [comment]
The report looks fine and FastReport Open Source has no restrictions on table amount. If you're still having this problem then please create a sample with data that we can reproduce what's going wrong, and create a new issue.
