### ISSUE TITLE
Null values show [data.xxx] on recent version, 2020.3.1 is working good but 2020.3.17 doesn't

### ISSUE THREAD

**Issue by seddik** [FastReports/FastReport#205]
Null values are replaced but the full binding expression and not empty values.

![image](https://user-images.githubusercontent.com/6674347/90668118-76afa780-e247-11ea-845f-f89f4fed9f4a.png)

-------------------

![image](https://user-images.githubusercontent.com/6674347/90667978-40722800-e247-11ea-9692-f484a5ddacaf.png)

**Comment by BogdanStegachev** [comment]
Hello!

On the current version of FastReport.Community your problem is not relevant

Best regards,
Bogdan

**Comment by seddik** [comment]
> Hello!
> 
> On the current version of FastReport.Community your problem is not relevant
> 
> Best regards, Bogdan

this is because the thread is 2 years and half old !, an yes I am not facing the issue anymore. thank you !
