### ISSUE TITLE
PrintOn LastPage not working with PageFooter Band

### ISSUE THREAD

**Issue by matheusjaar** [FastReports/FastReport#208]
Hey Guys,

I have a PageFooter Band that must be printed on the lastPage of the report (if the reports render with only one page, the page footer must be there). When I select the LastPage option on the PrintOn property, the PageFooter Band is never printed.

The printable expression is not working as well, even with a numb expression like 1 == 2.

Am I doing something wrong?

Fast Reports Version 2020.03.22
Installed from Nuget package Manager

**Comment by 0legK** [comment]
Hi,

Please, make sure that double pass is turned on in report options. It's needed for correct work of PritnOn.LastPage.

Best Regards,
Oleg.

**Comment by widardd** [comment]
Issue still exists, double pass is enabled
