### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by myn724405566** [FastReports/FastReport#209]
I did not find the "Show" method and the "ShowPrepared" method in the Report class. Can you tell me where I am mistaken, my dear friend?

**Comment by fediachov** [comment]
Hello,
Unfortunately, FastReport Open Source does not contain these methods for working with WinForms directly.

You can use the commercial version from https://www.fast-report.com/en/product/fast-report-net/

Or use the methods from these articles 
https://opensource.fast-report.com/2019/04/how-to-use-fastreport-open-source-in.html
https://opensource.fast-report.com/2019/04/how-to-use-fastreport-open-source-in_30.html
