### ISSUE TITLE
Please add Excel Export functionality in FastReport OpenSource.

### ISSUE THREAD

**Issue by VaskarBanerjee** [FastReports/FastReport#211]
Please add Excel Export Functionality in FastReport.OpenSource.Web

This functionality is very very very important.

**Comment by VaskarBanerjee** [comment]
Please add Excel Export Functionality in FastReport.OpenSource.Web

**Comment by VaskarBanerjee** [comment]
Please add Excel Export Functionality in FastReport.OpenSource.Web

This functionality is very very very important.

**Comment by VaskarBanerjee** [comment]
Please add Excel Export Functionality in FastReport.OpenSource.Web

**Comment by mguinness** [comment]
If you look at [The Feature Comparison Table](https://opensource.fast-report.com/p/the-feature-comparison-table-for.html) you'll see that it's not available for FastReport Open Source.  If it's "very very very important" then you'll have to get FastReport Core or FastReport .NET - they have to make money somehow which also helps support the open source version.
