### ISSUE TITLE
FastReport build error with ReadyToRun

### ISSUE THREAD

**Issue by soltrac** [FastReports/FastReport#212]
FastReport OpenSource will fail to buil any project with ReadyToRun in .NET Core because is using Microsoft.CodeAnalysis.VisualBasic 2.0.0 and MicrosoftCodeAnalysis.CSharp 2.0.0

It is a known bug on Microsoft that Microsoft.CodeAnalysis.* < 3.1.0 won't work for ReadyToRun (read here: https://github.com/dotnet/sdk/issues/4041), so it would be great to update the nuget packages to update those both packages.

**Comment by KirillKornienko** [comment]
Hello @soltrac ! Thanks for the warning, we already have plans to update the Microsoft.CodeAnalysis dependency. Do you recommend upgrading to at least version 3.1.0?

**Comment by soltrac** [comment]
At least 3.1.0 to avoid this problem. Current version is 3.7.0 and which is I'm using right now (I'm not having problems with it currently)

**Comment by KirillKornienko** [comment]
Hello, we updated Microsoft.CodeAnalysis to 3.2.0 version. Try to update FastReport.OpenSource package 2021.1.0.
