### ISSUE TITLE
FastReport.OpenSource.Web Toolbar Customization

### ISSUE THREAD

**Issue by VaskarBanerjee** [FastReports/FastReport#213]
There is no option for Toolbar customization. Visible-Invisible toolbar items or add new item to toolbar.

**Comment by VaskarBanerjee** [comment]
There is no option for Toolbar customization. Visible-Invisible toolbar items or add new item to toolbar.

**Comment by VaskarBanerjee** [comment]
There is no option for Toolbar customization. Visible-Invisible toolbar items or add new item to toolbar. Please add toolbar customization.

**Comment by fediachov** [comment]
Hi!

Thanks for request! We will do it.

**Comment by VaskarBanerjee** [comment]
Great. Thanks.

**Comment by VaskarBanerjee** [comment]
Thank you very much sir. Can you please provide some source code how can we implement it on Dot Net Core Web Application.

Regards,

**Comment by VaskarBanerjee** [comment]
Sir, Can I have some sample code on toolbar customization, that I can implement in my Dotnet Core Web Application. 

Regards,

**Comment by fediachov** [comment]
I am sorry, but at the moment this feature is being tested and will be included in the FastReport sources soon. Keep an eye on repository updates.

**Comment by VaskarBanerjee** [comment]
Sir any update on toolbar customization enhancement.  

Thanks in advance.

**Comment by VaskarBanerjee** [comment]
Sir, Waiting for your reply.

**Comment by VaskarBanerjee** [comment]
Sir, Waiting for your reply.

**Comment by Skilletron** [comment]
Hi, this is simple example code for use toolbar customization enhancement                                                            
ToolbarSettings toolbar = new ToolbarSettings()
            {
                Color = Color.Red,
                DropDownMenuColor = Color.Red,
                DropDownMenuTextColor = Color.White,
                IconColor = IconColors.White,
                Position = Positions.Right,
                FontSettings = new Font("Arial", 14, FontStyle.Bold),
                Exports = new ExportMenuSettings()
                {
                    ExportTypes = Exports.Pdf | Exports.Excel97 | Exports.Rtf
                }
            };
            model.WebReport.Toolbar = toolbar;                                                                                                                                                or another way to customization toolbar :  WebReport.Toolbar = new ToolbarSettings(){Position = Positions.Left, e.t.c options}

**Comment by Skilletron** [comment]
At the moment it is impossible  Visible-Invisible toolbar items or add new item to toolbar. But, we are already working on this and such an opportunity will be added soon.

**Comment by Alekarfes** [comment]
The toolbar had a lot of improvements since 2021, including the requested changes, so I'm closing the issue.
