### ISSUE TITLE
FastReport in Linux environment, if the text is longer, it will wrap

### ISSUE THREAD

**Issue by seanrenxiaofeng** [FastReports/FastReport#214]
FastReport in Linux environment, dot or space, if the text is longer, it will wrap. How to solve this problem?

**Comment by fediachov** [comment]
Hi!

Do you have any screenshots of the problem? Thanks in advance!

**Comment by seanrenxiaofeng** [comment]
![(J3RG(W_OJ)1WHRZO2B8(SR](https://user-images.githubusercontent.com/43309069/94256354-45b84600-ff5c-11ea-91b0-4ea96c659178.png)
![K8OMMBXLT@TOKKP1TNO0)(A](https://user-images.githubusercontent.com/43309069/94256357-46e97300-ff5c-11ea-9e94-ee969e0684df.png)

Thank you very much.

**Comment by fediachov** [comment]
Thanks for screenshots! 
I think the problem is with the libgdiplus library.
Please read the article to solve this problem https://opensource.fast-report.com/2020/10/building-libgdiplus-library-from-source.html
