### ISSUE TITLE
Report viewer toolbar

### ISSUE THREAD

**Issue by fredericoregateiro** [FastReports/FastReport#217]
Is it possible to remove some icons from the, community edition, viewer toobar? Like the "edit page" or the "save" button?
And a print icon, can that be added?

**Comment by fediachov** [comment]
Hi,

We did not provide such functionality for this program. You can always use the [FastReport .NET](https://www.fast-report.com/en/product/fast-report-net/) where all these features are available and you can make your own viewer.

Also you can read an article https://opensource.fast-report.com/2019/04/how-to-use-fastreport-open-source-in.html
And second part https://opensource.fast-report.com/2019/04/how-to-use-fastreport-open-source-in_30.html

It is an example how to make your own viewer in WinForms application with FastReport Open Source.
