### ISSUE TITLE
PDF export report with tabs

### ISSUE THREAD

**Issue by jimbrew** [FastReports/FastReport#218]
I have been following this [link ](https://opensource.fast-report.com/2019/06/pdf-export-in-fastreportopensource.html) in order to export my fast reports (FastReports.OpenSource.Web) to PDF in an MVC application. The report has a few tabs with hyperlinks that sets parameters and then produces a final report. However, it exports the first tab but I want to export the last one how do I to sepcify what tab to export?

**Comment by fediachov** [comment]
Hi,

Perhaps these are limitations of PDFSimpleExport. You can make changes to the code or use [FastReport .NET ](https://fast-report.com/en/product/fast-report-net/)with full-featured export.

**Comment by jimbrew** [comment]
Yes that is possibly the case from the code it seems to just export the initially loaded report.
