### ISSUE TITLE
FastReport.Utils.ClassException : Can't find object Datasets

### ISSUE THREAD

**Issue by kevinvenclovas** [FastReports/FastReport#219]
Hello,

when i call the function Load with my fr4 Report then i get every time this error -> FastReport.Utils.ClassException : Can't find object Datasets . How can i fix this ? 

```
Report report = new Report();
report.Load(@"C:\Invoice.fr4");
report.Report.Dictionary.Connections[0].ConnectionString = Settings.CONNECTION_STRING
```

**Comment by fediachov** [comment]
Hello,

You can load only files with *.frx extension.
