### ISSUE TITLE
Printing from browser pages move up

### ISSUE THREAD

**Issue by jimbrew** [FastReports/FastReport#220]
When using fast report opensource web reports on mvc and printing from browser the pages keep getting moved up so some content spans over multiple pages.

The more pages the report has the further up each page moves see the images below. The grey lines are the page breaks

1.
![image](https://user-images.githubusercontent.com/35928790/95436422-b93e5800-094b-11eb-83af-7f37a9acb320.png)
2.
![image](https://user-images.githubusercontent.com/35928790/95436486-c78c7400-094b-11eb-9761-b46ce75aa022.png)
3.
![image](https://user-images.githubusercontent.com/35928790/95437109-82b50d00-094c-11eb-91d3-67f6e8499982.png)

Is there a fix for this because it would be very handy to able to print to pdf and send these reports via email?

**Comment by araujofrancisco** [comment]
Is there any information or workaround on this issue?
