### ISSUE TITLE
FastReport.OpenSource.Web.MVC memory footprint continuously increasing 

### ISSUE THREAD

**Issue by pspyrou** [FastReports/FastReport#221]
We try to evaluate FastReport.OpenSource, so we downloaded the code and ran FastReport.OpenSource.Web.MVC within Visual Studio 2019 (using Ctrl+F5).

Simply cycling through the sample reports makes the memory allocated to the ".NET Core Host' process to increase constantly. It consumed well over 1GB of memory in just a few iterations between all the reports.

This problem does not occur if we repeat the same usage pattern using the FastReport.OpenSource.MVC project.

**Comment by fediachov** [comment]
Hi! We have some fixes in code. We plan to release the changes in early December in version 2021.1.

**Comment by la-lit** [comment]
I have the same issue, I am using version 2021.1.7 and the memory consumption increases on each load of report render in Ubuntu

**Comment by MaratAlaev** [comment]
Hello!

I reproduced this problem 
and informed the developers 

Best regards 
Marat
