### ISSUE TITLE
PdfSimple export as a readable

### ISSUE THREAD

**Issue by WaldoPas** [FastReports/FastReport#222]
Hi,
Are there any plans for PdfSimpleExport to support readable output as for now the outputted file is just an image?

**Comment by jeftegoesdev** [comment]
According to the fastreport technical team, in previous issues, this functionality is only available in the paid version.

**Comment by fediachov** [comment]
Hi! You can try FastReport .NET https://fast-report.com/en/product/fast-report-net/ 
It is also available on nuget https://www.nuget.org/packages/FastReport.Core/2020.4.11-demo
