### ISSUE TITLE
Demo PdfExport has no text characters in ubuntu

### ISSUE THREAD

**Issue by kattunga** [FastReports/FastReport#223]
Hi,
I'm testing PdfExport demo in ubuntu with dotnet core, pdf is generated, images and style is correct but text has no visible characters.

![image](https://user-images.githubusercontent.com/2139720/96498107-065edb80-1222-11eb-9965-ac1a48adc8ac.png)

I tested it in ubuntu 16.04 and 20.04 with latest libgdiplus.

Do I need to install any other package?

**Comment by Huangqi95** [comment]
You need to install fonts

**Comment by kattunga** [comment]
I'm sorry.
I didn't realize that because I already have installed the packages "tts-mscorefonts" and "fonts-liberation", but for some reason, in my case, fast-report does not match font names, If I manually set fonts to "Ubuntu" it works.

Thank you

**Comment by zhanghaiboshiwo** [comment]
How do you operate
