### ISSUE TITLE
The TextObject property CanGrow is rendered differently on Windows and Linux

### ISSUE THREAD

**Issue by BlackPig-dev** [FastReports/FastReport#226]
Windws：
![image](https://user-images.githubusercontent.com/28700143/97262195-5b6ea300-185b-11eb-941f-e37475d37e1e.png)
Linux：
![image](https://user-images.githubusercontent.com/28700143/97262384-abe60080-185b-11eb-8d13-bc5872072048.png)
These areas are not shown completely

Linux environment：
debian 20.04+libgbiplus+pango1.0 1.42.4-8~deb10u1

**Comment by fediachov** [comment]
Have you tried building the libgdiplus library from source? https://opensource.fast-report.com/2020/10/building-libgdiplus-library-from-source.html

**Comment by BlackPig-dev** [comment]
> Have you tried building the libgdiplus library from source? https://opensource.fast-report.com/2020/10/building-libgdiplus-library-from-source.html

Yes, it's built with the latest libgdiPlus code

**Comment by BlackPig-dev** [comment]
[https://github.com/BlackPig-dev/Test](url)
Here's my template

**Comment by NetChenQian** [comment]
I compiled libgdiplus with https://opensource.fast-report.com/2020/10/building-libgdiplus-library-from-source.html
Use same template file https://github.com/BlackPig-dev/Test but the pdf export like this:
![image](https://user-images.githubusercontent.com/29855154/99904459-e3828400-2d05-11eb-8fb9-66ac7c58a455.png)
The exported characters become number.
Enviroment：WSL Kali, libgbiplus with pango1.0
What should I do?

**Comment by BlackPig-dev** [comment]
> I compiled libgdiplus with https://opensource.fast-report.com/2020/10/building-libgdiplus-library-from-source.html
> Use same template file https://github.com/BlackPig-dev/Test but the pdf export like this:
> ![image](https://user-images.githubusercontent.com/29855154/99904459-e3828400-2d05-11eb-8fb9-66ac7c58a455.png)
> The exported characters become number.
> Enviroment：WSL Kali, libgbiplus with pango1.0
> This is also the case when using Linux docker!
> What should I do?

This is because the font is not installed.The font I use is Simsun

**Comment by BlackPig-dev** [comment]
This problem seems to be a font problem, it is normal for me to try to use Microsoft YaHei, what seems to be the problem with Pango in calculating the width of Simsun, I haven't found a solution yet

**Comment by NetChenQian** [comment]
Thank you. I'll install the Simsun font and try again.

**Comment by NetChenQian** [comment]
> This problem seems to be a font problem, it is normal for me to try to use Microsoft YaHei, what seems to be the problem with Pango in calculating the width of Simsun, I haven't found a solution yet

Yes. After install font, The characters can be displayed.
But I found the same problem as you, the layout is wrong.

**Comment by BlackPig-dev** [comment]
Graphics.measurestring gets inconsistent values leading to this problem.This seems to have something to do with fonts or GDI +.It's not a fastReport problem
