### ISSUE TITLE
Localization files 

### ISSUE THREAD

**Issue by EasyLOB** [FastReports/FastReport#229]
Hi,
This is an another question realated to the Issue [179](https://github.com/FastReports/FastReport/issues/179).
I posted the comment below after is was already closed.

I got the "Portuguese (Brazil).frl" from the FastReport.NET repository and loaded with FastReport:

webReport.LocalizationFile = Path.Combine(directory, "Portuguese (Brazil).frl");

But as you can see in the image below just the "Save" tooltip is translated: everythng else is still in English !
I read the Fast Report Community source code, found a "Refresh" resource in WebReport and created it: but it is not shown either.
I also included an "123" string to be sure the "frl" is really loaded: it is loaded.
Is there something else I have to do ?

![95634435-48d52b00-0a60-11eb-95c9-01ea44ac44d8](https://user-images.githubusercontent.com/18384835/99063805-d89c5680-2583-11eb-8e33-9398605ef24b.png)

**Comment by EasyLOB** [comment]
Hi,
Any ideia about the problem above ?
Thanks

**Comment by KirillKornienko** [comment]
Hello @EasyLOB ! Sorry for the late reply. You need to add the "Web" directory item to the 'Portuguese (Brazil).frl' file. Please, see 'Russian.frl' file as example.  
![image](https://user-images.githubusercontent.com/40214463/107486894-9ee4e700-6b96-11eb-8d10-1113471adae7.png)

We will add a "Localization" folder in the near future. Please, if you add translation for "Web", make a merge request.
