### ISSUE TITLE
Make a table grow to the bottom of a page

### ISSUE THREAD

**Issue by MerlinDuChaos** [FastReports/FastReport#230]
Hi !

Is there a way to make a table grow to the bottom of a page ?

Like this:

![2020-11-18 15_20_16-Boîte de réception - jbarbier@thelis be - Outlook](https://user-images.githubusercontent.com/10143747/99542008-d38b3d00-29b1-11eb-93fb-c397784d061f.png)

I tried setting "Can grow" to true on the band, and "GrowtoBottom" on the table.
I also tried adding a blank line with autosize set to true, but it didn't work.

Is it possible ?

Thanks

**Comment by Alekarfes** [comment]
GrowtoBottom refers to the bottom of the _band_, not of the page.
https://www.fast-report.com/public_download/docs/FRNet/online/en/UserManual/en-US/DataBand/DynamicLayout/DynamicLayout_GrowToBottom.html

Looks like you want a table of a fixed size, I can recommend resizing the databand so it fits the height requirement.
