### ISSUE TITLE
Duōyú de; hào 5/5000 Redundant; No.

### ISSUE THREAD

**Issue by Snuger** [FastReports/FastReport#232]
![image](https://user-images.githubusercontent.com/33015003/99786248-3539db80-2b59-11eb-82ca-97cf5d7db466.png)

**Comment by VitaliyRud2001** [comment]
Hi!
Can you provide problem project or at least frx file of this report? 
In case of using any data sources in report please save data in report (StoreData = true) if possible.
Best regards, Vitalii.

**Comment by Snuger** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<Report ScriptLanguage="CSharp" TextQuality="Regular" ReportInfo.Description="This example demonstrates how to print a datasource using the TableObject. To do this:&#13;&#10;- select the Table object;&#13;&#10;- go to the &quot;Properties&quot; window and click the &quot;Events&quot; button to view a list of available events;&#13;&#10;- doubleclick the &quot;ManualBuild&quot; event;&#13;&#10;- you will see an empty event handler. You need to print rows using TableObject.PrintRow method; in each row, you must also print all columns (using PrintColumn method). See the script's code for more details." ReportInfo.Created="08/01/2008 14:01:38" ReportInfo.Modified="11/20/2020 17:37:15" ReportInfo.CreatorVersion="2019.4.4.0">
  <ScriptText>using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Windows.Forms;
using System.Drawing;
using System.Data;
using FastReport;
using FastReport.Data;
using FastReport.Dialog;
using FastReport.Barcode;
using FastReport.Table;
using FastReport.Utils;

namespace FastReport
{
  public class ReportScript
  {       

    
  }
}
</ScriptText>
  <Dictionary>
    <TableDataSource Name="gongzuoliangzb" ReferenceName="Reports.gongzuoliangzb" DataType="System.String" Enabled="true">
      <Column Name="name" DataType="System.String"/>
      <Column Name="type" DataType="System.String"/>
      <Column Name="busType" DataType="System.String"/>
      <Column Name="Outbound" DataType="System.Decimal"/>
      <Column Name="CallBack" DataType="System.Decimal"/>
      <Column Name="Column" Alias="DifferenceRate" DataType="System.Int32" Calculated="true" Expression=""/>
    </TableDataSource>
    <TableDataSource Name="renYuanXX" ReferenceName="Reports.renYuanXX" DataType="System.String" Enabled="true">
      <Column Name="name" DataType="System.String"/>
      <Column Name="orgName" DataType="System.String"/>
      <Column Name="orgGroup" DataType="System.String"/>
    </TableDataSource>
    <Relation Name="renYuanXX_gongzuoliangzb" ParentDataSource="renYuanXX" ChildDataSource="gongzuoliangzb" ParentColumns="name" ChildColumns="name" Enabled="true"/>
    <Parameter Name="TimeRange" DataType="System.String"/>
  </Dictionary>
  <ReportPage Name="Page1" Landscape="true" PaperWidth="297" PaperHeight="210" RawPaperSize="9" Watermark.Font="宋体, 60pt">
    <ReportTitleBand Name="ReportTitle1" Width="1047.06" Height="53.15" FirstRowStartsNewPage="true">
      <TextObject Name="Text1" Left="462.11" Top="9.45" Width="122.85" Height="28.35" Text="ReportName" HorzAlign="Center" VertAlign="Center" Font="宋体, 16pt, style=Bold"/>
    </ReportTitleBand>
    <DataBand Name="Data1" Top="57.41" Width="1047.06" Height="204.35" CanGrow="true">
      <MatrixObject Name="Matrix2" Left="37.1" Width="567.71" Height="176" Fill.Color="ControlText" FixedRows="3" FixedColumns="2" AutoSize="false" CellsSideBySide="true" DataSource="gongzuoliangzb" Style="Gray">
        <MatrixColumns>
          <Header Expression="[gongzuoliangzb.busType]"/>
          <Header Expression="[gongzuoliangzb.type]"/>
        </MatrixColumns>
        <MatrixRows>
          <Header Expression="[gongzuoliangzb.renYuanXX.orgName]"/>
          <Header Expression="[gongzuoliangzb.name]"/>
        </MatrixRows>
        <MatrixCells>
          <Cell Expression="[gongzuoliangzb.Outbound]"/>
          <Cell Expression="[gongzuoliangzb.CallBack]"/>
          <Cell Expression="[gongzuoliangzb.Outbound]/[gongzuoliangzb.CallBack]"/>
        </MatrixCells>
        <TableColumn Name="Column8"/>
        <TableColumn Name="Column9" Width="55.52"/>
        <TableColumn Name="Column10" Width="41.58"/>
        <TableColumn Name="Column11" Width="41.58"/>
        <TableColumn Name="Column12" Width="0"/>
        <TableColumn Name="Column13" Width="60.48"/>
        <TableColumn Name="Column14" Width="60.48"/>
        <TableColumn Name="Column15" Width="60.48"/>
        <TableColumn Name="Column16" Width="60.48"/>
        <TableColumn Name="Column17" Width="60.48"/>
        <TableColumn Name="Column18" Width="60.48"/>
        <TableRow Name="Row6" Height="27.64">
          <TableCell Name="Cell44" Border.Lines="All" Fill.Color="Gainsboro" Text="orgName" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" RowSpan="3"/>
          <TableCell Name="Cell45" Border.Lines="All" Fill.Color="Gainsboro" Text="name" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" RowSpan="3"/>
          <TableCell Name="Cell50" Border.Lines="All" Fill.Color="Gainsboro" Text="[busType]" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" ColSpan="6"/>
          <TableCell Name="Cell53" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell54" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell64" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell65" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell79" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell80" Border.Lines="All" Fill.Color="Gainsboro" Text="total" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" ColSpan="3" RowSpan="2"/>
          <TableCell Name="Cell81" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell94" Font="宋体, 9pt, style=Bold"/>
        </TableRow>
        <TableRow Name="Row7" Height="27.64">
          <TableCell Name="Cell46" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell47" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell51" Border.Lines="All" Fill.Color="Gainsboro" Text="[type]" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" ColSpan="3"/>
          <TableCell Name="Cell55" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell56" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell66" Border.Lines="All" Fill.Color="Gainsboro" Text="total" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" ColSpan="3"/>
          <TableCell Name="Cell67" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell82" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell83" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell84" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell95" Font="宋体, 9pt, style=Bold"/>
        </TableRow>
        <TableRow Name="Row8" Height="37.09">
          <TableCell Name="Cell48" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell49" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell52" Border.Lines="All" Fill.Color="Gainsboro" Text="Outbound" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell57" Border.Lines="All" Fill.Color="Gainsboro" Text="CallBack" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell58" Border.Lines="All" Fill.Color="Gainsboro" Text="DifferenceRate" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell68" Border.Lines="All" Fill.Color="Gainsboro" Text="Outbound" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell69" Border.Lines="All" Fill.Color="Gainsboro" Text="CallBack" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell85" Border.Lines="All" Fill.Color="Gainsboro" Text="DifferenceRate" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell86" Border.Lines="All" Fill.Color="Gainsboro" Text="Outbound" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell87" Border.Lines="All" Fill.Color="Gainsboro" Text="CallBack" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell96" Border.Lines="All" Fill.Color="Gainsboro" Text="DifferenceRate" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
        </TableRow>
        <TableRow Name="Row9" Height="27.64">
          <TableCell Name="Cell59" Border.Lines="All" Fill.Color="Gainsboro" Text="[orgName]" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" RowSpan="2"/>
          <TableCell Name="Cell60" Border.Lines="All" Fill.Color="Gainsboro" Text="[name]" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell61" Border.Lines="All" Fill.Color="White" Text="[Outbound]" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell62" Border.Lines="All" Fill.Color="White" Text="[CallBack]" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell63" Border.Lines="All" Fill.Color="White" Text="[gongzuoliangzb.Outbound]/[gongzuoliangzb.CallBack]" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt">
            <Formats>
              <PercentFormat DecimalDigits="1"/>
              <GeneralFormat/>
            </Formats>
          </TableCell>
          <TableCell Name="Cell70" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell71" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell88" Border.Lines="All" Fill.Color="White" Format="Percent" Format.UseLocale="true" Format.DecimalDigits="2" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell89" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell90" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell97" Border.Lines="All" Fill.Color="White" Format="Percent" Format.UseLocale="true" Format.DecimalDigits="2" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
        </TableRow>
        <TableRow Name="Row10" Height="27.64">
          <TableCell Name="Cell72" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell73" Border.Lines="All" Fill.Color="Gainsboro" Text="total" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell74" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell75" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell76" Border.Lines="All" Fill.Color="White" Format="Percent" Format.UseLocale="true" Format.DecimalDigits="2" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell77" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell78" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell91" Border.Lines="All" Fill.Color="White" Format="Percent" Format.UseLocale="true" Format.DecimalDigits="2" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell92" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell93" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell98" Border.Lines="All" Fill.Color="White" Format="Percent" Format.UseLocale="true" Format.DecimalDigits="2" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
        </TableRow>
        <TableRow Name="Row11" Height="28.35">
          <TableCell Name="Cell99" Border.Lines="All" Fill.Color="Gainsboro" Text="total" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" ColSpan="2"/>
          <TableCell Name="Cell100" Font="宋体, 9pt"/>
          <TableCell Name="Cell101" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell102" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell103" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell104" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell105" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell106" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell107" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell108" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell109" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
        </TableRow>
      </MatrixObject>
    </DataBand>
  </ReportPage>
</Report>
`

**Comment by Snuger** [comment]
'<?xml version="1.0" encoding="utf-8"?>
<Report>
  <Dictionary>
    <TableDataSource Name="gongzuoliangzb" ReferenceName="Reports.gongzuoliangzb" DataType="System.String" Enabled="true">
      <Column Name="name" DataType="System.String"/>
      <Column Name="type" DataType="System.String"/>
      <Column Name="busType" DataType="System.String"/>
      <Column Name="Outbound" DataType="System.Decimal"/>
      <Column Name="CallBack" DataType="System.Decimal"/>
      <Column Name="Column" Alias="DifferenceRate" DataType="System.Int32" Calculated="true" Expression=""/>
    </TableDataSource>
    <TableDataSource Name="renYuanXX" ReferenceName="Reports.renYuanXX" DataType="System.String" Enabled="true">
      <Column Name="name" DataType="System.String"/>
      <Column Name="orgName" DataType="System.String"/>
      <Column Name="orgGroup" DataType="System.String"/>
    </TableDataSource>
    <Relation Name="renYuanXX_gongzuoliangzb" ParentDataSource="renYuanXX" ChildDataSource="gongzuoliangzb" ParentColumns="name" ChildColumns="name" Enabled="true"/>
    <Parameter Name="TimeRange" DataType="System.String"/>
  </Dictionary>
  <ReportPage Name="Page1" Landscape="true" PaperWidth="297" PaperHeight="210" RawPaperSize="9" Watermark.Font="宋体, 60pt">
    <ReportTitleBand Name="ReportTitle1" Width="1047.06" Height="53.15" FirstRowStartsNewPage="true">
      <TextObject Name="Text1" Left="462.11" Top="9.45" Width="122.85" Height="28.35" Text="ReportName" HorzAlign="Center" VertAlign="Center" Font="宋体, 16pt, style=Bold"/>
    </ReportTitleBand>
    <DataBand Name="Data1" Top="57.41" Width="1047.06" Height="204.35" CanGrow="true">
      <MatrixObject Name="Matrix2" Left="37.1" Width="567.71" Height="176" Fill.Color="ControlText" FixedRows="3" FixedColumns="2" AutoSize="false" CellsSideBySide="true" DataSource="gongzuoliangzb" Style="Gray">
        <MatrixColumns>
          <Header Expression="[gongzuoliangzb.busType]"/>
          <Header Expression="[gongzuoliangzb.type]"/>
        </MatrixColumns>
        <MatrixRows>
          <Header Expression="[gongzuoliangzb.renYuanXX.orgName]"/>
          <Header Expression="[gongzuoliangzb.name]"/>
        </MatrixRows>
        <MatrixCells>
          <Cell Expression="[gongzuoliangzb.Outbound]"/>
          <Cell Expression="[gongzuoliangzb.CallBack]"/>
          <Cell Expression="[gongzuoliangzb.Outbound]/[gongzuoliangzb.CallBack]"/>
        </MatrixCells>
        <TableColumn Name="Column8"/>
        <TableColumn Name="Column9" Width="55.52"/>
        <TableColumn Name="Column10" Width="41.58"/>
        <TableColumn Name="Column11" Width="41.58"/>
        <TableColumn Name="Column12" Width="0"/>
        <TableColumn Name="Column13" Width="60.48"/>
        <TableColumn Name="Column14" Width="60.48"/>
        <TableColumn Name="Column15" Width="60.48"/>
        <TableColumn Name="Column16" Width="60.48"/>
        <TableColumn Name="Column17" Width="60.48"/>
        <TableColumn Name="Column18" Width="60.48"/>
        <TableRow Name="Row6" Height="27.64">
          <TableCell Name="Cell44" Border.Lines="All" Fill.Color="Gainsboro" Text="orgName" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" RowSpan="3"/>
          <TableCell Name="Cell45" Border.Lines="All" Fill.Color="Gainsboro" Text="name" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" RowSpan="3"/>
          <TableCell Name="Cell50" Border.Lines="All" Fill.Color="Gainsboro" Text="[busType]" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" ColSpan="6"/>
          <TableCell Name="Cell53" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell54" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell64" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell65" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell79" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell80" Border.Lines="All" Fill.Color="Gainsboro" Text="total" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" ColSpan="3" RowSpan="2"/>
          <TableCell Name="Cell81" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell94" Font="宋体, 9pt, style=Bold"/>
        </TableRow>
        <TableRow Name="Row7" Height="27.64">
          <TableCell Name="Cell46" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell47" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell51" Border.Lines="All" Fill.Color="Gainsboro" Text="[type]" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" ColSpan="3"/>
          <TableCell Name="Cell55" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell56" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell66" Border.Lines="All" Fill.Color="Gainsboro" Text="total" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" ColSpan="3"/>
          <TableCell Name="Cell67" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell82" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell83" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell84" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell95" Font="宋体, 9pt, style=Bold"/>
        </TableRow>
        <TableRow Name="Row8" Height="37.09">
          <TableCell Name="Cell48" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell49" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell52" Border.Lines="All" Fill.Color="Gainsboro" Text="Outbound" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell57" Border.Lines="All" Fill.Color="Gainsboro" Text="CallBack" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell58" Border.Lines="All" Fill.Color="Gainsboro" Text="DifferenceRate" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell68" Border.Lines="All" Fill.Color="Gainsboro" Text="Outbound" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell69" Border.Lines="All" Fill.Color="Gainsboro" Text="CallBack" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell85" Border.Lines="All" Fill.Color="Gainsboro" Text="DifferenceRate" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell86" Border.Lines="All" Fill.Color="Gainsboro" Text="Outbound" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell87" Border.Lines="All" Fill.Color="Gainsboro" Text="CallBack" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell96" Border.Lines="All" Fill.Color="Gainsboro" Text="DifferenceRate" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
        </TableRow>
        <TableRow Name="Row9" Height="27.64">
          <TableCell Name="Cell59" Border.Lines="All" Fill.Color="Gainsboro" Text="[orgName]" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" RowSpan="2"/>
          <TableCell Name="Cell60" Border.Lines="All" Fill.Color="Gainsboro" Text="[name]" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell61" Border.Lines="All" Fill.Color="White" Text="[Outbound]" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell62" Border.Lines="All" Fill.Color="White" Text="[CallBack]" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell63" Border.Lines="All" Fill.Color="White" Text="[gongzuoliangzb.Outbound]/[gongzuoliangzb.CallBack]" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt">
            <Formats>
              <PercentFormat DecimalDigits="1"/>
              <GeneralFormat/>
            </Formats>
          </TableCell>
          <TableCell Name="Cell70" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell71" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell88" Border.Lines="All" Fill.Color="White" Format="Percent" Format.UseLocale="true" Format.DecimalDigits="2" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell89" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell90" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell97" Border.Lines="All" Fill.Color="White" Format="Percent" Format.UseLocale="true" Format.DecimalDigits="2" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
        </TableRow>
        <TableRow Name="Row10" Height="27.64">
          <TableCell Name="Cell72" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell73" Border.Lines="All" Fill.Color="Gainsboro" Text="total" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold"/>
          <TableCell Name="Cell74" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell75" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell76" Border.Lines="All" Fill.Color="White" Format="Percent" Format.UseLocale="true" Format.DecimalDigits="2" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell77" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell78" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell91" Border.Lines="All" Fill.Color="White" Format="Percent" Format.UseLocale="true" Format.DecimalDigits="2" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell92" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell93" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell98" Border.Lines="All" Fill.Color="White" Format="Percent" Format.UseLocale="true" Format.DecimalDigits="2" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
        </TableRow>
        <TableRow Name="Row11" Height="28.35">
          <TableCell Name="Cell99" Border.Lines="All" Fill.Color="Gainsboro" Text="total" HorzAlign="Center" VertAlign="Center" Font="宋体, 9pt, style=Bold" ColSpan="2"/>
          <TableCell Name="Cell100" Font="宋体, 9pt"/>
          <TableCell Name="Cell101" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell102" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell103" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell104" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell105" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell106" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell107" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell108" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
          <TableCell Name="Cell109" Border.Lines="All" Fill.Color="White" HorzAlign="Right" VertAlign="Center" Font="宋体, 9pt"/>
        </TableRow>
      </MatrixObject>
    </DataBand>
  </ReportPage>
</Report>
'

**Comment by Snuger** [comment]
[jixiaotj-tongyong-gongzuoliangzb-debug.txt](https://github.com/FastReports/FastReport/files/5577043/jixiaotj-tongyong-gongzuoliangzb-debug.txt)


  string reportFile = Path.Combine(JiXiaoTJReportConstant.CONST_REPORT_FRX_ROOT, $"jixiaotj-tongyong-{reportParameter.ReportName.ToLower().ToString()}-debug.frx");
            if (string.IsNullOrWhiteSpace(reportParameter.ReportName))
                return BadRequest($"报表名{reportParameter.ReportName}-不存在");
            if (!System.IO.File.Exists(reportFile))
                return BadRequest($"{reportFile},报表文件不存在");
            DataSet dataSet = await _kaiFaRYTJService.GetKaiFaRYJXTJAsync(reportParameter);
            WebReport WebReport = new WebReport();
            WebReport.Report.Load(reportFile);
            WebReport.Report.RegisterData(dataSet, "Reports");
            ViewBag.WebReport = WebReport;
            return View("Report");

**Comment by Snuger** [comment]
sorry   I wrote an I was not careful, extra ";" symbol on my own page
