### ISSUE TITLE
Wrong Barcode

### ISSUE THREAD

**Issue by AliSabzali** [FastReports/FastReport#237]
Hello guys.
When I wanted use fastreport for make a USPS mailing label,
I figured out that Barcode of GS1-128 (UCC/EAN 128), makes wrong result.
can you check it and solve its problem?
![test](https://user-images.githubusercontent.com/10707957/100577012-49927c80-32ad-11eb-85f9-a2f1d3cd5e39.png)

**Comment by fediachov** [comment]
Hi! We will check the barcode and I will answer you.

**Comment by VitaliyRud2001** [comment]
Hi! We reproduced the problem. It will be fixed soon.

**Comment by VitaliyRud2001** [comment]
Hello!
You want to generate USPS mailing label and you use GS1-128 (UCC/EAN 128) for this purpose?
Do I understand you correctly?

**Comment by AliSabzali** [comment]
Yes. I wanna use it to make a USPS label. 
If it is possible that developers can change X-dimension and Resolution (dpi) of barcode, it is better applicable.

**Comment by VitaliyRud2001** [comment]
> Yes. I wanna use it to make a USPS label.
> If it is possible that developers can change X-dimension and Resolution (dpi) of barcode, it is better applicable.

Are you talking about USPS Package Identification Code Barcode which is based on UCC/EAN-128 GS1-128?
There are so many barcodes 😄

**Comment by DavidCFreire** [comment]
I'm facing the same issue when exporting the report with HTMLExport with 2/5 Interleaved barcode
#589
