### ISSUE TITLE
Report builder for building report from code

### ISSUE THREAD

**Issue by ekondur** [FastReports/FastReport#241]
Hello,
I've developed a fluent builder with some features of FastReport to build report easy way. It supports strongly types. If you want,  I can add it to your open source project and develop other features.

git repo ->[https://github.com/ekondur/FastReportBuilder]( https://github.com/ekondur/FastReportBuilder)

Thanks for amazing framework.

**Comment by fediachov** [comment]
Hi,

Great job! We'll be very grateful for that!

**Comment by fediachov** [comment]
Our code has an MIT license. Does that suit you?

**Comment by ekondur** [comment]
I think with MIT licence, the codes I wrote will be fastreport opensource project community ?
If so it's OK for me :)

**Comment by fediachov** [comment]
Yes, I meant only FastReport Open Source with MIT license.
Could you make a pull request with the code to the Extras/FastReportBuilder folder? Please put your name (maybe github name) in the README.md file in that folder. Also, you can add your LICENSE.md with MIT license with your name.

If so, you'll be listed as a contributor to the project, and we'll add your name to our main README.md

Also, thank you very much for your work!
