### ISSUE TITLE
Printed barcode not recognized by the bank

### ISSUE THREAD

**Issue by bernardonascimento** [FastReports/FastReport#252]
I am generating a boleto and the barcode generated by the component is not recognized by the reader nor by the bank.

Perhaps the standard I am using is not correct 128A or the size is not necessary or something related to zoom.

Has anyone managed to generate tickets (44 caracteres/numbers) with FastReport.

![image](https://user-images.githubusercontent.com/44785140/103242307-8c8b5280-4934-11eb-83c3-cddd045a30c8.png)
![image](https://user-images.githubusercontent.com/44785140/103242355-acbb1180-4934-11eb-8382-689908d2d74d.png)

The barcode below is generated using type 128A and is read normally by the reader

![image](https://user-images.githubusercontent.com/44785140/103242435-eb50cc00-4934-11eb-9948-c0906218452e.png)

**Comment by MaratAlaev** [comment]
Hello!

In the latest version 
this problem is not reproduced

Best regards 
Marat

**Comment by DavidCFreire** [comment]
I'm facing the same issue when exporting the report with HTMLExport

**Comment by DavidCFreire** [comment]
using 2/5 Interleaved barcode
#589
