### ISSUE TITLE
FastReport base path is not correct in iis. 

### ISSUE THREAD

**Issue by jc0814** [FastReports/FastReport#256]
I have my .net core 3.1 project published on IIS. 
However, the report doesn't work correctly.
I have errors like 404 not found. (but it works perfectly both on another VM and my local machine.) 
The only difference is that the error one is published under **Subfolder**. 
However, the base path seems wrong which not target the right folder. 
e.g.   
it should be something like   www.abc.com/[webName]/_fr/reference....  
but it shows   www.abc.com/_fr/reference  .... 

I tried to use  app.UseFastReport(options => options.RouteBasePath = "/[webName]/_fr");  
but it didn't work....
I need your help on this.  
![Snipaste_2021-01-20_21-25-25](https://user-images.githubusercontent.com/11080533/105180849-0a263500-5b66-11eb-9d6c-11fed1889729.png)

**Comment by JordiKocina** [comment]
Hi, I'm working with net core 3.1 and the report works fine in my local visual studio. But, when I publish the project on my web site I get the error "404 not found" when WebReport.Render() is triggered. Could you solve this error?

Thanks and regards

**Comment by KirillKornienko** [comment]
Duplicate #186 . We will increase the priority of this task

**Comment by jc0814** [comment]
> Duplicate #186 . We will increase the priority of this task

thanks
