### ISSUE TITLE
Exception swallowed in TextObjectBase.CalcAndFormatExpression

### ISSUE THREAD

**Issue by sandord** [FastReports/FastReport#257]
I just noticed that the `CalcAndFormatExpression` method in `TextObjectBase.cs` swallows the original exception, only passing the inner exception into the new exception:

https://github.com/FastReports/FastReport/blob/d433d505823e84140ad4458baff253a7a91811f4/FastReport.Base/TextObjectBase.cs#L463

In my case, when a database connection exception occurs, there's no way for the host application to know about it (or log it) because the connection exception is in `ex` which itself isn't passed on.

The result of this issue is that I only see exceptions about failed expressions in my log, not failed database connections. This makes troubleshooting much harder.

**Comment by sandord** [comment]
Of course this applies to any kind of exceptions that is thrown during `CalcAndFormatExpression`. All of them are hidden, only their underlying exceptions are exposed which most of the time are not very useful or even absent.

**Comment by Alekarfes** [comment]
There's been a change regarding how the exceptions are handled, and we believe it should fix the problem you're describing. Please tell us if this is still an issue on later versions of FastReport.

**Comment by sandord** [comment]
That's great to hear. I've changed jobs in the meantime so I'm not in the position to try it anymore.
