### ISSUE TITLE
TextObject not creating properly on web designer

### ISSUE THREAD

**Issue by StefanDamchevski** [FastReports/FastReport#260]
Hello!

So as you can see in the video, the first time I add the text object the designer says that it was created, but in the frx file a text object was not added, you can see that when I load the same report again. Later on I add the text field again and press preview so that the designer tries to add the text object while processing the report. So pressing save again after seems to create the text object.

https://user-images.githubusercontent.com/58256222/107207458-9bb7f280-6a00-11eb-9c75-09f2608899ab.mp4

How to save my text object without previewing the report before save?

Thanks in advance!!

**Comment by RedKot73** [comment]
Hi!
There is a bug that I fixed like this:

[DesignerController.cs.txt](https://github.com/FastReports/FastReport/files/6010222/DesignerController.cs.txt)

namespace FastReport.Web.Controllers
{
    class DesignerController : BaseController

**Comment by KirillKornienko** [comment]
Hello! This bug fixed. We will release an updated version of the package in the near future

**Comment by StefanDamchevski** [comment]
@KirillKornienko Can you be more precise about the release date?

**Comment by RedKot73** [comment]
After insert a RTF element and save report, then loading I get the message:
"Can't find object RichObject"

**Comment by KirillKornienko** [comment]
@RedKot73 Try the latest FastReport.OpenSource.Web package 2021.1.20

**Comment by RedKot73** [comment]
@KirillKornienko 
I don't see version 2021.1.20, latest available is 2021.1.16

Didn't finish writing my correction:
>>
`
        public async Task<string> ReadStringDataManual(Stream ABodyStrm, WebReport AWebReport)
        {
            using (StreamReader vReader = new StreamReader(ABodyStrm, Encoding.UTF8))
            {
                var vBody = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" + await vReader.ReadToEndAsync();
                return AWebReport.DesignerSaveMethod(AWebReport.ID,
                    AWebReport.ReportFileName,
                    System.Web.HttpUtility.HtmlDecode(vBody));
            }
        }
/////////

                if (webReport.DesignerSaveMethod == null)
                {
                    // old saving way by self-request
                    return webReport.DesignerSaveReport(Context);
                }
                else
                {
                    _ = ReadStringDataManual(Request.Body, webReport);
`

**Comment by KirillKornienko** [comment]
@RedKot73 https://www.nuget.org/packages/FastReport.OpenSource.Web/2021.1.20

**Comment by RedKot73** [comment]
@KirillKornienko 
Will the sources for the updated package be available?

**Comment by KirillKornienko** [comment]
> @KirillKornienko
> Will the sources for the updated package be available?

Sources are updated
