### ISSUE TITLE
Designer - Strong name failure by choosing the mongodb connector

### ISSUE THREAD

**Issue by nistadie** [FastReports/FastReport#261]
Every time, i start the fast report designer and open the data wizard to connect to mongo database a error window pops up. The message behind: A strong name assembly is required. Assembly "MongoDB.Driver.Core, Version=2.11.0.0 (HERSULT :0x80131044)

What can i do to fix this issue?

Thanks in advance! :)

**Comment by fediachov** [comment]
Should be fixed in the latest build
