### ISSUE TITLE
HTML export: embedded stylesheet contains wrong class selectors

### ISSUE THREAD

**Issue by fubar-coder** [FastReports/FastReport#264]
The stylesheet contains selectors like `.s0-1`, while the elements contain the class `s0` instead of `s0-1`, which results in styles not being applied.

This is an example with an HTML export: [test2.zip](https://github.com/FastReports/FastReport/files/6025114/test2.zip)

**Comment by MaratAlaev** [comment]
Hello!

The latest version exports correctly 

Best regards 
Marat
