### ISSUE TITLE
FastReport Designer says "Could not find file or assembly System.Threading.Tasks.Extensions version=4.1.0.0"

### ISSUE THREAD

**Issue by ProsserCJ** [FastReports/FastReport#270]
Hello, I am getting this error when I try to add a Postgres datasource in FastReport Designer. It looks like a missing .NET dll. This happens when I click "Test Connection". 

I'm using v2021.2.0 of FastReport Designer, which I downloaded [here](https://github.com/FastReports/FastReport/releases/tag/v2021.2.0), with Postgres 12.4.

![image](https://user-images.githubusercontent.com/4368756/110964073-ca3b2d00-8320-11eb-9cc5-14f7768abfee.png)

**Comment by fediachov** [comment]
Hello,

Thanks for your message! We will fix it ASAP

**Comment by KirillKornienko** [comment]
Hello, @ProsserCJ . We fixed this problem and `FastReport.Community.zip` are updated in 2021.2.0 release.

**Comment by ProsserCJ** [comment]
Thank you! It seems to work. I appreciate your quick response.

**Comment by gbellini79** [comment]
Hi, same problem in the new 2024.1.3 version

**Comment by VaisVeron** [comment]
Hello! Same error in 2024.2.0 version.
