### ISSUE TITLE
How to print the header after the table is paged?

### ISSUE THREAD

**Issue by jonny-xhl** [FastReports/FastReport#272]
### The test data
```sql
CREATE TABLE TestTable(
    ID int,
    SDate datetime
)

INSERT INTO TestTable
VALUES (1,GETDATE())
    ,(1,GETDATE())
    ,(1,GETDATE())
```
> Notice:Add more than 20 lines to the test.

### Add Data Source

Add  data source with the TestTable.

### The report design
<img src="https://user-images.githubusercontent.com/29520329/112121541-52abae80-8bfa-11eb-8a43-2ebf5819fd4b.png" width="300"/>

### The table ManualBuildEvent
```csharp
public class ReportScript
  {
    private void TableTest_ManualBuild(object sender, EventArgs e)
    {
      DataSourceBase data1 = Report.GetDataSource("TestTable"); 
      data1.Init(); 
      TableTest.PrintRow(0);
      TableTest.PrintColumns();   
      while(data1.HasMoreRows)
      {
        TableTest.PrintRow(1);
        TableTest.PrintColumns();
        data1.Next();
      }
    }
  }
```

### The result
I want the text on the table to be printed after paging when there is a lot of data, and the header of the table to be printed after paging.
<img src="https://user-images.githubusercontent.com/29520329/112121941-bf26ad80-8bfa-11eb-97b5-fd1cbc7f536b.png" width="400"/>

**One of my solutions solves the problem of printing table headers after paging:**
```csharp
     while(data1.HasMoreRows)
      {
        if (data1.CurrentRowNo!=0 && data1.CurrentRowNo%20==0)
        {
          TableTest.PrintRow(0);
          TableTest.PrintColumns();
        }
        TableTest.PrintRow(1);
        TableTest.PrintColumns();
        data1.Next();
      }
```
> But you need to know exactly how many rows of data are on each page of the table.

**Comment by jeftegoesdev** [comment]
Enable all properties in PrintOn
![image](https://user-images.githubusercontent.com/15343678/113637024-06c12680-964a-11eb-84db-254f11b70848.png)

Look this result:
![image](https://user-images.githubusercontent.com/15343678/113637072-1b9dba00-964a-11eb-9b8b-da20c759d4d3.png)

**Comment by jonny-xhl** [comment]
> Select first the Band Page Header and enable all properties in PrintOn
> ![image](https://user-images.githubusercontent.com/15343678/113637164-57388400-964a-11eb-8cda-4bd1cc0a32f0.png)
> 
> Look this result:
> ![image](https://user-images.githubusercontent.com/15343678/113637072-1b9dba00-964a-11eb-9b8b-da20c759d4d3.png)

This is really a solution.Tks.
