### ISSUE TITLE
How to add business Object datasource from the report designer ?

### ISSUE THREAD

**Issue by chibimaruko88** [FastReports/FastReport#273]
Hi, May I know how to add business object datasource from the report designer ?

**Comment by jeftegoesdev** [comment]
Look this example https://www.fast-report.com/en/blog/64/show/

**Comment by behroozbc** [comment]
I have the same issue. This progress is too complex.

**Comment by BogdanStegachev** [comment]
Hello!

You can read about using FastReport Business Graphics in FastReport.Net in our article: https://www.fast-report.com/en/blog/show/install-business-graphics-net/

Best regards,
Bogdan
