### ISSUE TITLE
cannot use app.UsePathbase("xxxx")

### ISSUE THREAD

**Issue by shaofing** [FastReports/FastReport#274]
My English is not good.

不能使用app.UsePathbase("xxxx") ; 各种资源都找不到。
cannot use app.UsePathbase("xxxx");  Various resources cannot be found .

![image](https://user-images.githubusercontent.com/21122388/112276512-cc57a100-8cbb-11eb-96a4-bcf418ed70af.png)

-----------------------------------   HotFix  --------------------------------------------
我已经修复了这个bug,附上代码
I've fixed the bug and attached the code

![image](https://user-images.githubusercontent.com/21122388/112277087-5d2e7c80-8cbc-11eb-8ebc-5da9641b1ec5.png)
![image](https://user-images.githubusercontent.com/21122388/112277154-6cadc580-8cbc-11eb-9a01-a15a81608a11.png)
![image](https://user-images.githubusercontent.com/21122388/112277396-ad0d4380-8cbc-11eb-879f-a899ea04988b.png)

**Comment by KirillKornienko** [comment]
Hi, this bug has been fixed recently! Try the latest version. Important: you must call app.UseFastReport () before UseEndpoints / UseMVC for this fix to work correctly.
