### ISSUE TITLE
htmlExport  do not  page Break

### ISSUE THREAD

**Issue by jianliulin** [FastReports/FastReport#277]
var htmlExport = new HTMLExport();
htmlExport.PageBreaks = true;
fastReport.Prepare();
fastReport.Export(htmlExport, stream);

chrome print preview the report do not  page break 

<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name=Generator content="FastReport http://www.fast-report.com">
<title></title>
</head>
<body bgcolor="#FFFFFF" text="#000000">
<style type="text/css" media="print"></style>
.....
<div class="frpage0"  ....
<div class="frpage1" .... 
<div class="frpage2" ...

![image](https://user-images.githubusercontent.com/4531974/112429051-19e51400-8d77-11eb-8059-e32689e1b9c4.png)

**Comment by fediachov** [comment]
Fixed in 2021.3.17
