### ISSUE TITLE
PdfSimple обрезает изображения.

### ISSUE THREAD

**Issue by ksakz** [FastReports/FastReport#278]
В дизайнере все выглядит хорошо.
Но при экспорте в PDF картинки обрезаются (сверху и слева)

**Comment by fediachov** [comment]
Здравствуйте! Какая операционная система используется?

**Comment by ksakz** [comment]
Операционная система линукс.  Запускаю в docker контейнере

**Comment by ksakz** [comment]
Опытным путем выявил, что если у объекта page обнулить свойства LeftMargin и TopMargin, то картинки не обрезаются, но у страницы  пропадают отступы

**Comment by ksakz** [comment]
в версии FastReport.OpenSource 2020.4.11 все работает нормально

**Comment by KirillKornienko** [comment]
Здравствуйте, попробуйте последние версии. Вероятно, этот баг был исправлен

**Comment by ksakz** [comment]
> Здравствуйте, попробуйте последние версии. Вероятно, этот баг был исправлен

Здравствуйте.  Проверил. Все работает. Спасибо!
