### ISSUE TITLE
How to test in linux mint

### ISSUE THREAD

**Issue by dannieljunior** [FastReports/FastReport#279]
I trying to restore using linux and vscode, bu when i execute the .sh file return many errors like /usr/share/dotnet/sdk/3.1.301/NuGet.targets(128,5): error : Access to the path '/home/myuser/.nuget/packages/fastreport.compat/2021.1.1' is denied.

please help!

**Comment by KirillKornienko** [comment]
Have you tried on the latest versions? What command are you running?
