### ISSUE TITLE
Using JSON(Javascript Object Notation) datasource send data from .Net Core

### ISSUE THREAD

**Issue by tbbyazilim** [FastReports/FastReport#281]
Hi,

I create a list from person class that using .Net Core 5.0. and send to report but fastreport consists of a single line from the first element of the list.

```
      List<Person> data = GetDummyData();
      Report report = new Report();
      report.Load("C:\\Users\\testyazilim\\Desktop\\PersonJsonTest.frx");
      report.RegisterData(data, "JSON.item");
      report.Prepare();
```
The json format I use is as follows; and json schema is created automatically.

```
{
 "Id": {
  "type": "integer"
 },
 "Name": {
  "type": "string"
 },
 "Surname": {
  "type": "string"
 },
 "Age": {
  "type": "integer"
 }
}
```
the report is generated successfully but only from a single line, although I use a table in ".frx" report. I used many different versions of json, but the result was the same.

I use FastReport Community.

**Comment by jeftegoesdev** [comment]
Which band is using?

**Comment by tbbyazilim** [comment]
<img width="896" alt="ss" src="https://user-images.githubusercontent.com/80811456/114680135-84a1c380-9d15-11eb-826f-978639669365.png">

**Comment by jeftegoesdev** [comment]
There are 2 distinct approaches:

1. JSON, in this case, you need load one file .json or serialize object and pass to .frx file;
2. BusinessObjeect, you need build a object BusinessObjectDataSource into .frx file this form:
![image](https://user-images.githubusercontent.com/15343678/115129765-5d6e1f00-9fbf-11eb-8c76-8bce946da4b6.png)

In your case, you are mixing the 2 approaches.

I created this repository to demonstrate use with BusinessObjeect
https://github.com/jeftegoesdev/ExampleFastReportBusinessObject

**Comment by tbbyazilim** [comment]
Thank you, sir

**Comment by neozhu** [comment]
> There are 2 distinct approaches:
> 
> 1. JSON, in this case, you need load one file .json or serialize object and pass to .frx file;
> 2. BusinessObject, you need build a object BusinessObjectDataSource into .frx file this form:
>    ![image](https://user-images.githubusercontent.com/15343678/115129765-5d6e1f00-9fbf-11eb-8c76-8bce946da4b6.png)
> 
> In your case, you are mixing the 2 approaches.
> 
> I created this repository to demonstrate use with BusinessObjeect
> https://github.com/jeftegoesdev/ExampleFastReportBusinessObject

please, see my question. how change json datasource when running
https://github.com/FastReports/FastReport/issues/307#issue-923282198
