### ISSUE TITLE
.Net Core 3.1 and FastReport OpenSource Web

### ISSUE THREAD

**Issue by siwakornapichit** [FastReports/FastReport#282]
I has install 3 package 

1.) FaslReport Opensource
2.) FastReport.Opensource.Export.PdfSimple
3.) FastReport.OpenSource.Web

I cloud not publish to win 64 package or Linux package after Install Opensource.Web. VS 2019 show error dialog.

Publish has encountered an error.
Build failed. Check the Output window for more details.

A diagnostic log has been written to the following location:
"C:\Users\Admin\AppData\Local\Temp\tmpDEC9.tmp"

Thank

**Comment by KirillKornienko** [comment]
A few questions. Have you tried on the latest versions? What command are you running? Which TFM are you using (.NET Core 3.1 or .NET 5)? Single File? etc
