### ISSUE TITLE
FastReport Opensource Web Preview Printing Landscape

### ISSUE THREAD

**Issue by Anat56** [FastReports/FastReport#284]
When you print a landscape template in the browser, only the first page is styled for rotation, the rest are rendered in normal orientation:
`<style type="text/css" media="print">
</style>`
But the page contains multiple frpage... elements

**Comment by Anat56** [comment]
Clarification: each page has its own class frpage0..frpageN, but only frpage0 has style in tag `<style type="text/css" media="print">`

**Comment by KirillKornienko** [comment]
Can you send report file (*.frx) with this problem? I tried my report with landscape and portrait pages and everything works correctly. Version 2021.3.6

**Comment by Anat56** [comment]
Во вложении сохраненная страница предварительного просмотра, а так же файл шаблона отчета. 
Пакеты обновил до 2021.3.6 — изменений нет 
>Суббота, 12 июня 2021, 2:06 +03:00 от Kirill Kornienko ***@***.***>:
> 
> 
>Can you send report file (*.frx) with this problem? I tried my report with landscape and portrait pages and everything works correctly. Version 2021.3.6
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
C уважением, Анатолий.

**Comment by KirillKornienko** [comment]
> Во вложении сохраненная страница предварительного просмотра, а так же файл шаблона отчета.  Пакеты обновил до 2021.3.6 — изменений нет
> Суббота, 12 июня 2021, 2:06 +03:00 от Kirill Kornienko ***@***.***>:     Can you send report file (*.frx) with this problem? I tried my report with landscape and portrait pages and everything works correctly. Version 2021.3.6 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or unsubscribe .
>     C уважением, Анатолий.

Вы уверены, что вы что-то приложили? Я не вижу никакого шаблона отчёта

**Comment by Anat56** [comment]
В исходящих у меня вложения есть. Вложил архив с двумя файлами, дополнительно ссылка на него:
https://disk.yandex.ru/d/IXJGcLg28RZteA 
>Четверг, 1 июля 2021, 12:45 +03:00 от Kirill Kornienko ***@***.***>:
> 
> 
>Во вложении сохраненная страница предварительного просмотра, а так же файл шаблона отчета.  Пакеты обновил до 2021.3.6 — изменений нет
>Суббота, 12 июня 2021, 2:06 +03:00 от Kirill Kornienko  @ .** >:     Can you send report file ( .frx) with this problem? I tried my report with landscape and portrait pages and everything works correctly. Version 2021.3.6 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or unsubscribe .
>    C уважением, Анатолий.
Вы уверены, что вы что-то приложили? Я не вижу никакого шаблона отчёта
—
You are receiving this because you authored the thread.
Reply to this email directly,  view it on GitHub , or  unsubscribe .  
 
C уважением, Анатолий.

**Comment by Anat56** [comment]
Через почту отправлял сообщения c вложениями, т.е. отвечал на письмо. Наверно поэтому криво вложения обрабатываются, но в предыдущем сообщении есть ссылка на файлы в облаке

**Comment by VaskarBanerjee** [comment]
FastReport Opensource page setup a landscape not working, While click print from Browser, only the first page is in Landscape orientation, the rest are rendered in Portrait orientation. Big issue.

**Comment by MaratAlaev** [comment]
Hello!

The problem is not reproduced in the latest version

Best regards 
Marat

**Comment by VaskarBanerjee** [comment]
Not properly resolved. showing blank page on first and last page when
printing layout is Landscape.

File attached.
