### ISSUE TITLE
Store HTML/JS in FastReport template

### ISSUE THREAD

**Issue by RedKot73** [FastReports/FastReport#285]
Is there a mechanism for saving HTML and JavaScript fragments in the FastReport template?
For my task, it would be perfect to store such fragments together with the description of the data source.

**Comment by jeftegoesdev** [comment]
Look this example:
![image](https://user-images.githubusercontent.com/15343678/115478320-45dfa200-a21c-11eb-921e-270a48bb6fb6.png)

Some html tags related to formatting (italic, bold, paragraph) will work, others will not.

JavaScript not.
