### ISSUE TITLE
Not displaying "č" at the end of words using FastReport .frx document in Origam

### ISSUE THREAD

**Issue by HankaZ** [FastReports/FastReport#288]
**Environment (used apliactions):**
* Origam no. 7179 (but it did not worked even in the previous versions)
* FastReport.Net - Version 2021.1.16 Community Edition

**Initial conditions:**
1. I create the .frx item in FastReport to be used in Origam displayed as pdf document.
2. In the FastReport there is used Arial font and Czech language and diacritics.
![obrazek](https://user-images.githubusercontent.com/83660572/117033550-c31e1300-ad02-11eb-974f-d604ee3d3563.png)
3. There are some words ending with letter "č" not followed by any symbol
4. There are other words ending with the rest of specific czech letters as well.
5. All are clearly visible in the FastReport preview.
![obrazek](https://user-images.githubusercontent.com/83660572/117033193-6d496b00-ad02-11eb-87dd-444708cedd45.png)
6. The Origam has it´s own custom Docker Image using font Arial (it does not matter which fonts I use, I can even used the build in fonts of Origam, that are DejaVuSans.ttf)

**Steps to reproduce:**
Open Origam UserInterface environment and open a document pdf related to the .frx document.

**Expected result:**
The letter "č" will be displayed in Origam pdf document (identically as in the preview in FastReport).

**Current result:**
1. The letter "č" is not displayed in the pdf document downloaded in Origam.
2. If the letter "č" is followed by any other symbol (ex. a dott) it is visible.
![obrazek](https://user-images.githubusercontent.com/83660572/117034174-535c5800-ad03-11eb-9517-224d111c3fc9.png)
3. All other specific czech letters at the end of words are displayed correctly

**Comment by tvavrda** [comment]
The server which produces the PDF with a missing letter runs on .net core 5 Linux (standard Microsoft image).
