### ISSUE TITLE
An exception occurred when using the export under multiple concurrent requests

### ISSUE THREAD

**Issue by BlackPig-dev** [FastReports/FastReport#290]
Use multiple thread request ‘TestReport’,Triggered an abnormal exit from the container.
Building libgdiplus library from source.
FastReport.OpenSource Version:2021.2.7
errorlogs:
kernel: dotnet[30286]: segfault at 0 ip 00007f5214309a3c sp 00007f51d5117790 error 4 in libfontconfig.so.1.12.0[7f52142f8000+24000]

root@19b3e49e455c:/app# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

        [Route("/TestReport")]
        public List<string> TestPrint()
        {
            return ExportFile(false);
        }
        private List<string> ExportFile(bool saveFile, int resolution = 300)
        {
            List<string> list = new List<string>();
            Report report = new Report();
            report.Load("1.frx");
            report.Prepare();
            ImageExport image = new ImageExport();
            image.ImageFormat = ImageExportFormat.Png;
            image.Resolution = 300;
            image.SeparateFiles = true;
            if (saveFile)
            {
                report.Export(image, DateTime.Now.ToString("yyyyMMdd_HHmmSSFFF")+"report.png");
            }
            else
            {
                using (MemoryStream reportImageStream = new MemoryStream())
                {
                    report.Export(image, reportImageStream);

                    list.Add(Convert.ToBase64String(reportImageStream.ToArray()));
                }
            }
            return list;
        }

**Comment by BlackPig-dev** [comment]
I use simple load, which also causes the container to exit on multi-threaded requests
```
         [Route("/TestLoad")]
        public IActionResult TestLoad(string type)
        {
            using (Report report = new Report())
            {
                report.LoadFromString(temp);
            }
            return Ok();
         }

```

**Comment by zs-dima** [comment]
@fediachov 
looks it could be related case
https://github.com/FastReports/FastReport/issues/313
it is quite critical issue that prevent us to use FastReport

**Comment by fediachov** [comment]
We are investigating this bug. Please wait.

**Comment by BlackPig-dev** [comment]
> We are investigating this bug. Please wait.

Thank you !

**Comment by fediachov** [comment]
Thanks for the wait and the bug report! The bug has been localized. We need a few days for testing. I will let you know when a new build is released.

**Comment by BlackPig-dev** [comment]
@fediachov 
Thank you very much

**Comment by fediachov** [comment]
@BlackPig-dev  Could you test latest changes in 2021.3.17?

**Comment by BlackPig-dev** [comment]
@fediachov thanks a lot for fix

**Comment by frantisekjandos** [comment]
Does not work for version 2021.3.30, see my tomorrow ticket: https://support.fast-report.com/tickets/626294?key=b9f274b427be576
