### ISSUE TITLE
Rest API Client Resource 404 Not Found

### ISSUE THREAD

**Issue by ismailkocacan** [FastReports/FastReport#291]
Hi, 

I'm trying FastReport  web components REST API (.net core 5) based.
Version : 2021.2.14
```
[HttpGet]
public IActionResult Get()
{
	WebReport WebReport = new WebReport();
	WebReport.Width = "1000";
	WebReport.Height = "1000";
	WebReport.Report.Load(@".\Reports\pentagon.frx");
	WebReport.Report.Prepare();
	WebReport.Mode = WebReportMode.Preview;
	string html = WebReport.RenderSync().Value;
	return new ContentResult
	{
		ContentType = "text/html",
		StatusCode = (int)HttpStatusCode.OK,
		Content = html
	};
}
```
I have create client application is Angular.

app.component.ts
```
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';

import { HttpClient } from '@angular/common/http';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'fastreportclient';

  reportHtmlValue:any;
  constructor(private httpClient:HttpClient) { }


  ngOnInit(): void { 
    this.httpClient.get('http://localhost:4240/api/FastReport',  { headers: { 'Accept': 'text/html' }, responseType: 'text' })
    .subscribe((response: any) => {    
      this.reportHtmlValue = response;
    }); 
  }

}
```
app.component.html
`<div #element [innerHTML]="reportHtmlValue | safeHtml"></div> 	`

safeHtml.pipe.ts
```
import { DomSanitizer } from '@angular/platform-browser'
import { PipeTransform, Pipe } from "@angular/core";

@Pipe({
  name: 'safeHtml'
})
export class SafeHtmlPipe implements PipeTransform {

  constructor(private sanitized: DomSanitizer) {}
  
  transform(value:string) {
    return this.sanitized.bypassSecurityTrustHtml(value);
  }

}

```

As I see URLs is wrong.
I added a sample projects  to reproduce the problem.
[FastReportIssue.zip](https://github.com/FastReports/FastReport/files/6481780/FastReportIssue.zip)
Thanks.

![image](https://user-images.githubusercontent.com/3339197/118345144-4e857880-b53b-11eb-8ab9-05fd3ca2c5ea.png)
![image](https://user-images.githubusercontent.com/3339197/118345187-91dfe700-b53b-11eb-92a2-54fc1044c32a.png)

**Comment by KirillKornienko** [comment]
Did you forget to call app.UseFastReport() ?
https://github.com/FastReports/FastReport/blob/master/FastReport.Core.Web/README.md
I draw your attention, it is advisable to call UseFastReport() before UseMvc/UseEndpoints

**Comment by ismailkocacan** [comment]
> Did you forget to call app.UseFastReport() ?
> https://github.com/FastReports/FastReport/blob/master/FastReport.Core.Web/README.md
> I draw your attention, it is advisable to call UseFastReport() before UseMvc/UseEndpoints

Did you try my reproduce example ?
