### ISSUE TITLE
Need to update Microsoft.CodeAnalysis.VisualBasic 3.3.1 to version 3.6.0 or higher

### ISSUE THREAD

**Issue by liftlei** [FastReports/FastReport#292]
![image](https://user-images.githubusercontent.com/34734852/118426565-02366600-b6fe-11eb-8046-4d419d1c3981.png)

**Comment by KirillKornienko** [comment]
If upgraded, all users with explicit version 3.3.1 will get an error. The reason for this is a strong reference to the Microsoft.CodeAnalysis.Common version from Microsoft.CodeAnalysis.CSharp and Microsoft.CodeAnalysis.VisualBasic.
  If you want to update the version of Microsoft.CodeAnalysis, explicitly import the Microsoft.CodeAnalysis.CSharp and Microsoft.CodeAnalysis.VisualBasic of the required version into your project. Example:

`<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.6.0" />`
`<PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="3.6.0" />`
