### ISSUE TITLE
Could not find file exception when Table Object exists

### ISSUE THREAD

**Issue by tomatostudio** [FastReports/FastReport#296]
Hello,

I'm using FastReport.OpenSource 2021.3.1 in WPF (.NET 5). When there are some table objects in a frx template, some exceptions will be raised in Prepare() function. But it seems to be fine in some other environment such as .Net 5 console application.

Here is the message.
Message = "Could not find file 'E:\\Development\\XXXXX\\output\\net5.0-windows\\System.dll'."
Message = "Could not find file 'E:\\Development\\XXXXX\\output\\net5.0-windows\\System.Drawing.dll'."
Message = "Could not find file 'E:\\Development\\XXXXX\\output\\net5.0-windows\\System.Data.dll'."
......

Here is the call stack.
![图片](https://user-images.githubusercontent.com/63195199/119632602-8c3fa680-be43-11eb-80eb-b624ac1551b9.png)

The report seems to be OK.

Thanks.

**Comment by MaratAlaev** [comment]
Hello!

We have not been able to reproduce this problem on the latest version 

Best regards 
Marat
