### ISSUE TITLE
how to use an Array object as a DataSource?

### ISSUE THREAD

**Issue by allen3371** [FastReports/FastReport#297]
i download the fastreport community designer ,and i can't find how to use an array as a datasource ,the demo "DataFromArray" 

thanks

**Comment by jeftegoesdev** [comment]
Look this example https://github.com/jeftegoesdev/ExampleFastReportBusinessObject

**Comment by allen3371** [comment]
> Look this example https://github.com/jeftegoesdev/ExampleFastReportBusinessObject

thanks
