### ISSUE TITLE
Can I convert rdlc report to frx?

### ISSUE THREAD

**Issue by wangchong666** [FastReports/FastReport#299]
I have some rdlc reports in old project,can i render them directly(or convert to frx) with FastReport

**Comment by fediachov** [comment]
![image](https://user-images.githubusercontent.com/43993341/125583565-42df0d8c-1d83-480c-916a-71ff2910a540.png)

You can convert view of rdlc with [FastReport Designer Community](https://github.com/FastReports/FastReport/releases/download/v2021.3.0/FastReport.Community.2021.3.0.zip). Just open file and select file type.
