### ISSUE TITLE
Toilet paper printing,and got the error

### ISSUE THREAD

**Issue by allen3371** [FastReports/FastReport#302]
i want to print on Toilet paper ,i fond the url 
https://www.fast-report.com/tr/blog/show/printing-on-toilet-paper/
but i got the error "paramentr is not valid"
mabe the image height is too large ,the image height is 332886

so how can i print on Toilet Paper?

thanks!

![image](https://user-images.githubusercontent.com/28289993/121481795-128ce880-c9ff-11eb-984e-c495318ec4cd.png)

**Comment by fediachov** [comment]
Hi,

You can't print with FastReport Open Source. This feature exists only in FastReport .NET https://www.fast-report.com/en/product/fast-report-net/
