### ISSUE TITLE
.Net Core Export Pdf File Size

### ISSUE THREAD

**Issue by yukseldemirtas** [FastReports/FastReport#304]
I am using fastreport for my .net core web api project.

I export pdf with pdfsimple in my .net core web api project, but the file size is too big
How can I provide a solution for this problem?

I am Using versions :
Fastreport.OpenSource 2021.3.1
Fastreport.OpenSource.Export.PdfSimple 2021.3.1
Fastreport.OpenSource.Web

**Comment by jeftegoesdev** [comment]
It's great because the community version of FastReport generates the pdf as if they were images inside the pdf.

It can be optimized, but it loses a lot of quality.

**Comment by fediachov** [comment]
The PdfSimple export is not very good because of its size and lack of text as there is a picture inside it.
If you have high requirements for the resulting PDF files, I recommend using FastReport .NET https://www.fast-report.com/en/fast-report-comparison/
