### ISSUE TITLE
how to run in asp.net mvc5?

### ISSUE THREAD

**Issue by neozhu** [FastReports/FastReport#306]
![image](https://user-images.githubusercontent.com/1549611/122209737-71f36880-ced7-11eb-9e62-61fdba82ed06.png)
![image](https://user-images.githubusercontent.com/1549611/122209791-80da1b00-ced7-11eb-940a-d9d259682a7f.png)
![image](https://user-images.githubusercontent.com/1549611/122209828-8a638300-ced7-11eb-8126-0b7bf7c6565c.png)

or not support .net framework , only for .net core , right?

**Comment by fediachov** [comment]
FastReport works fine in ASP.NET .NET5 
There is an example for .NET 5 https://github.com/fediachov/FastReportSamples/tree/master/PostgreSQL/dotnet-5

**Comment by neozhu** [comment]
thank you for revert, I'veve got it.
