### ISSUE TITLE
Excuse me ,How can I find these files

### ISSUE THREAD

**Issue by zhuhuanzi** [FastReports/FastReport#308]
![image](https://user-images.githubusercontent.com/26531688/123891829-140d5900-d98c-11eb-81d0-388983c8f63f.png)

**Comment by fediachov** [comment]
Hi,

This is FastReport Online Designer https://www.fast-report.com/en/product/fast-report-online-designer/

**Comment by ArmyMedalMei** [comment]
你买了就可以了哈

**Comment by ilivecoding** [comment]
开源的被移除了，现在要收费了。
