### ISSUE TITLE
Web Online Designer QrCode Show Bug

### ISSUE THREAD

**Issue by ArmyMedalMei** [FastReports/FastReport#309]
![image](https://user-images.githubusercontent.com/19337530/124533347-bcb43080-de44-11eb-95d9-3656b864da87.png)

**Comment by ArmyMedalMei** [comment]
no one?

**Comment by fediachov** [comment]
Hi,

Thanks for issue. We will fix this bug in next build of Online Designer.

**Comment by ArmyMedalMei** [comment]
> Hi,
> 
> Thanks for issue. We will fix this bug in next build of Online Designer.

OK,We are using it online, please repair it as soon as possible, thank you

**Comment by djak741** [comment]
Hi,
fix will be available soon

**Comment by MaratAlaev** [comment]
Hello!

At the moment, this problem is completely solved.

Best regards 
Marat
