### ISSUE TITLE
Line breaks on html export on Linux

### ISSUE THREAD

**Issue by WAmadeus** [FastReports/FastReport#31]
TextObjects containing linebreaks are correctly converted to &lt;br&gt; when exporting html on Windows, but on Linux they are missing.

The issue is on method "SplitToParagraphs", class "AdvancedTextRenderer", file TextRenderer.cs. It's not considering platform's linebreak.

**Comment by Detrav** [comment]
What is the line feed character in your system? FR uses the default LF as a line feed.

**Comment by tushroy** [comment]
@fediachov Wouldn't `text.Replace("<br>", "\r\n")` be considered with `text.Replace("<br>", Environment.NewLine)` to solve the issue on all platform?

**Comment by Detrav** [comment]
No, it isn't the problem. Our text engine is built on the \n symbol as line separator, it is made for compatibility of reports from different operating systems. 

For example, you create a report on the windows operating system or MacOS or Android or any other. The text is converted and stored in a universal form with a \n separator, it will allow to prepare a report on any operating system.

This method converts <br/> tags into our internal separator. After that, our engine breaks the text in rows.

```
// This line text is replaced
text = text.Replace("<br>", "\r\n");
// This line text is splitted
string[] lines = text.Split(new char[] { '\n' });
```

**Comment by WAmadeus** [comment]
> What is the line feed character in your system? FR uses the default LF as a line feed.

Windows uses CR+LF, Linux only LF

**Comment by WAmadeus** [comment]
> No, it isn't the problem. Our text engine is built on the `\n` symbol as line separator, it is made for compatibility of reports from different operating systems.
> 
> For example, you create a report on the windows operating system or MacOS or Android or any other. The text is converted and stored in a universal form with a `\n` separator, it will allow to prepare a report on any operating system.
> 
> This method converts `<br/>` tags into our internal separator. After that, our engine breaks the text in rows.
> 
> ```
> // This line text is replaced
> text = text.Replace("<br>", "\r\n");
> // This line text is splitted
> string[] lines = text.Split(new char[] { '\n' });
> ```

The problem is not the report itself but with strings build dynamically.

For example, I have a class's property getter that returns an address. The resulting string is build using StringBuilder.AppendLine("Street 1").AppendLine("City 1") that appends CR+LF on Windows and only LF on Linux. The report is exported correctly on Windows, but the same report on Linux doesn't have line breaks.

**Comment by Detrav** [comment]
That is why the internal separator from the FR does not go outside.

**Comment by Detrav** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/FastReports/FastReport/releases).

Thank you!

**Comment by marcianobandeira** [comment]
erro persiste FastReport.Utils.CompilerException: (153,103): Error CS0117: Please, don't use the method 'NewLine'

**Comment by KirillKornienko** [comment]
> continues with problem FastReport.Utils.CompilerException: (153,103): Error CS0117: Please, don't use the method 'NewLine'

Hello! It's ScriptSecurity: https://www.fast-report.com/en/blog/360/show/
Disable `FastReport.Utils.Config.EnableScriptSecurity` property

**Comment by marcianobandeira** [comment]
i disabled FastReport.Utils.Config.EnableScriptSecurity = false;
but, the error persists
FastReport.Utils.CompilerException: (153,103): Error CS0117: Please, don't use the method 'NewLine'

**Comment by KirillKornienko** [comment]
> i disabled FastReport.Utils.Config.EnableScriptSecurity = false;
> but, the error persists
> FastReport.Utils.CompilerException: (153,103): Error CS0117: Please, don't use the method 'NewLine'

Can you send your code?
