### ISSUE TITLE
How to cancel or configure the web online designer page refresh prompt?

### ISSUE THREAD

**Issue by ArmyMedalMei** [FastReports/FastReport#310]
![image](https://user-images.githubusercontent.com/19337530/125228001-7fe5af00-e306-11eb-8fe7-8e90881e6a70.png)

**Comment by djak741** [comment]
Try off confirm_before_exit checkbox in builder (available for registered users) or in build.json
![Clipboard - 13 июля 2021 г , 12 37](https://user-images.githubusercontent.com/87365466/125430072-f154ff51-b2ae-4ebf-ab04-26e6c2ffdceb.png)

**Comment by ArmyMedalMei** [comment]
> Try off confirm_before_exit checkbox in builder (available for registered users) or in build.json
> ![Clipboard - 13 июля 2021 г , 12 37](https://user-images.githubusercontent.com/87365466/125430072-f154ff51-b2ae-4ebf-ab04-26e6c2ffdceb.png)

Thank you very much
