### ISSUE TITLE
.Net 5 TypeLoadException: Could not load type 'System.Drawing.Design.UITypeEditor' from assembly 'FastReport.Compat, Version=2021.2.7.0

### ISSUE THREAD

**Issue by DanMburu** [FastReports/FastReport#314]
What could be causing this exception in .Net 5.0?

**Comment by zs-dima** [comment]
@DanMburu had you added libraries for the Docker container ?

```Docker
* * * 
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated --no-install-recommends \
        libgdiplus \
    && rm -rf /var/lib/apt/lists/*
* * * 
```

**Comment by fediachov** [comment]
Hi, 

Could you tell us more about your app's project type and the use of FastReport inside?

**Comment by zs-dima** [comment]
@fediachov looks libgdiplus library had not been installed in the to the Linux Docker container as I mentioned above.

**Comment by DanMburu** [comment]
The Project is .NET 5 ASP.NET Core App (MVC). Am running it on VS2019 (Windows 10).
I added FastReport via 

Install-Package FastReport.OpenSource
Install-Package FastReport.OpenSource.Web

Then on my controller

![image](https://user-images.githubusercontent.com/440412/126146630-48e38af1-7c22-4704-a5ef-ec67724f463a.png)

![image](https://user-images.githubusercontent.com/440412/126146683-8ed55753-0613-4831-8473-ef4b2f4cb468.png)

**Comment by DanMburu** [comment]
> @fediachov looks libgdiplus library had not been installed in the to the Linux Docker container as I mentioned above.

Am running on Windows 10 and not Linux

**Comment by zs-dima** [comment]
@DanMburu on Windows 10 as Windows application or as Linux Docker container ?

**Comment by DanMburu** [comment]
> @DanMburu on Windows 10 as Windows application or as Linux Docker container ?

As a web application ASP.NET Core MVC. Im currently runnning it directly from Visual Studio using IIS Express.

**Comment by KirillKornienko** [comment]
> > @DanMburu on Windows 10 as Windows application or as Linux Docker container ?
> 
> As a web application ASP.NET Core MVC. Im currently runnning it directly from Visual Studio using IIS Express.

Can you run `dotnet --list-runtimes` and attach it?

**Comment by DanMburu** [comment]
> dotnet --list-runtimes

![image](https://user-images.githubusercontent.com/440412/126243560-d62a32f8-1614-4fdb-b8aa-d82135205be7.png)

**Comment by KirillKornienko** [comment]
@DanMburu Update FastReport.Compat to 2021.2.10, this bug fixed.
