### ISSUE TITLE
Error setting height when barcode component type is EAN13

### ISSUE THREAD

**Issue by ArmyMedalMei** [FastReports/FastReport#321]
Error setting height when barcode component type is EAN13，Cancel auto size and set zoom to 1  After the height is set and saved, the height will automatically change to 2.5，The error report is shown in the figure
![QQ截图20210817145116](https://user-images.githubusercontent.com/19337530/129678285-47d2489f-6fff-42b8-815f-ad113e9c71ee.png)

**Comment by Alekarfes** [comment]
Judging by the screenshot, this seems to be related to the FastReport Online Designer and not FastReport Open Source. If this issue is still a problem for you, please create send us an example that we can use to recreate the issue to our support.
