### ISSUE TITLE
Microsoft.CodeAnalysis.VisualBasic version conflict

### ISSUE THREAD

**Issue by juchunwei** [FastReports/FastReport#324]
Could you please upgrade the Microsoft.CodeAnalysis.VisualBasic?  it shows error when build the project. 
Thanks!

Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.8.0 directly to project  to resolve this issue. 
 Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 5.0.8 -> Microsoft.CodeAnalysis.Razor 5.0.8 -> Microsoft.CodeAnalysis.Common (>= 3.8.0) 
  FastReport.OpenSource.Web 2021.3.30 -> FastReport.OpenSource 2021.3.30 -> FastReport.Compat 2021.3.0 -> Microsoft.CodeAnalysis.VisualBasic 3.3.1 -> Microsoft.CodeAnalysis.Common (= 3.3.1).

**Comment by KirillKornienko** [comment]
Please see #292
