### ISSUE TITLE
TextObject not Showing properly after CanGrow Property True (Attached Image)

### ISSUE THREAD

**Issue by VaskarBanerjee** [FastReports/FastReport#328]
Sir,

TextObject not resizing properly while CanGrow property true. Image attached.

![image](https://user-images.githubusercontent.com/71010132/133027122-8e928ab6-8025-4fdb-a619-e4c56ae18c3b.png)

**Comment by fediachov** [comment]
The CanGrow property must also be enabled on the band

**Comment by VaskarBanerjee** [comment]
CanGrow property also set True on Band. Screenshot attached.

![image](https://user-images.githubusercontent.com/71010132/133044840-90ebf724-aa42-4699-ac57-172477b1c401.png)

**Comment by 0legK** [comment]
Hi,

You also have to turn on GrowToBottom property of TextObject.

Best Regards,
Oleg.
