### ISSUE TITLE
Complete translation of "Portuguese (Brazil).frl" resources file, based on "Russian.frl"

### ISSUE THREAD

**Issue by EasyLOB** [FastReports/FastReport#329]
Hi

I just installed FastReport.Localization NuGet package, available with 2021.4 version:

https://opensource.fast-report.com/2021/09/fastreport-open-source-20214-release.html

But the "Portuguese (Brazil).frl" translation was still incomplete.
So, based on "Russian.frl" file, I included and translated the missing sessions:

Fonts
Functions
Cloud
Messaging
Web

Attached you find the file.

Thanks
[Portuguese (Brazil).zip](https://github.com/FastReports/FastReport/files/7202843/Portuguese.Brazil.zip)

**Comment by 0legK** [comment]
Hi,

We are going to check this localization file and include it in future builds. Thanks a lot.

Best Regards,
Oleg.
