### ISSUE TITLE
FastReports Free/Commerical "labeling" is confusing

### ISSUE THREAD

**Issue by danijelh** [FastReports/FastReport#331]
Hello team, 

can you update either WEB or GitHub so that it states if FastReport is FREE or COMMERCIAL and in which cases? 

The website currently states that there is no free version of FastReports for .NET while GitHub says otherwise.

Also, please help answer this question here.

Thanks in advance and best of luck!

**Comment by fediachov** [comment]
Hi, 
FastReport Open Source (this repo) is free with MIT license.
And we have commercial version with enhanced features and with own site https://www.fast-report.com/en/product/fast-report-net/
[
This is a comparison table of our generators in WEB, which shows that Open Source is free.](https://www.fast-report.com/en/fast-report-comparison/)
