### ISSUE TITLE
export pdf System.AccessViolationException

### ISSUE THREAD

**Issue by xyun52** [FastReports/FastReport#332]
two click export pdf button error

System.AccessViolationException:“Attempt to read or write protected memory. This usually indicates that other memory is corrupted.”

**Comment by fediachov** [comment]
We need more information about your project, operating system and used product. Did you use the project https://github.com/FastReports/FastReport/tree/master/Demos/OpenSource/PdfExport ?

**Comment by xyun52** [comment]
![动画](https://user-images.githubusercontent.com/5417624/141418744-dcd62672-dc3d-4434-a2a1-8ac4db11ff99.gif)
![image](https://user-images.githubusercontent.com/5417624/141418808-daa82d61-1752-4e77-b88c-a1f65f4a0ce0.png)

**Comment by fediachov** [comment]
This question goes beyond the Open Source product. It is about FastReport .NET code. Please send information about the bug to support@fast-report.com
Thank you!
