### ISSUE TITLE
Please add support for some additional HTML tags

### ISSUE THREAD

**Issue by adevelopery** [FastReports/FastReport#338]
TextObject currently supports only a small number, (6 or 7 different basic html tags.
Would be very useful to add support for some additional tags, at least <ul>,<li>,<p>,<br>.

**Comment by Detrav** [comment]
Hi, the list of tags is not visible, but I guess what this is about. TextObject is like `<p>` it should be used exactly as a paragraph.

For html there is an html object, I think the development team will tell you better here. IMHO, I am in favor of using the html object for complex html text.

**Comment by adevelopery** [comment]
Hi!
thank you for your explanation and help.
I have another question regarding FastReport OpenSource. I checked the documentation and demos on github and couldn't find an example how to register JSON with registerData. Is this possible actualy? I know it is possible from designer....

Can you please help me with the answer here or should I open another issue on git?
Regards,Ales
    On Wednesday, November 3, 2021, 02:27:31 PM GMT+1, Witaly Ezepchuk ***@***.***> wrote:  
 
 


Hi, the list of tags is not visible, but I guess what this is about. TextObject is like <p> it should be used exactly as a paragraph.

For html there is an html object, I think the development team will tell you better here. IMHO, I am in favor of using the html object for complex html text.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 8VAid8** [comment]
> Hi! thank you for your explanation and help. I have another question regarding FastReport OpenSource. I checked the documentation and demos on github and couldn't find an example how to register JSON with registerData. Is this possible actualy? I know it is possible from designer.... Can you please help me with the answer here or should I open another issue on git? Regards,Ales On Wednesday, November 3, 2021, 02:27:31 PM GMT+1, Witaly Ezepchuk ***@***.***> wrote: Hi, the list of tags is not visible, but I guess what this is about. TextObject is like <p> it should be used exactly as a paragraph. For html there is an html object, I think the development team will tell you better here. IMHO, I am in favor of using the html object for complex html text. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Hi! Check out this article - https://www.fast-report.com/en/blog/show/connecting-JSON-database/
