### ISSUE TITLE
PdfSimpleEport - Encoding of PdfInfo fields (Title,Subject,etc) is incorrect

### ISSUE THREAD

**Issue by mskinner-au** [FastReports/FastReport#343]
PdfInfo contains a number of fields that contain meta data about the document. These are displayed in the document properties of Acrobat, or the tab of a web browser (for Title). Currently the static fields (Creator and Producer) are being encoded as HEX values, but the public fields are not. The readers I have tried are not rendering this data correctly. My testing indicates that changing the public fields to also be HEX encoded resolves the issue (e.g. changing the setters to be `this[key] = new PdfString(value, true);`)

Examples of current rendering:
![image](https://user-images.githubusercontent.com/65928761/141030370-b98756f7-ad65-4cd8-b122-ea60a2e89cc4.png)
![image](https://user-images.githubusercontent.com/65928761/141030415-36470caa-aa26-4e15-9f44-9d1befebf6a6.png)

**Comment by ChristophSchlag** [comment]
The problem still exists in version 2025.1.0. The parts of PDFInfo are included in the pdf. with ‘/Title (/(\254\255 ...’. \254\255 should represent xFEFF and mark the content as UTF-16 BOM. Somehow this seems to be wrong.
Here is a C#-function that replaces the wrong characters. The file must then be saved via the memory stream.

`       PDFSimpleExport pdfExport = new()
       {
           Title = "My Title",
           Subject = "My Subject ",
           Keywords = "My Keywords",
           Author = "My Author"
       };

       MemoryStream pdfMS = new();
       report.Export(pdfExport, pdfMS);
       pdfMS = FixPdfBom(pdfMS);
       File.WriteAllBytes(pdffilePath, pdfMS.ToArray());`

`private MemoryStream FixPdfBom(MemoryStream pdfStream)
{
    byte[] pdfBytes = pdfStream.ToArray();
    string pdfText = Encoding.Latin1.GetString(pdfBytes);

    pdfText = pdfText.Replace(@"(\254\255", "(þÿ"); //þÿ = xFEFF

    // Zurück in den Stream schreiben
    return new MemoryStream(Encoding.Latin1.GetBytes(pdfText));
}`
