### ISSUE TITLE
Error in FastReport community

### ISSUE THREAD

**Issue by Severanin** [FastReports/FastReport#35]
Hello!
1. How to connect the parameter in the report in dotnet core 2.1 and FastReport community.
2. Error while executing the request
![untitled1](https://user-images.githubusercontent.com/17942764/48837036-1952a200-eda6-11e8-9074-f0eaca53ab55.png)
![untitled](https://user-images.githubusercontent.com/17942764/48837075-27a0be00-eda6-11e8-8466-80a68cc6543e.png)

**Comment by fediachov** [comment]
Hi! 
Thanks for issue request! We have an [updated version](https://github.com/FastReports/FastReport/releases/download/v2018.4.9/FastReport.Community.zip) the Designer Community Edition. Could you try it with your report?

[FastReport Community Edition 2018.4.9](https://github.com/FastReports/FastReport/releases/download/v2018.4.9/FastReport.Community.zip)

**Comment by Severanin** [comment]
It works great! Thank!
