### ISSUE TITLE
NET 6 support on Linux

### ISSUE THREAD

**Issue by volodin-danila** [FastReports/FastReport#360]
Hello, is NET 6 currently supported on Linux? If not, are there any plans in this regard? System.Drawing supports only Windows for NET 6.

**Comment by fediachov** [comment]
FastReport Open Source works fine on Linux with .NET 6 (with [libgdiplus](https://www.fast-report.com/en/blog/show/Building-libgdiplus-library-from-source/)). Or did you mean UI?

**Comment by fediachov** [comment]
We will work to support a different drawing engine

**Comment by volodin-danila** [comment]
Thanks for the detailed answer!
