### ISSUE TITLE
Set accessors of 'NavigatorTemplate' and 'OutlineTemplate' use the same backing field

### ISSUE THREAD

**Issue by VasilievSerg** [FastReports/FastReport#363]
Hello,

I found that set accessors of `NavigatorTemplate` and `OutlineTemplate` use the same backing field. 
Looks like `IndexTemplate` should use the `indexTemplate` backing field. :)

[Link](https://github.com/FastReports/FastReport/blob/dd337ea7c72fccb079db3d43f3a114f912e8bad6/FastReport.Base/Export/Html/HTMLExportTemplates.cs#L80).
![image](https://user-images.githubusercontent.com/10921236/145542476-013770cb-259e-4002-8734-6ea419f38f61.png)

**Comment by alexsherkhan** [comment]
This bug has been resolved.
