### ISSUE TITLE
 How can I set Text Object default [TID#656232]

### ISSUE THREAD

**Issue by ismailkocacan** [FastReports/FastReport#365]
The windows server 2019 standart editon small date format is "dd.MM.yyy"
Fastreport online designer text object's value is Date
Fastreport online designer text object's format is Date
but preview format is MM.dd.yyyy
How to configure (format) text object date time values globally ?

we use fastreport open source and .net core 5.

![FastReport1](https://user-images.githubusercontent.com/3339197/147544892-3adc8ee9-4480-4b5d-8754-cf6484bc199f.png)
![Fastreport2](https://user-images.githubusercontent.com/3339197/147544893-5557f410-5788-406b-a19e-c0d73aa1e94d.png)
![FastReport3](https://user-images.githubusercontent.com/3339197/147544894-e308438a-5fdb-4be5-9488-d0d799b4e197.png)

**Comment by Detrav** [comment]
FastReport uses format from [CurrentCulture](https://docs.microsoft.com/ru-ru/dotnet/api/system.globalization.cultureinfo.currentculture?view=net-6.0) by default.

As far as I know, there is no other way to set the global format.

**Comment by ismailkocacan** [comment]
> FastReport uses format from [CurrentCulture](https://docs.microsoft.com/ru-ru/dotnet/api/system.globalization.cultureinfo.currentculture?view=net-6.0) by default.
> 
> As far as I know, there is no other way to set the global format.

How can I change culture info ?
