### ISSUE TITLE
Error reading JSON data source

### ISSUE THREAD

**Issue by afr751116** [FastReports/FastReport#366]
Hello, I have a reference
https://www.fast-report.com/en/blog/show/connecting-JSON-database/
《How to create the connection to JSON database from the application code》
However, there is an error in the actual operation and the data source cannot be registered. Is there a more detailed example?
Code:

` WebReport entity = new WebReport();
            Report report = new Report();

            report.Load("wwwroot/FastReport/" + reportName + ".frx"); 
            RegisteredObjects.AddConnection(typeof(JsonDataConnection));
            JsonDataConnection conn = new JsonDataConnection();
            conn.ConnectionString = $"Json={itemPath}.json";
            conn.CreateAllTables();
            report.RegisterData(conn.DataSet);
            report.Dictionary.Connections.Add(conn);
          
            report.Prepare();
            entity.Report = report;

            entity.Mode = WebReportMode.Designer; 
            entity.DesignerLocale = "zh"; 
            entity.DesignerPath = "index.html"; 
            entity.DesignerSaveCallBack = "SaveDesignedReport"; 
            entity.Debug = true;
            entity.Width = "100%";
            entity.Height = "100%";`
![image](https://user-images.githubusercontent.com/57131579/147663182-40030448-47b8-4666-b3ec-dda3762ebd54.png)
Json:
`{"Id":"1101","Department":"13.10","Name":"张三","MobileOne":"11111111111","MobileTwo":"11111111111","Phone":"11111111111","Email":"11111111111@qq.com","PositionType":"1101","Birthday":"2021-08-01T10:18:25.557","SexType":0,"Address":null,"IdentityCard":null,"EntryTime":"2021-08-02T10:18:30.417","IDCard":"67564333","IsJobType":1}
`
![image](https://user-images.githubusercontent.com/57131579/147663204-04cd0df0-7da6-4232-a2e9-3afced09d134.png)

In the end < dictionary / > there is no data. What went wrong?
![image](https://user-images.githubusercontent.com/57131579/147663435-ac456069-0a7b-46fe-8b4c-b4c42a440cbf.png)

**Comment by Detrav** [comment]
I made an example, a little rough. https://github.com/Detrav/fros-json-demo
