### ISSUE TITLE
Error in JSON format

### ISSUE THREAD

**Issue by afr751116** [FastReports/FastReport#367]
The local JSON is used as the data source, but an error is reported. Why?

![image](https://user-images.githubusercontent.com/57131579/147721425-b1794007-5c07-4fbc-89ff-455cdb2669fc.png)

![image](https://user-images.githubusercontent.com/57131579/147721470-ab69a7dc-d013-419f-84b3-10bef7ba4e80.png)

![image](https://user-images.githubusercontent.com/57131579/147721483-93c9b7fd-ac7a-46d1-8346-a52c3cf16f97.png)

![image](https://user-images.githubusercontent.com/57131579/147721351-5839f541-e323-4f04-a653-dbe771a0f743.png)

![image](https://user-images.githubusercontent.com/57131579/147721377-fbf952a4-c31a-4ff8-a387-911023335f33.png)

**Comment by Detrav** [comment]
What version of .net are you using? What version of newtonsoft json?

It looks like the old json plugin doesn't support nullable fields, I need to check.

You can also try and use the new json connector builtin to FastReport.

**Comment by afr751116** [comment]
![image](https://user-images.githubusercontent.com/57131579/147725021-a9ec5e94-707f-4d58-adf0-af7bdf88eb05.png)
![image](https://user-images.githubusercontent.com/57131579/147725071-45a130ab-3e6c-443b-b81b-09c3dc137fc8.png)
.NET 5
How to use the new built-in JSON connector in FastReport? Are there any examples?

**Comment by Detrav** [comment]
I made an example, a little rough. https://github.com/Detrav/fros-json-demo
