### ISSUE TITLE
Connectionstring connection error

### ISSUE THREAD

**Issue by afr751116** [FastReports/FastReport#368]
I used connectionstring to link my API. Here is the code. And it can be tested with tools. But why is an error reported in the program? At the same time, there is no data in the dataset. Is my connectionstring wrong?

![image](https://user-images.githubusercontent.com/57131579/147893900-a6901499-7138-4eb4-ac08-09bc62799893.png)
![image](https://user-images.githubusercontent.com/57131579/147893904-b2ca56ed-bc84-434e-94e3-3a05f3c49be9.png)
![image](https://user-images.githubusercontent.com/57131579/147893907-47eb6fdd-6bce-49f7-9330-98de17594b85.png)

`conn.ConnectionString = $"Json=http://localhost:6698/api/services/app/Employee/GetAllList;Encoding=utf-8;Header0=Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiI1NDMyMDEzOTJAcXEuY29tIiwiQXNwTmV0LklkZW50aXR5LlNlY3VyaXR5U3RhbXAiOiJjNGI4OWY2YS03M2Y1LTUyNDUtOTZjZi0zOWZlMzdhZjY2NWIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly93d3cuYXNwbmV0Ym9pbGVycGxhdGUuY29tL2lkZW50aXR5L2NsYWltcy90ZW5hbnRJZCI6IjEiLCJzdWIiOlsiMiIsIjIiXSwianRpIjpbImMxNDA1NWFhLTlhYzItNDQ4OC05NDQ3LWU5YjhiYzBjNWQ0ZCIsImMzNzczZTQyLWQ5MjQtNGNjZi1iMWEzLTEwNDJmZjZiNjY0YyJdLCJpYXQiOlsxNjQxMTY3Nzc5LDE2NDExNjc3ODVdLCJodHRwOi8vYXV0aC41MmFicC5jb20vaWRlbnRpdHkvY2xhaW1zL1VzZXJOYW1lIjoiYWRtaW4iLCJodHRwOi8vYXV0aC41MmFicC5jb20vaWRlbnRpdHkvY2xhaW1zL0VtYWlsIjoiNTQzMjAxMzkyQHFxLmNvbSIsInRva2VuX3ZhbGlkaXR5X2tleSI6ImQ1MzdkZDY1LWIyOWUtNGQ3OC05YzVmLTRjMTIwOWVlMTk2ZSIsInVzZXJfaWRlbnRpZmllciI6IjJAMSIsIm5iZiI6MTY0MTE2Nzc4NSwiZXhwIjoxNjQxMjU0MTg1LCJpc3MiOiJZb3lvQ21zVGVtcGxhdGUiLCJhdWQiOiJZb3lvQ21zVGVtcGxhdGUifQ.Gg8AbvFtrOCLpNh8FNhOzJjI-Cv83pTKo1QJVBa8__0";`

**Comment by Detrav** [comment]
I made an example, a little rough. https://github.com/Detrav/fros-json-demo
If you have questions, make an another issue.
