### ISSUE TITLE
Error linking JSON file

### ISSUE THREAD

**Issue by afr751116** [FastReports/FastReport#369]
I want to directly use the local JSON file as the data source, but there is an error when linking the JSON file. My file code is UTF-8. How to solve it?
![image](https://user-images.githubusercontent.com/57131579/147894009-a96fb6d7-94ef-4958-8c36-4305f8ec67ae.png)
![image](https://user-images.githubusercontent.com/57131579/147894015-fa1ed6e3-7d2f-45b1-acf1-20a7474f598c.png)
![image](https://user-images.githubusercontent.com/57131579/147894037-a9de3739-7384-4f1d-abb1-275485d9fa8e.png)

**Comment by Detrav** [comment]
I made an example, a little rough. https://github.com/Detrav/fros-json-demo
