### ISSUE TITLE
Exporting PDF garbled code from online Designer

### ISSUE THREAD

**Issue by afr751116** [FastReports/FastReport#370]
Pdf garbled code is exported from online designer, and the WinForm designer has the function of embedding font. I don't know how to set it in online designer?
![image](https://user-images.githubusercontent.com/57131579/147907761-a23076f5-b331-421c-8276-3719f06c9c84.png)
![image](https://user-images.githubusercontent.com/57131579/147907771-48bef35e-91f4-4556-8ec5-dd187e91a54c.png)
![image](https://user-images.githubusercontent.com/57131579/147907779-6cb0e4ef-33ec-45e1-a19e-7c12dce6fccd.png)
![image](https://user-images.githubusercontent.com/57131579/147907787-7887770c-76f3-4574-92f0-5bd57f5129da.png)

**Comment by fediachov** [comment]
Try this solution https://www.fast-report.com/en/blog/show/Building-libgdiplus-library-from-source/

**Comment by fediachov** [comment]
Also you should add  next line in your csproj
`<PackageReference Include="system.drawing.common" Version="5.0.2" />`
same as in this example https://github.com/fediachov/FastReportSamples/blob/master/RHEL/frtest/frtest.csproj

**Comment by afr751116** [comment]
> 试试这个解决方案https://www.fast-report.com/en/blog/show/Building-libgdiplus-library-from-source/

Hello, I'm hosted by IIS. Like the screenshot, I added a font file and added it at @ font face. I don't know if this is correct, but it shows up and doesn't mess.
I think it's caused by the lack of online fonts. I don't know if there is a better way.

![image](https://user-images.githubusercontent.com/57131579/147931838-380750e0-98e8-493e-9a8e-140ba9bfe117.png)
![image](https://user-images.githubusercontent.com/57131579/147931873-1c5b3523-41cb-4278-80d9-4bfa5bad65f2.png)
![image](https://user-images.githubusercontent.com/57131579/147931926-9e7fe3c3-7dd1-40a5-9cb1-6b84fe822953.png)

**Comment by Detrav** [comment]
I don’t understand what exactly is happening, the wrong font is displayed in the pdf? Is font embedding is enabled.
Is the desired font works in the preview.

**Comment by afr751116** [comment]
> 我不明白到底发生了什么，pdf中显示错误的字体？是否启用了字体嵌入。 所需的字体是否在预览中有效。
When I don't put the font in the folder, my Chinese font will be automatically changed to "Arial", resulting in garbled code
![image](https://user-images.githubusercontent.com/57131579/148741559-2d259bad-a6c0-4457-a077-380faecd1a26.png)

**Comment by afr751116** [comment]
> I don’t understand what exactly is happening, the wrong font is displayed in the pdf? Is font embedding is enabled. Is the desired font works in the preview.

When I don't put the font in the folder, my Chinese font will be automatically changed to "Arial", resulting in garbled code
![image](https://user-images.githubusercontent.com/57131579/148741727-d152f411-86db-4110-8161-580bab0ff773.png)

**Comment by Detrav** [comment]
An article for using custom fonts in an online designer. https://www.fast-report.com/en/blog/show/custom-fonts-online-designer/
