### ISSUE TITLE
PDFSimpleExport - linux environment

### ISSUE THREAD

**Issue by adevelopery** [FastReports/FastReport#372]
I am trying to create a pdfexport from a simple fastreport report. PDF file is created but design is broken. Text in TextObject is not rendered properly. 
It seems like, when a TextObject contains only one letter or number, it is ok, otherwise there are some strange outlined squares rendered instead of text. (see example attached)
I am running project in visual studio 2022 , WSL (Ubuntu 18.04.2 LTS, libgdiplus v. 4.2.2)

![image](https://user-images.githubusercontent.com/5798414/148028626-817654f6-046a-490b-aafd-1c8489c7daea.png)

**Comment by evertonschuster** [comment]
Hello @adevelopery, did you find a solution?
Estou tendo o mesmo problema em servidores fedora apos a atualização para o dotnet 6

**Comment by alexsherkhan** [comment]
See here:
https://www.fast-report.com/en/blog/show/Building-libgdiplus-library-from-source/
