### ISSUE TITLE
FastReport.OpenSource.Export.PdfSimple on linux wordwrap property not work

### ISSUE THREAD

**Issue by dashenxian** [FastReports/FastReport#374]
FastReport.OpenSource.Export.PdfSimple version 2022.1.0
FastReport.OpenSource version 2022.1.0
os: uos
asp.net core3.1
when I run it on uos os system(linux)，wordwarp is not work,like this:
![image](https://user-images.githubusercontent.com/18696614/148199177-c2c31e52-f5db-4924-b1e4-19c4987e0d83.png)
![image](https://user-images.githubusercontent.com/18696614/148199319-1b4ce55e-43ba-494e-af09-7016bb8550ce.png)
but when I run it on windows os system,it works well
![image](https://user-images.githubusercontent.com/18696614/148199976-a456e030-11ea-42bb-a108-60ca209172e9.png)

**Comment by dashenxian** [comment]
After testing, the reason is 
System.Drawing.Graphics.Drawstring(string s, font, brush, brush, rectangle F, layoutrectangle, stringformat) 
format drawFormat. FormatFlags = 0; 
format. Trimming = StringTrimming.Word 
is not valid on Linux

**Comment by Detrav** [comment]
Hi! Most likely the problem is in libgdiplus on linux, you need to try to build it with pango manually. Here's an article.
https://www.fast-report.com/en/blog/show/Building-libgdiplus-library-from-source/

**Comment by dashenxian** [comment]
It's solved. Thank you very much
