### ISSUE TITLE
Export: Empty redundant odd pages

### ISSUE THREAD

**Issue by MrVitaly** [FastReports/FastReport#38]
## Versions
 - Fast Report:  Demos/FastReportWebCore.MVC fom the sources as is (Latest commit 664c4e9)
 - Browser: Google Chrome v. 70.0.3538.102 (64-bit), IE 11.407.17134.0, MS Edge 42.17134.1.0

## What happened
Printed documents contain redundant empty odd pages with note "`Generated by Fast Report.Net`" only.
For example: when I want to print the demo report "Simple list" which contains 3 pages, I get printed 7 pages when pages 2, 4, 6 contain required content and extra empty pages 1, 3, 5, 7.

### Steps to Reproduce
1. Run project "`Demos/FastReportWebCore.MVC.csproj`";
2. Select "`Simple list`" demo report;
3. Press "`Print from browser`" button;
4. See printed pages.

### Expected behavior
Printed document should contains 3 pages with required content only.

### Screenshots
 - What I try to print:
![fastreportissue_1](https://user-images.githubusercontent.com/7189888/48959034-d47c6600-ef73-11e8-8f21-b1a13a4ae1cd.png)

 - What I have as result:
![fastreportissue_2](https://user-images.githubusercontent.com/7189888/48959037-d80fed00-ef73-11e8-9558-35148169eb31.png)

**Comment by MrVitaly** [comment]
@fediachov, yes, problem still persist by provided link too.  `Print from PDF viewer` option works fine, but `Print from browser` option has the problem described  below (checked on two different PC in different browsers).
![fastreportissue_7](https://user-images.githubusercontent.com/7189888/49038657-99c23a00-f1ce-11e8-8333-ac0af32cb31f.png)

**Comment by fediachov** [comment]
The problem may be related to page size (A4 in example).

**Comment by MrVitaly** [comment]
You are right 👍 - the reason of the issue is value `Letter` in the `Paper size`  parameter (the value by default) instead of `A4`. After changing `Paper size` to `A4` the problem disappeared:
 - `Paper size` = `Letter`
![fr_1](https://user-images.githubusercontent.com/7189888/49236120-7f759f80-f40c-11e8-9b67-82ea4a0594b3.png)
 - `Paper size` = `A4`
![fr_2](https://user-images.githubusercontent.com/7189888/49236132-843a5380-f40c-11e8-8189-3b08a9308701.png)
