### ISSUE TITLE
report contains only empty pages

### ISSUE THREAD

**Issue by sf8321** [FastReports/FastReport#399]
hallo,
if i create a report i got only empty pages. if i debug the code and save the image
in method 
FastReport\Extras\OpenSource\FastReport.OpenSource.Export.PdfSimple\FastReport.OpenSource.Export.PdfSimple\PDFSimpleExport.Images.cs, private void DrawImage(RectangleF rectangleF, Bitmap image), line 54

with the degugger direct console (or so)
image.Save(@"C:\Temp\test.bmp") 

the image has the correct picture but in pnh format (irfanview says wrong it is png)

 method AppendPDFImage save it as jepg ? image.Save saves default png format what ever naming ?

where can i search the problem ?

**Comment by sf8321** [comment]
hallo,
i found the problem in my code

in an older Version i have to write this code to save the PDF
...
String pdf;
using (MemoryStream ms = new MemoryStream())
{
  report.Export(export, ms);
  pdf = Encoding.ASCII.GetString(ms.ToArray());
}
File.WriteAllText(DirectoryHelper.ToPlatformPath(sPdfDatei),pdf);

and this creates empty pages


but yet i have to write this 
report.Export(export, DirectoryHelper.ToPlatformPath(sPdfDatei));

ok it works

**Comment by sf8321** [comment]
hallo,
is the Encoding.ASCII.GetString the problem ? but when this is the problem why was it working in the past ! worked it in the past ?
do not known anymore. with report.Export(export, "test.pdf") it works and all is good.

**Comment by MaratAlaev** [comment]
Hello!

Can you describe in more detail what you want to do

best regards 
Marat

**Comment by sf8321** [comment]
Hello,
problem is solved as i described above (now i have no problem).

my old code was

String pdf;
using (MemoryStream ms = new MemoryStream())
{
report.Export(export, ms);
pdf = Encoding.ASCII.GetString(ms.ToArray());
}
File.WriteAllText("test.pdf",pdf);

my new code is ( and all works now)

report.Export(export, "test.pdf");

but i wonder why i have wrote i that way and not as it is.

was there an older release where this was right ? (this not important only for clarification)

**Comment by MaratAlaev** [comment]
has always been used in the documentation 
report.Export(export, "test.pdf");
or
pdf.Export(report, "test.pdf")
So I'm not sure
that this should work

Best regards 
Marat

**Comment by Detrav** [comment]
Do not read ASCII text from PDF, if you need to do it through a double buffer, then write an array of bytes through the [File.WriteAllBytes](https://docs.microsoft.com/ru-ru/dotnet/api/system.io.file.writeallbytes?view=net-6.0) method.

**Comment by sf8321** [comment]
hello,
i found the place here i have this examples from the unit tests

FastReport\FastReport\Extras\OpenSource\FastReport.OpenSource.Export.PdfSimple\FastReport.OpenSource.Export.PdfSimple.Tests\PdfSimpleExportTests.cs

namespace FastReport.Tests.OpenSource.Export.PdfSimple
{
    public class PdfSimpleExportTests
    {
        [Fact]
        public void ExportPdf()
        {
            Report r = new Report();
            r.LoadPrepared("TestReport.fpx");

            PDFSimpleExport export = new PDFSimpleExport();
            string pdf;

            using (MemoryStream ms = new MemoryStream())
            {
                r.Export(export, ms);
                pdf = Encoding.ASCII.GetString(ms.ToArray());
            }

...


but this is totaly wrong i have to use this code

...
        [Fact]
        public void TestExportWatermark()
        {
            Report r = new Report();
            r.LoadPrepared("Watermark.fpx");

            PDFSimpleExport export = new PDFSimpleExport();
            r.Export(export, "Watermark.pdf");
        }


i think have started with FastReport testing 2019 and there the things are different. Later i tested 2021 my code does not work anymore. looking for examples and i took the wrong example. thats all.
