### ISSUE TITLE
Exception in Config.cs,LoadPluginsInCurrentFolder:527

### ISSUE THREAD

**Issue by sf8321** [FastReports/FastReport#405]
hallo,

my problem is that i have and exception in Config.cs,LoadPluginsInCurrentFolder:527 because ApplicationFolder is empty because 
AppDomain.CurrentDomain.BaseDirectory is empty. i my pull request i have solved this with a new property that i can set before
new Report(). a new property because i do not what to change the original behavior. if no use the new property nothing is changed.

.....
        private static void LoadPluginsInCurrentFolder()
        {
            // find all plugin-connector in current directory
            var plugins = Directory.GetFiles(ApplicationFolder, "FastReport.Data.*.dll");

the other change is the assembly loading. i am in the situation

cpp program
dotnet 6.0 hosted
dotnet core plugin system started with 3.1 (use google github mc master plugin dotnetcore)
hotreload
reflectionContext (because i use reflection a lot inside the plugins)

in my copy of the code i removed all old targets and use only net6.0

i do not know if the FastReport Plugins can successfully loaded in this situation

        private static void LoadPluginsInCurrentFolder()
        {
            const string searchPattern = "FastReport.Data.*.dll";
.....
                 ProcessAssembly(Assembly.LoadFrom(pluginName));

**Comment by sf8321** [comment]
hallo,
in the FastReport.Compat i can create a new File/Class for the methods and use it in FastReport

LoadFromStream, LoadFromFile, LoadFromAssemblyName in dotnet core it is implemented like
...
if (AssemblyLoadContext.CurrentContextualReflectionContext != null)
{
    assembly =
        AssemblyLoadContext.CurrentContextualReflectionContext.LoadFromStream(asm);
}
else
{
    assembly = AssemblyLoadContext.Default.LoadFromStream(asm);
}
...
in all other versions
...
Assembly.Load(name); // or eqauls for stream, file, name, ...
....

**Comment by Alekarfes** [comment]
Hello, are you still experiencing this issue?

**Comment by sf8321** [comment]
Hello,
i use
 FastReport.Utils.Config.ApplicationFolder = .....;
before

Report report = new Report();

and all works as expected.



Am Mi., 31. Jan. 2024 um 11:16 Uhr schrieb Alekarfes <
***@***.***>:
