### ISSUE TITLE
Microsoft.CodeAnalysis.Common 3.3.1 X 4.0.0

### ISSUE THREAD

**Issue by EasyLOB** [FastReports/FastReport#412]
Hi,

When I include FastReport in .NET 5 ou .NET 6 projects I get the following message:

Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.0.0 directly to project MyLOB.Api to resolve this issue.
MyLOB.Api -> Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 6.0.2 -> Microsoft.CodeAnalysis.Razor 6.0.2 -> Microsoft.CodeAnalysis.Common (>= 4.0.0)
MyLOB.Api -> FastReport.Compat 2021.3.0 -> Microsoft.CodeAnalysis.VisualBasic 3.3.1 -> Microsoft.CodeAnalysis.Common (= 3.3.1).
    (+) Microsoft.CodeAnalysis.Common 4.0.1

It sound like FastReport.Compat references Microsoft.CodeAnalysis.Common (= 3.3.1) instead of (>= 3.3.1).
Could you change this in the next release ?

Thanks

**Comment by fencer** [comment]
How did you get to solve this?

**Comment by fencer** [comment]
> How did you get to solve this?

found the answer in #292

**Comment by EasyLOB** [comment]
Hi,
I referenced Microsoft.CodeAnalysis 4.0.1 directly in my Project.
This package references Microsoft.CodeAnalysis.CSharp.Workbench and .VisualBasic.Workbench, and so on...
