### ISSUE TITLE
postgresql  and obdc or plugin dll error

### ISSUE THREAD

**Issue by sak1065** [FastReports/FastReport#416]
## hi, i am using .netcore 5 framework and postgresql db version 13

i have web api and installed packages : 

![github](https://user-images.githubusercontent.com/6229889/157628653-4b3a6b7f-cdc6-454f-af00-887ccc93f818.PNG)

When I use odbc in my fastreport designs, I get an error on the api side, even though I define odbc on my server.

When I want to use fastreport as a plugin, I get npgsql.dll error 
and then i rebuild project from programfiles folder but postgresql doesn't support after version 9

I couldn't find anything about this topic.

thanks

**Comment by KirillKornienko** [comment]
Hi, see #292
