### ISSUE TITLE
The setting value of SVG angle for web page preview does not take effect, and the PDF preview effect is normal

### ISSUE THREAD

**Issue by ArmyMedalMei** [FastReports/FastReport#429]
![image](https://user-images.githubusercontent.com/19337530/163907208-728bdbdf-7c66-44bd-9c13-73cd5c5744f0.png)
The setting value of SVG angle for web page preview does not take effect, and the PDF preview effect is normal
![image](https://user-images.githubusercontent.com/19337530/163946458-688682a5-ebff-4b87-86fc-b95bd6cf60dd.png)

**Comment by MaratAlaev** [comment]
Hello!

I have created a task 

Best regards 
Marat

**Comment by KirillKornienko** [comment]
Hello! This bug was fixed
