### ISSUE TITLE
Direct Print

### ISSUE THREAD

**Issue by mojtabakaviani** [FastReports/FastReport#43]
Is there any plans to add support of Direct Print reports. this option allow use  in UWP apps.

**Comment by fediachov** [comment]
Thank for your request! We will think about it.

**Comment by EJLANDETAR** [comment]
The most recent versions already allow to print directly?

**Comment by marcosgerene** [comment]
@EJLANDETAR 
https://github.com/rftd/FastReport.OpenSource.Winforms
