### ISSUE TITLE
Exported PDF & Adobe

### ISSUE THREAD

**Issue by CoConutSyj** [FastReports/FastReport#430]
This is My .frx
![image](https://user-images.githubusercontent.com/38199371/166430853-893a2389-bee8-4b47-9d22-155031f10abe.png)
![image](https://user-images.githubusercontent.com/38199371/166430997-eaec6270-ac56-4d1c-ac12-849d21bbb741.png)
When I export the pdf，check the "Embedded Fonts" option，Open pdf with adobe，there is this prompt。
![image](https://user-images.githubusercontent.com/38199371/166431472-9faebd72-a8f0-4dc8-ac72-0cd3fd3ab219.png)

**Comment by CoConutSyj** [comment]
还有Out of Memory
![image](https://user-images.githubusercontent.com/38199371/166627424-3e95af1a-261b-4db1-87af-14440f79b74c.png)

**Comment by MaratAlaev** [comment]
Hello!

In the first case, the font most likely does not have these characters 
That's why they don't show up in the PDF. 

In the second case with out of memory
Try using the `UseFileStream` property


Best regards 
Marat
