### ISSUE TITLE
webapi how to use online designer

### ISSUE THREAD

**Issue by ilivecoding** [FastReports/FastReport#431]
use like this in mvc, but how to use in vue?

![图片](https://user-images.githubusercontent.com/7898334/167102225-e095a832-d518-4fd1-af87-102ecd0cf053.png)

![图片](https://user-images.githubusercontent.com/7898334/167102201-23fb3090-00e4-4161-ba5a-5ee161cf430c.png)

![图片](https://user-images.githubusercontent.com/7898334/167244633-fa16a244-5668-4ff6-9e51-983bf2e969ac.png)

**Comment by oniej** [comment]
I'm having the same issue

**Comment by ilivecoding** [comment]
oh, it need to pay.
