### ISSUE TITLE
How to setup a RavenDB connection in FastReport Designer Community Edition?

### ISSUE THREAD

**Issue by luis-fss** [FastReports/FastReport#442]
I copied "FastReport.Data.RavenDB.dll" to the installation folder and the option "RavenDB Connection" appeared in the dropdown of possible connection types, but I always get a NullReferenceException when I click the "Test Connection" button.

![image](https://user-images.githubusercontent.com/685069/172971171-dc5823b6-0216-49af-a07a-efadb4afc721.png)

**Comment by MaratAlaev** [comment]
Hello!

I will test the work of RavenDB 
If I can reproduce the problem 
I will solve the problem.

Best regards 
Marat
