### ISSUE TITLE
"Error in expression" exception hides the underlying exception

### ISSUE THREAD

**Issue by sandord** [FastReports/FastReport#447]
When an exception is thrown with the message "Error in expression", the underlying exception isn't passed as the inner exception but rather the underlying's exception inner exception, which often is `null`:

https://github.com/FastReports/FastReport/blob/ed95b9dcda4b1e7f802312db0138619eb78c1f14/FastReport.Base/TextObjectBase.cs#L463

Because of this, the actual cause of the "Error in expression"-exception is hidden and therefore not logged or inspectable by the host application.

I think this problem can be fixed by simply replacing `e.InnerException` with `e`:

    throw new Exception(Name + ": " + Res.Get("Messages,ErrorInExpression") + ": " + expression, e);

I had to spend a few hours to find out that I had a problem with parameter types while the exception suggested that one of my data field expressions were wrong. If I would've had access to the actual underlying exception, it probably would've been a breeze.

**Comment by MaratAlaev** [comment]
Hello!

Thank you 
I will inform the developer about it
And if there really is a problem 
We'll fix it. 

 

Best regards 
Marat

**Comment by MaratAlaev** [comment]
Hello!

Thank you for contacting me.
I have created a task 


Best regards 
Marat
