### ISSUE TITLE
Can't you add a new column after the total column of the crosstab?

### ISSUE THREAD

**Issue by afr751116** [FastReports/FastReport#448]
Hello, can you add new columns to the crosstab after the total column? My target format:
![image](https://user-images.githubusercontent.com/57131579/174938704-1b1633a2-9ded-4c3f-8704-087b0b040a3c.png)

But I can only do this at present. The next two new columns cannot be added
![image](https://user-images.githubusercontent.com/57131579/174938809-1b8031af-0880-4948-85fd-89ea9b26e0a4.png)
![image](https://user-images.githubusercontent.com/57131579/174938839-89a7b90d-e3a6-4068-bd35-198684ada7e2.png)

**Comment by MaratAlaev** [comment]
Hello!

We have already responded to your ticket
This is already being dealt with by our specialist
 

Best regards 
Marat
