### ISSUE TITLE
I could not create word file using FastReport in c#

### ISSUE THREAD

**Issue by akhmadjon1999** [FastReports/FastReport#449]
It took me 1 year to create a word file in .net core 3.1 using the FastReport.Export.OoXML.Word2007Export library. Now I can't create a word file in .net 6. Tell me, which nuget package can be created in .net 6 to create a word file?

**Comment by MaratAlaev** [comment]
Hello!

Could you please tell me in more detail
What is the problem with Word2007Export?
 

Best regards 
Marat

**Comment by akhmadjon1999** [comment]
I could not find nuget package working with word export in .net 6. In my
opinion not any nuget package for Fast Report word export in .net 6. But I
found nuget package for .net 5

**Comment by MaratAlaev** [comment]
Hello!

What product do you use?
FastReport .Core?

Best regards 
Marat
