### ISSUE TITLE
fast-report-online-designer Combination with local preview printing

### ISSUE THREAD

**Issue by afr751116** [FastReports/FastReport#450]
fast-report-online-designer At present, it can export PDF format and print it through Google Chrome, but in some cases, the printing is missing, such as Chinese. Is it considered to combine fast report online designer with local preview printing to transfer printing to local? For example, the preview print client is installed by the operator
![image](https://user-images.githubusercontent.com/57131579/176401625-14491cfd-3ffe-4233-99bf-d38bbb550ecd.png)

**Comment by MaratAlaev** [comment]
Hello!

We are in the process of reproducing this problem
I wrote about it in your ticket
We'll continue our communication there
 

Best regards 
Marat
