### ISSUE TITLE
PdfSimple: Text in result pdf is not selectable

### ISSUE THREAD

**Issue by TautFlorian** [FastReports/FastReport#452]
## Issue
Im trying out FastReport OpenSource in combination with the Open Source PdfSimple Plugin.
Unfortunately i cannot select words and copy them out of the generated pdf as its possible with any browser or adobe reader.

Is this a limitation of PdfSimple or a setting thing for the export?

## Code
```
Report rep = new Report();
rep.BaseReport = @"C:\users\taut\desktop\invoice.frx";

rep.SetParameterValue("InvoiceNr", 22080514);

if (rep.Prepare())
{
    PDFSimpleExport export = new PDFSimpleExport();
    rep.Export(export, @"C:\users\taut\desktop\Watermark.pdf");
}
```
## Result
[Watermark.pdf](https://github.com/FastReports/FastReport/files/9026484/Watermark.pdf)

**Comment by MaratAlaev** [comment]
Hello!

Yes, these are the limitations of PdfSimple 
because it exports everything in picture format

Best regards 
Marat
