### ISSUE TITLE
dorker环境部署，导出PDF，中文字符不换行。

### ISSUE THREAD

**Issue by easyson** [FastReports/FastReport#455]
1、docker环境下，已经安装中文字体，导出的表格，行高已经自动撑高了，但中文字符还是单行的，显示不全。英文字符正常换行。
![QQ20220713-0](https://user-images.githubusercontent.com/38804725/178623671-b3a55941-f067-48bb-ae9e-c71ecf64e465.png)

2、windows 环境下部署正常。

**Comment by xtanuiha** [comment]
最后咋解决的？
