### ISSUE TITLE
Have anyone use the HTML Object?

### ISSUE THREAD

**Issue by alanyu3517** [FastReports/FastReport#457]
how can i use html in html Object? even i put html in Edit Text
Thanks

FastReport .NET version 2022.2.0 Community Edition

![Fastreport-issue](https://user-images.githubusercontent.com/81033325/179913274-fcb5816f-c44a-466f-9a80-d2722462d487.png)

**Comment by alexsherkhan** [comment]
This is not a full-fledged HTML renderer. This is a text object with HTML tag support.
See here:
https://www.fast-report.com/public_download/docs/FRNet/online/en/UserManual/en-US/Fundamentals/ReportObjectsFundamentals/TextObjectFundamentals/HTMLTags.html

**Comment by alexdiegorocha** [comment]
Where is the "HtmlTags" property? Has it been removed?
