### ISSUE TITLE
.Net Join small pages missing in print options

### ISSUE THREAD

**Issue by fkbeys** [FastReports/FastReport#458]
I m trying to join small pages . But in .Net version, there is not a option for it. 
But in delphi version, it Is usable.
If the design file is Fr3, the join small pages option is visible.
On the other hand, if the design is frx, the join small pages option is invisible.
how can i solve this issue? I need to join small pages into one page.

**Comment by Alekarfes** [comment]
Greetings! FastReport .NET has an option to print like you want, but it's laid out differently.
![image](https://github.com/FastReports/FastReport/assets/46153199/8132d675-ccd5-4281-81fe-29a6357b79df)
What you're looking for is the "Scale" print mode. To print A4 on A3 you need to set the "Print on sheet" to A3 and "Pages on sheet" to your desired amount, like 2.

These options are accessed by clicking "More options" in the print dialogue.
