### ISSUE TITLE
Question: Possible to create a report with TableObject manually and entirely in application code?

### ISSUE THREAD

**Issue by githubfanster** [FastReports/FastReport#46]
Question: Possible to create a report with TableObject manually and entirely in application code?

I'm a complete newbie to FastReport.

After successfully creating a simple report entirely in code (see the CreateReport1() method used in HomeController.Index() in the attached HomeController file to be used as replacement for the one in FastReportWebCore.MVC.Controllers folder of the FastReportWebCore.MVC Demo project), I decided to try creating a report with a TableObject.

In the method CreateReportWithTableObject() in the HomeController.cs file mentioned above, I just want to print out the Header Row of Table1 as a starting point but am not able to.

All I get is the report title "My Table Object Report" and the Table1_ManualBuild(object sender, EventArgs e) event handler code is not getting called.

Is it possible to create a report with TableObject manually and entirely in application code?

Do I need to set my report's ScriptText property to something like the script I see in Table.frx??

What else might I be doing obviously incorrectly in the attached code??  
 
Thank you very much for any tips and help.

I've attached two files:  HomeController.cs  and SampleDataModel.cs (this one goes to the Models folder)
[Controllers.zip](https://github.com/FastReports/FastReport/files/2656364/Controllers.zip)

**Comment by Detrav** [comment]
Hi, use `ManualBuild` instead of `ManualBuildEvent` for `TableObject`, `ManualBuildEvent` only for the internal script in the variable `report.ScriptText`, when a report is created in the designer or for independent use, not in the code.

**Comment by Detrav** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/FastReports/FastReport/releases).

Thank you!
