### ISSUE TITLE
can not  get  the  online designer when i  follow your arcitle

### ISSUE THREAD

**Issue by DUWENINK** [FastReports/FastReport#465]
I follow this  [https://opensource.fast-report.com/2019/07/how-to-use-online-designer-with.html](https://opensource.fast-report.com/2019/07/how-to-use-online-designer-with.html)
But I get someting wrong 
![image](https://user-images.githubusercontent.com/16337239/183606424-d8ba1fac-96be-4325-a073-accb98775d65.png)

**Comment by Yamasiash** [comment]
This error is usually caused by an incorrectly specified route. Tell us more about the project, for example, what platform it is on, etc.

**Comment by MaratAlaev** [comment]
Hello!

You need to specify this in setupProxy.js:

```
const context = [
    "/Home",
    "/_fr",
    "/WebReportDesigner"
];
```

You also need to add Online Designer to the wwwroot of your project

and write this in the controller: 

```
WebReport webReport = new WebReport();

webReport.Mode = WebReportMode.Designer;
webReport.Width = "1000px";
webReport.Height = "1000px";

ViewBag.WebReport = webReport;
return View();
```


Best regards 
Marat
