### ISSUE TITLE
ReportPage Border not exporting when using PdfSimpleExport

### ISSUE THREAD

**Issue by ghost** [FastReports/FastReport#466]
Hi,
When using the PdfSimpleExport to export the report , the border of the reportpage is not getting exported
![image](https://user-images.githubusercontent.com/109153161/184182362-e40225fd-e346-4800-a119-dda518e54d75.png)

Can you please help with a workaround 
Thanks

**Comment by Yamasiash** [comment]
Could you please elaborate on the steps to reproduce the problem? Also let me know what OS you have.

**Comment by MaratAlaev** [comment]
Hello!

I informed the developers about this problem 
As soon as it is solved 

I will let you know

Best regards 
Marat

**Comment by BogdanStegachev** [comment]
Hello!

Our developers managed to solve the problem on your request, wait for the new version of FastReport.OpenSource

Best regards,
Bogdan
