### ISSUE TITLE
2022.2.0 这是什么问题

### ISSUE THREAD

**Issue by nm-1216** [FastReports/FastReport#467]
`Time:2022-08-29 11:07:30; Message:打印失败：(0,0): Error CS0006: 未能找到元数据文件“Microsoft.CSharp”`

模板打印 TableObject 不能给 name 赋值
模板中拼接公式 【】 中括号内不支持常量

在2021.2.0中这些都是好的

![image](https://user-images.githubusercontent.com/16759471/187115319-0486a999-926a-4c6c-bd0f-975686f2523d.png)

**Comment by Yamasiash** [comment]
Attach the test report and steps to reproduce the error.

**Comment by MaratAlaev** [comment]
Hello!

There has been no update on the issue

Best regards 
Marat
