### ISSUE TITLE
TableObject Sum(Cell6) Not Working in Community Designer 

### ISSUE THREAD

**Issue by githubfanster** [FastReports/FastReport#47]
I'm using the attached Csv file as Data Source for the attached productTable.frx Report Template.

when i preview the results in the Community Designer / Viewer, the Sum of all the values in the Price column is incorrectly showing as 0.

i'm building the report table dynamically, using the Table.frx example (my Script code is similar to that in Table.frx's Script Code).

What might I be doing incorrectly??  

Thanks for helping!
[CsvAsDataSourceTableObjectSumCellNotWorking.zip](https://github.com/FastReports/FastReport/files/2661514/CsvAsDataSourceTableObjectSumCellNotWorking.zip)

**Comment by githubfanster** [comment]
Thank you. That Worked.
How do I get the Table Header to get printed repeatedly for each new page?

In the designer, Table1 PrintOn property has RepeatedBand checked, in my SCriptCode,
i added:
 // printing the table header

      Cell1.PrintOn = PrintOn.RepeatedBand; //added
      Cell2.PrintOn = PrintOn.RepeatedBand; //added
      Table1.PrintRow(0);
      Table1.PrintColumns();

Couldn't get it to work.

Thanks for helping!
[HowToGetTableColumnHeadersToPrintRepeatedlyOnEachPage.zip](https://github.com/FastReports/FastReport/files/2662435/HowToGetTableColumnHeadersToPrintRepeatedlyOnEachPage.zip)
[HowToGetTableColumnHeadersToPrintRepeatedlyOnEachPage.zip](https://github.com/FastReports/FastReport/files/2662438/HowToGetTableColumnHeadersToPrintRepeatedlyOnEachPage.zip)

**Comment by githubfanster** [comment]
thanks. that worked. now i may have a different problem.

in the last page, i get only the table header and table footer printed with no data in between because there's no more data.

so it looks like this:

Name              Price
        Total:              2345678.90

Can I do better than this?  Just wondering  :-)

Any conditional capabilities I could explore?

Thank you so much for helping a newbie!

**Comment by fediachov** [comment]
Hi,

You can check the count of available rows and make the page brake from a code: table.PageBreak();
For example:
```csharp      
      int rowIndex = 0;
      while (rowData.HasMoreRows)
      {
        // print the table body  
        Table1.PrintRow(1);
        Table1.PrintColumns();        
        // check for table footer for last page
        if (rowData.RowCount - rowIndex < 3)
        {
          Table1.PageBreak();
          rowIndex = 0;
        }       
        // go next data source row
        rowData.Next();
        rowIndex++;
      }
```

**Comment by githubfanster** [comment]
thank you for the tip!
