### ISSUE TITLE
Переход с Microsoft SQL Server Reporting Services

### ISSUE THREAD

**Issue by FausT-VX** [FastReports/FastReport#471]
Добрый день!
На данный момент у нас на предприятии активно используется система отчетности Microsoft SQL Server Reporting Services. Более 500 различных отчетов, формируемых из баз данных компании преимущественно на СУБД MS SQL Server. C разграничением прав по группам отчетов (папка) и по отчетам, с NTLM авторизацией. **Планируем переход с MS Reporting Services на другую систему отчетности**, в связи с чем ведем поиск наиболее удобной в разработке и администрировании, а так же по простоте и скорости перехода (переноса имеющихся отчетов). 

**Что можете посоветовать из ваших разработок для наших целей?**

Основные требования:
1.	Сервис должен быть развернут на наших серверах.
2.	Сервис должен быть похож на Сервер отчетов от Microsoft по функционалу. Имеется в виду развертывание (публикация) отчетов на сервере отчетов/сайте/вэб-интерфейсе или же некий собственный клиент, с разграничение прав доступа по папкам (группам отчетов) и по отчетам. Отчеты должны быть интерактивными.
3.	Так же планируется переход на Linux сервера с СУБД MS SQL Server, и последним этапом перевод баз на СУБД PostgreSQL и рабочих станций с Windows на Linux. Соответственно на всех связках искомая система отчетности должна работать.

**Comment by Bykiev** [comment]
Здравствуйте, сразу скажу, что я обычный пользователь, не сотрудник компании FastReports.
Переход на продукты FastReports все равно приведет к необходимости правки всех отчетов, я попробовал открыть простой отчет SSRS с параметрами, не перенеслись параметры, источники данных (shared), многое придется править вручную.
Для ваших задач нужно использовать FastReport Corporate Server: https://www.fastreport.ru/ru/product/corporate-server/

**Comment by Yamasiash** [comment]
Yes, indeed. FastReport Corporate Server is a very good choice for your needs
