### ISSUE TITLE
WinForms is integrated for free in the OpenSource version?

### ISSUE THREAD

**Issue by matomosh** [FastReports/FastReport#474]
Hello,
I am interested in using FastReport but it is not clear to me if WinForms is integrated for free in the OpenSource version, on GitHub I find references to the functionality in FastReport/Demos/OpenSource/WinFormsOpenSourceViewer/
but in the comparison table "WinForms Applications" is not included for this version.

Thanks

**Comment by Yamasiash** [comment]
In fact, OpenSource itself does not support WinForms because it does not have Preview and Designer.
