### ISSUE TITLE
Replace System.Drawing.Common to SkiaSharp

### ISSUE THREAD

**Issue by lucas-pollus** [FastReports/FastReport#484]
Please consider updating the library to use SkiaSharp for Unix environments instead of System.Drawing.Common (native for Windows only). As of dotnet version 6 an exception is raised in Unix environments.

Ref: https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

**Comment by alexsherkhan** [comment]
This feature is only available in the paid version. Starting from version 2022.3.
See here:
https://www.fast-report.com/en/blog/show/fastreport-core-skia/

**Comment by alexsherkhan** [comment]
@scoroop unfortunately you are right on .NET 7 FastReport Open Source will only work on Windows

**Comment by SongOfYouth** [comment]
> This feature is only available in the paid version. Starting from version 2022.3. See here: https://www.fast-report.com/en/blog/show/fastreport-core-skia/

can the paid version work on wasm?

**Comment by alexsherkhan** [comment]
> > This feature is only available in the paid version. Starting from version 2022.3. See here: https://www.fast-report.com/en/blog/show/fastreport-core-skia/
> 
> can the paid version work on wasm?

Yes, read more here
https://www.fast-report.com/blogs/blazor-webassembly-manual
