### ISSUE TITLE
Replace System.Drawing.Common to Aspose.Drawing

### ISSUE THREAD

**Issue by alextnull** [FastReports/FastReport#494]
Please consider updating the library to use Aspose.Drawing for cross-platform usage instead of System.Drawing.Common.

> Aspose.Drawing is a fully managed, cross-platform, complete 2D graphic library for drawing text, geometries, and images. Aspose.Drawing provides System.Drawing compatible API, making it very easy for your existing code using System.Drawing to become truly cross-platform.

**Comment by Yamasiash** [comment]
We will consider replacing System.Drawing.Common with Aspose.Drawing. Thank you for helping us improve the product.

**Comment by Bykiev** [comment]
`SkiaSharp` is recommended by Microsoft

**Comment by Yamasiash** [comment]
We had a meeting and decided not to change System.Drawing.Common to Aspose.Drawing because the tool is not suitable because of product policy and it does not support printing.
