### ISSUE TITLE
`DesignerControl` sometimes doesn't show `code` & `page` tab

### ISSUE THREAD

**Issue by itsalongstory** [FastReports/FastReport#496]
![image](https://user-images.githubusercontent.com/1243202/200754922-5cf97dd8-2ee1-4f82-9110-6dc0dffb5f1b.png)

---

![image](https://user-images.githubusercontent.com/1243202/200755007-42215b3a-080a-42fa-ae80-7e0e2616e678.png)

After resize the window, the `code` & `page` tab will show up.

**Comment by Yamasiash** [comment]
Can you tell me the exact steps to reproduce the error?

**Comment by itsalongstory** [comment]
> Can you tell me the exact steps to reproduce the error?

@Yamasiash 

![image](https://user-images.githubusercontent.com/1243202/201239200-1244bab7-3507-4f7f-8629-837129a2b710.png)


```cs
        private void Form1_Load(object sender, EventArgs e)
        {

            string report_name_1 = "report 1.frx";
            string report_name_2 = "report 2.frx";
            string report_name_3 = "report 3.frx";

            this.treeView1.Nodes.Add(report_name_1);
            this.treeView1.Nodes.Add(report_name_2);
            this.treeView1.Nodes.Add(report_name_3);
           
        }

        private void treeView1_AfterSelect(object sender, TreeViewEventArgs e)
        {

            try
            {
                report.Load(this.treeView1.SelectedNode.Text);
                this.designerControl1.Report = report;
                this.designerControl1.RefreshLayout();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }
```

https://github.com/itsalongstory/fast-report-demo-issue

I've pushed a simplest demo repo to reproduce the error: select the reports in turn and see the behavior of the DesignerControl.

**Comment by itsalongstory** [comment]
> Can you tell me the exact steps to reproduce the error?

@Yamasiash @Pentium133 @mandrookin @daviddesmet 

Can you reproduce this error on your own computers?

**Comment by itsalongstory** [comment]
`designerControl1.UpdateUIStyle();`
