### ISSUE TITLE
The project introduction is free and open source, but the official website shows that it is paid. Do I have to pay if I use this project in a production environment?

### ISSUE THREAD

**Issue by wubingrong** [FastReports/FastReport#502]
The project introduction is free and open source, but the official website shows that it is paid. Do I have to pay if I use this project in a production environment?

**Comment by alexsherkhan** [comment]
If you use FastReport OpenSource, not to be confused with FastReport .NET/Core, then this [license](https://github.com/FastReports/FastReport/blob/master/LICENSE.md) applies to this product.
For the differences between FastReport OpenSource and FastReport .NET/Core, see the [link](https://opensource.fast-report.com/p/the-feature-comparison-table-for.html).
