### ISSUE TITLE
Abstract WebReportCache interface

### ISSUE THREAD

**Issue by MaximBalaganskiy** [FastReports/FastReport#529]
**Is your feature request related to a problem? Please describe.**
In hosted environments requests to FastReport controllers are not necessarily hitting the same instance.
In this case a singleton `WebReportCache` will not have a cached `WebReport` and report saving will fail.

**Describe the solution you'd like**
Abstract the report cache making it possible to create custom implementations. This will enable using Redis, for example, as a cache for multiple instances. Or better yet, use already existing `IDistributedCache` which already has plenty of existing implementations.

**Describe alternatives you've considered**
No real alternatives

**Comment by KirillKornienko** [comment]
Are you see the future?) We are currently working on this feature. The problem is that we don't have an access to user's DI container (because FastReport.Web doesn't register as a service, only as a middleware). We need to add this feature before we will implement IWebReportCache.

**Comment by MaximBalaganskiy** [comment]
Can I suggest that existing IDisttibutedCache is used instead of a custom one? The benefit is that it's standard and there many implementations already. The only difference with yours would be that you'll need to cache a serialised report, not an instance directly.

**Comment by MaximBalaganskiy** [comment]
As for the DI, it's quite easy to add controllers from a different assembly to the pipeline, you don't even need middleware for that
https://learn.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-7.0

**Comment by KirillKornienko** [comment]
We will support IDistributedCache as part of IWebReportCache, because we need to support legacy caching in one-server scenarios (this support will use IMemoryCache implementation also).

**Comment by MaximBalaganskiy** [comment]
The default IDistributedCache implementation uses IDistributedMemoryCache - ideal for dev and one-instance deploys

**Comment by KirillKornienko** [comment]
`MemoryDistributedCache` use serialization. It's a perfomance regression because every time when we need to use webReport instance we need to serialize/deserialize it. Also im not sure that we can correctly serialize state of webReport. This is yet to be tested.

**Comment by MaximBalaganskiy** [comment]
Fair enough

**Comment by KirillKornienko** [comment]
> As for the DI, it's quite easy to add controllers from a different assembly to the pipeline, you don't even need middleware for that https://learn.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-7.0

Thanks, i will read it soon
