### ISSUE TITLE
Concerns over SaveMethod technique in ASP.NET Core

### ISSUE THREAD

**Issue by MaximBalaganskiy** [FastReports/FastReport#530]
I'm a bit concerned regarding the usage of `SaveMethod` callback.
In a real-life scenario this callback will capture a controller reference.
If the controller allocated any resources, they won't be cleaned up until the `WebReport` is expelled from the cache.
Somehow, an idea that an old controller instance will be hanging around makes me uneasy.
Are there any alternatives to this report saving method?
I can modify the online designer code slightly to pass the report template to the iframe parent and handle saving from the SPA itself,
but would prefer an out of the box solution.

**Comment by Alekarfes** [comment]
Thank you for your suggestions, we will take a look at them.

**Comment by MaximBalaganskiy** [comment]
Have you found the time to look into this?

**Comment by BogdanStegachev** [comment]
Hello!

Thank you for your suggestion, we have created the task and passed it to the development department, this feature will be implemented in the next versions of FastReport OpenSource

Best regards,
Bogdan
