### ISSUE TITLE
Use FastReport Community  In Query Wizard show error character set 'utf8mb3' is not supported by net framework

### ISSUE THREAD

**Issue by pupss89345** [FastReports/FastReport#531]
MYSQL Version :8.0.30

In Query Wizard
show error character set 'utf8mb3' is not supported by net framework
![image](https://user-images.githubusercontent.com/11567878/208445208-aaf42ea0-15d0-44fe-adba-f076f0a06e6a.png)

But When I Create a new table Use utf8mb4 and select data it change error message :  Fatal error encountered attempting to read the resultset
![image](https://user-images.githubusercontent.com/11567878/208446091-5f2f6468-ca7c-488d-b0f0-9bf0a34906fd.png)

**Comment by dennisroy** [comment]
This issue can be solved by going to MySql.Data version 8.0.30 or above. It will require a new release from FastReports.

**Comment by rolosoftpy** [comment]
> This issue can be solved by going to MySql.Data version 8.0.30 or above. It will require a new release from FastReports. The problem is that both MySql and MariaDB are hard-coded to use utf8mb3 on the system databases. When the report designer makes calls to get the schema it has to query those system databases.

Do you remember the step to solve this issue? because I'm with Mysql 8.0.32 and FastReport 2023.1.0 and this problem still is a thing.

**Comment by dennisroy** [comment]
I don't think it can be solved until fast reports releases a new version of the community designer. Since the designer is not open source it will need to be rebuilt against MySql.Data version 8.0.30 or greater.

**Comment by pupss89345** [comment]
no solve yet, like @dennisroy said because the designer is not open source~ 
only wait new version ....

**Comment by Yamasiash** [comment]
Are you still encountering the problem on version 2024.1.3?

**Comment by pupss89345** [comment]
I've tried but The version 2024.1.3 show other error 🥲
<img width="379" alt="2024-01-18_09-35" src="https://github.com/FastReports/FastReport/assets/11567878/ea715397-7bf4-4b81-93ca-255a81e4103f">

**Comment by Alekarfes** [comment]
We've figured out the root issue and will soon release a version with this problem fixed.
