### ISSUE TITLE
Hello. An example related to Blazor.

### ISSUE THREAD

**Issue by petran53** [FastReports/FastReport#532]
Hello. Can you share an example about Blazor? An example related to Blazor server side and client side (WASM).

**Comment by petran53** [comment]
Hello. Can you share an example about Blazor? An example related to Blazor server side and client side (WASM).

**Comment by carlberg74** [comment]
Found this: https://www.fast-report.com/public_download/docs/FRNet/online/en/ProgrammerManual/en-US/Blazor/Preflight.html
It works, but I cant find any OpenSource version... 

Also, 
Using the official version, settings on the WebReport ex. ShowRefreshButton=false seem to have no effect.
Anyone else have tested this?

**Comment by petran53** [comment]
No, thanks for your help

**Comment by MaratAlaev** [comment]
Hello!

At the moment the developers are creating a demo for WASM

Best regards 
Marat

**Comment by ShamilS** [comment]
> Hello. Can you share an example about Blazor? An example related to Blazor server side and client side (WASM).

[Try this one](https://github.com/ShamilS/FastReport.Web.Blazor-DemoProject/tree/dotNet7) (forked from [KirillKornienko/FastReport.Web.Blazor-DemoProject](https://github.com/KirillKornienko/FastReport.Web.Blazor-DemoProject) and slightly edited to run with [.NET7](https://dotnet.microsoft.com/en-us/download))
