### ISSUE TITLE
MsSqlDataConnection not working

### ISSUE THREAD

**Issue by winsonet** [FastReports/FastReport#539]
**Describe the bug**
I am using asp.net core 6 for generating PDF from the fastreport, and use the ```FastReport.Data.MsSqlDataConnection``` , and just get the hang screen and find the pdf file size was continuously increasing, and the file was locking

**To Reproduce**

just use below codes

```
FastReport.Utils.RegisteredObjects.AddConnection(typeof(MsSqlDataConnection));
report.Load(Path.Combine("./reports", "Cities.frx"));

var mssqlDataConnection = new MsSqlDataConnection();
mssqlDataConnection.ConnectionString = _context.Database.GetConnectionString();
mssqlDataConnection.CreateAllTables();
report.Dictionary.Connections.Add(mssqlDataConnection);

var cities = _context.Cities.AsNoTracking().Take(5).ToList();
report.RegisterData(cities, "Cities");
report.Prepare();

 PDFSimpleExport pdfExport = new PDFSimpleExport();
pdfExport.Export(report, "Cities.pdf");
```
I created the `frx` report file with community report design tool and the data source is MSSQL database 

**Expected behavior**
Should be generate a PDF file

**Stacktrace**
There is no error and just keep reading and increasing the pdf file, so the screen was hang.

**Comment by winsonet** [comment]
Oh, I found that's my data issue, and acctually, it can't pass the data from coding and just get data from DB with frx file, so it get all of the data(a lot) and let the screen like hang :(

But why I can't pass data from coding to the report? and I also tried to pass the parameters and still not working, in the end, I need to use the `BusinessObjectDataSource` in the report to solve my problem

**Comment by winsonet** [comment]
Thanks for your reply! 

Yes, I think maybe there are a lot of data (over 40,000 records) and the report keeps generating data in the backend, so only the report hangs, but my question is why I can't pass the parameters for filter data? I just can use the fixed SQL in the report, so I have to change to use `BusinessObjectDataSource` to get data first

**Comment by BogdanStegachev** [comment]
Hello!

Please update your FastReport.Community to the current version

Best regards,
Bogdan
