### ISSUE TITLE
SQLiteConnection creation fails in FastReport.Community.2023.1.0

### ISSUE THREAD

**Issue by dvdsch** [FastReports/FastReport#541]
**Describe the bug**
In the latest free community version of the Designer the Data Wizard doesn't show any tables when creating an SQLite connection. The "Test connection" Button tells "Test connection succeeded" (see screenshots).

The version affected is 2023.1.0 (newest release at time of issue creation).

When trying the older version 2022.3.11 the tables show up (see screenshot).

The button "Add SQL query..." is also missing.

**To Reproduce**
1. Add a new SQlite data connection.
2. Click test connection. This should succeed.
3. Click on Next in the Data Wizard.
4. See error: No tables shown.

**Expected behavior**
The tables and the "Add SQL query..." button should show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/28543479/213883028-71bb803b-d6cd-4dc1-a5f1-ea3b7659e9ea.png)

![image](https://user-images.githubusercontent.com/28543479/213882851-2511d136-191c-434e-a979-ac5abe0f3915.png)

![image](https://user-images.githubusercontent.com/28543479/213882860-000986bc-08ec-4b58-8010-f1ed983d599e.png)

**Device**
 - OS: Windows 10 64 bit

**Additional context**
When creating a report in the older version, saving it, and executing it in the newer, the report generates. (But doesn't show tables when editing the connection.)

Example database file:
[test.sqlite3.zip](https://github.com/FastReports/FastReport/files/10472842/test.sqlite3.zip)
(Other files didn't work too.)

**Comment by Yamasiash** [comment]
Hello!

We were able to reproduce the problem. We will try to fix it as soon as possible.

Thank you for helping us improve our product!

**Comment by BogdanStegachev** [comment]
Hello!

In the current version of FastReport.Community your problem has been solved, we will wait for your feedback 

Best regards,
Bogdan

**Comment by dvdsch** [comment]
Hi!

Yes, it works now, thank you very much.

Best regards,
David
