### ISSUE TITLE
SQLLite programmatic creation fails

### ISSUE THREAD

**Issue by linusaurus** [FastReports/FastReport#549]
**Describe the bug**
Programmatically creating a Sqllite connection fails with null object error

**To Reproduce**
 FastReport.Report report = new FastReport.Report();
            FastReport.Data.SQLiteDataConnection reportConnection = new FastReport.Data.SQLiteDataConnection();
            string jobid = _selectedJob.jobID.ToString();
            reportConnection.ConnectionString = $"datasource = C:\\DB\\{jobid}.db";
            
            report.Load($"{Application.StartupPath}/JobAnalysis.frx");
            report.Dictionary.Connections[0].ConnectionString = reportConnection.ConnectionString;

            report.Show();

**Expected behavior**

**Stacktrace**
![image](https://user-images.githubusercontent.com/8205460/218512076-9667c729-8dfc-4620-9e4f-69157f48198e.png)

**Screenshots**

**Device (please complete the following information):**
 - Windows 10  Build 19045
 - Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Additional context**

**Comment by conqu1stador** [comment]
Could you send the call stack please?

**Comment by BogdanStegachev** [comment]
Hello!

Please update your FastReport.Community to the current version

Best regards,
Bogdan
