### ISSUE TITLE
SQLite connection in Designer

### ISSUE THREAD

**Issue by VladislavChastnokov** [FastReports/FastReport#557]
I'm adding SQLite data source into a new report, .db3 database, connection test is successful, but when i hit Next there aren't any tables and no SQL query option. Any help?
![1](https://user-images.githubusercontent.com/15748715/222892820-ca2f5da1-ccff-4e78-b4bb-d6a13a4d7245.jpg)
![2](https://user-images.githubusercontent.com/15748715/222892828-19b7ac67-f858-4f45-b665-e3172b3430f2.jpg)

**Comment by DeRoJo85** [comment]
I have exactly the same problems with a MariaDB. The connection is made as usual via the MySQL driver, but no tables are displayed...

**Comment by BogdanStegachev** [comment]
Hello!

In the current version of FastReport.Community your problem has been solved, we will wait for your feedback

Best regards,
Bogdan
