### ISSUE TITLE
Database connect hand in retrieving database infomation

### ISSUE THREAD

**Issue by hks2002** [FastReports/FastReport#559]
**Describe the bug**
My database MS 2016 has more than 1000 tables,

FastReport.Community.2023.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8808496/222940980-d628bd6a-bcff-4297-bef9-2a38ecff80a1.png)

**Comment by BogdanStegachev** [comment]
Hello!

In the current version of FastReport.Community your problem has been solved, we will wait for your feedback

Best regards,
Bogdan

**Comment by BogdanStegachev** [comment]
Hello!

Please update your FastReport.Community to the current version

Best regards,
Bogdan
