### ISSUE TITLE
export to docx

### ISSUE THREAD

**Issue by badre429** [FastReports/FastReport#56]
Is there a plans to add support of word( Docx) or Excel export format ?

**Comment by Detrav** [comment]
Hello, this functionality is already exists in the paid version of FR. Export to Word (DOCX, RTF), Excel (XLSX, XLS (Biff8)) and many other features can be found in the [comparison table](https://fastreports.github.io/FastReport.Documentation/COMPARISON.html). At the moment we are not going to add these features to the OpenSource project.
