### ISSUE TITLE
Shape Object could over more than one band

### ISSUE THREAD

**Issue by hks2002** [FastReports/FastReport#561]
**Describe the solution you'd like**
I am thinking to change my CrystalReport to FastReport, Now I found a very big problem on the report design.
CsystalReport support shape over more then one area/band, it is very nice feature, when you do report design.
![image](https://user-images.githubusercontent.com/8808496/223020921-b6004647-0c8b-4e64-87b3-0382cdd34e83.png)
I can draw a retangle and serval lines very easy, But in FastReport，you can not, you must draw lines in very band, and you need spend much time to let each line align vertically, as the band more as difficult more.
![image](https://user-images.githubusercontent.com/8808496/223021545-58169267-57d4-49e3-a0cc-38d83c626c78.png)

**Comment by Alekarfes** [comment]
Aligning lines vertically can be easy if you use the object inspector and set the values manually. Also, I would highly recommend using a TableObject for this purpose, and not a collection of lines.
