### ISSUE TITLE
Support to firebird

### ISSUE THREAD

**Issue by marcelokrol** [FastReports/FastReport#57]
Is this open source version, or will it have support for the firbird database?

**Comment by Detrav** [comment]
Hi, yes, this is an open source version :smiley:

Do you mean [`Firebird`](https://firebirdsql.org/)? Yes it is possible to add a connector to the Firebird. We will add this plugin. If someone wants to make a connector it will be a good and very simple first issue and we will be happy to approve pull request.

**Comment by viegasfh** [comment]
Hi!

I can't seem to find an implementation of this feature request. Therefore, I volunteer myself to implementing the connector, if someone hasn't already planned it.

**Comment by lbuczko** [comment]
Maybe this will help to fix the problem:
-  https://github.com/lbuczko/FastReport-Community-Firebird-addin

**Comment by fediachov** [comment]
https://github.com/FastReports/FastReport/tree/master/Extras/Core/FastReport.Data/FastReport.Data.Firebird
