### ISSUE TITLE
Error when trying to change the layout of the report

### ISSUE THREAD

**Issue by rodrigomartins2** [FastReports/FastReport#571]
**Device (please complete the following information):**
 - OS: Windows 11 Home
 - Version 22H2

But the designer of the reports I can't move yet.

Follow images
![image](https://user-images.githubusercontent.com/65425899/228280851-2f777609-4c27-4308-9ff8-8b7d8ec88713.png)

I can view the data but I can't edit it
![image](https://user-images.githubusercontent.com/65425899/228280963-ccdf370d-8501-4c49-a6bc-63e08ba3c6dd.png)

The problem seems to be the zoom that is coming with too much.
![image](https://user-images.githubusercontent.com/65425899/228281068-215bd2a0-de06-4b56-80e1-b08e3155ba9e.png)

But when trying to reduce the designer appears, but it crashes when I try to change the layout
![image](https://user-images.githubusercontent.com/65425899/228281140-1f636ab1-f17b-4621-ad28-20b6195c5e38.png)

**Comment by rick4bsl** [comment]
Hi, 
its some error in the config file

_C:\Users\<YOUR USER NAME>\AppData\Local\FastReport\FastReport.Community.config_

if you delete it and restart the programm it should work.
The file recreates after every closing of the programm.

Greets Patrick

**Comment by rodrigomartins2** [comment]
Problem solved!

Thank you for your help!
