### ISSUE TITLE
Can't drag and drop components in Fast Report Community, v.2023.2.0

### ISSUE THREAD

**Issue by matheussanton** [FastReports/FastReport#574]
**I've created a .frx file and it broke fast report at all**

Hi, I'm working for the first time using fast report and today I tried to use C# in order to generate a .frx file with a data source already fixed (using RegisterBusinessObject). I've used the following code:

  

>private  string  SaveReportLocalPath(DailyReportInformations  report)
{
var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"Templates\AccountingDaily.frx");
var freport =  new  FastReport.Report();
freport.Dictionary.RegisterBusinessObject(new List&lt;DailyReportInformations> { report }, "accountingDaily", 10, true);
freport.Report.Save(filePath);
return filePath;
}

  You can download the file here:
  https://drive.google.com/file/d/1OCEvHDYsfQl5qHC0yGnR1kvQDpuD1pKU/view?usp=share_link

It generates a .frx file with the following Dictionary (opening it with notepad++):

![Dictionary](https://i.ibb.co/k00KwjM/image.png)

You can follow this image for analysis.
![Tree](https://i.ibb.co/wcKZY5w/image.png)

**So, what's the problem?**

The problem is that after opening this file in Designer.exe the Drag and Drop feature brokes, it doesn't matter what you do after that, you can delete FastReport folder, download it again and the problem still there..

Drag and drop, for example, 'PageN' into the board, it'll place the component into a random position and it become invisible and unusable!

**I've tried:**
- Reboot the PC
- Uninstall and install again
- Install other versions (with my tests in other machines, the problem only occurs if I start with version 2023.2.0,
in one of my test cases, I first tried the version 2022.2.0 and the problem didn't occured, so I assume the problem is with the latest version of the tool).

**How to reproduce?**

1. Using C#, generate a .frx file registering it's RegisterBusinessObject with a class and save it locally (see first lines).
2. Download the version 2023.2.0 of Fast Report Community (https://github.com/FastReports/FastReport/releases/tag/v2023.2.0)
3. Unzip the download
4. Open Designer.exe
5. At Designer, open the generated file, in my code example, called "AccountingDaily.frx".

**Package and Project versions:**
- Fast Report Community: 2023.2.0 (link above)
- FastReport.OpenSource:  2023.2.4 (dotnet add package FastReport.OpenSource --version 2023.2.4)
- FastReport.OpenSource.Export.PdfSimple: 2023.2.4 (dotnet add package FastReport.OpenSource.Export.PdfSimple --version 2023.2.4)
- FastReport.OpenSource.Web: 2023.2.4 (dotnet add package FastReport.OpenSource.Web --version 2023.2.4)

**How can I have my FastReport working normally again? Does I need to format my SSD?**

Thank you all in advance. :)

**Comment by sabinosabino** [comment]
Eu também tenho o mesmo problema

**Comment by matheussanton** [comment]
> Eu também tenho o mesmo problema



> I have the same problem. It didn't work even going back to the previous version.


The only way that worked for me was to format my machine and download a previous version

**Comment by HenriqueFelixDev** [comment]
I solved the problem by changing the `snap size` property from 25 cm to 0.25 cm in View > Options... > Report Page

**Comment by Gabriel-Guimaraes** [comment]
I am having the same problem, and the only working solution is deleting the FastReport.Community.config file as mentioned by @vercom , or going to View > Options > User Interface and clicking 'Reset config'. After restarting the designer, the report becomes editable again. However, upon closing and reopening it, the issue reoccurs, and it is necessary to repeat the same steps.

**Comment by rcoelhao** [comment]
Thank you it works for me!

**Comment by AlonsoLucasls** [comment]
> I solved the problem by changing the `snap size` property from 25 cm to 0.25 cm in View > Options... > Report Page

work for me.

**Comment by fredribeirov** [comment]
> I am having the same problem, and the only working solution is deleting the FastReport.Community.config file as mentioned by @vercom , or going to View > Options > User Interface and clicking 'Reset config'. After restarting the designer, the report becomes editable again. However, upon closing and reopening it, the issue reoccurs, and it is necessary to repeat the same steps.

Thank you it works for me

**Comment by Tilli69** [comment]
> I solved the problem by changing the `snap size` property from 25 cm to 0.25 cm in View > Options... > Report Page

u save my day

**Comment by BogdanStegachev** [comment]
Hello!

To solve your problem please upgrade your FastReport.OpenSource to the current version and then follow the steps:
View -> Options -> Reset config 
after clicking on Reset config please restart your FastReport.OpenSource completely

Best regards,
Bogdan
