### ISSUE TITLE
NU1107 Version conflict Microsoft.CodeAnalysis 3.3.1

### ISSUE THREAD

**Issue by SchreinerK** [FastReports/FastReport#577]
**Describe the bug**
NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common.
 MyProject -> 3rdProject -> Microsoft.CodeAnalysis.CSharp 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0) 
 MyProject -> FastReport.OpenSource 2023.2.7 -> FastReport.Compat 2023.1.8 -> Microsoft.CodeAnalysis.VisualBasic 3.3.1 -> Microsoft.CodeAnalysis.Common (= 3.3.1).	

Install/reference Microsoft.CodeAnalysis.Common 4.5.0 :
Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.VisualBasic 3.11.0 requires Microsoft.CodeAnalysis.Common (= 3.11.0) but version Microsoft.CodeAnalysis.Common 4.5.0 was resolved.

1. create a .NET 6 project which depends on Microsoft.CodeAnalysis.Common 4.5.0 
2. install FastReport.OpenSource 2023.2.7

**Expected behavior**
Nuget package can be loaded w/o conflict

**Device**
 - OS: Windows 11

**Comment by KirillKornienko** [comment]
Please, see #292
