### ISSUE TITLE
Error 500 -System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by binli123-max** [FastReports/FastReport#578]
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') at FastReport.Web.WebReport.GetReportPageWidthInPixels() at FastReport.Web.WebReport.ReportInHtml() at FastReport.Web.WebReport.template_body(Boolean renderBody) at FastReport.Web.WebReport.template_render(Boolean renderBody) at FastReport.Web.WebReport.Render(Boolean renderBody) at FastReport.Web.Services.ReportService.GetReport(WebReport webReport, GetReportServiceParams params) at FastReport.Web.Controllers.ReportController.<.ctor>b__0_0() at FastReport.Web.Controllers.BaseController.OnRequest(HttpContext httpContext) at FastReport.Web.FastReportMiddleware.RequestFastReportController(HttpContext httpContext) at FastReport.Web.FastReportMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context) HEADERS ======= Accept: */* Host: localhost:7019 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 :method: POST Accept-Encoding: gzip, deflate, br Accept-Language: zh-CN,zh;q=0.9 Cookie: street=1,street_area=1%2C3409,session_id_ip=0.0.0.0_11910925485cb9a8895b8880ebef7f76,_med=dw:1280&dh:720&pw:1920&ph:1080&ist:0,isg=BPLyKXf2wifG8f4bjer8kiFVQzjUg_YdcZapZ7zLIKWQT5JJpBFXL33uP-tzP261,province=25,city=321,district=0,ECS_ID=fd444944e80386dd699fcd036c772475a70d11c9,ECS[visit_times]=2,ECSCP_ID=38d082172c052809095ca4e0613d5c1c51bf27ac,adminStartHome=cookieValue,ECS[history]=944,ECS[list_history]=944,dscActionParam=menushopping%7C02_order_list,dscUrl=order.php%3Fact%3Dinfo%26order_id%3D14 Origin: https://localhost:7019 Referer: https://localhost:7019/Report/Preview?Id=123&sourceId=123.json Content-Length: 0 sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111" sec-ch-ua-mobile: ?0 sec-ch-ua-platform: "Windows" sec-fetch-site: same-origin sec-fetch-mode: cors sec-fetch-dest: empty

**Comment by BogdanStegachev** [comment]
Hello!

Could you please install the current version of FastReport.OpenSource 2023.3.0 and let us know on which of the demo applications this error is reproduced

Best regards,
Bogdan

**Comment by binli123-max** [comment]
您好，我是李斌！您的邮件，已收到！

**Comment by BogdanStegachev** [comment]
Hello!

This problem is not reproduced on the latest version of FastReport.OpenSource

Best regards,
Bogdan

**Comment by binli123-max** [comment]
您好，我是李斌！您的邮件，已收到！
