### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by tombradev** [FastReports/FastReport#58]
Good afternoon, 

I am looking for alternative to crystal report, I am wondering if anyone has used this fast-report for their projects able to share their experience. What is the performance of FastReport in your apps?

Thank you

**Comment by Gandalf361** [comment]
Hello.
Unfortunately, I did not measure performance in my applications. But according to my feelings, the FR is much faster than in Crystal reports. I once worked with it. It was a nightmare. Therefore, I strongly recommend you to try FR.
Here I found an article on this topic:
https://www.fast-report.com/en/blog/100/show/
