### ISSUE TITLE
Support cancellation tokens in FastReport.Prepare

### ISSUE THREAD

**Issue by MaximBalaganskiy** [FastReports/FastReport#581]
**Is your feature request related to a problem? Please describe.**
Sometimes background report generation needs to be cancelled, for example, when SQL is slow.

**Describe the solution you'd like**
I would like to pass `CancellationToken` to `FastReport.Prepare`. It would be a non-breaking change if you default the parameter to `CancellationToken.None`.

**Describe alternatives you've considered**
I see that there's an `Abort` method but the docs don't have any examples on how to properly use it or if it's thread safe.
I suspect that `Abort` only cancels the report generation but not the DB query.

**Comment by conqu1stador** [comment]
Hello, what about `PrepareAsync`? It has a CancellationToken in params

**Comment by MaximBalaganskiy** [comment]
This method is in the sources but not in the nuget package.

**Comment by MaximBalaganskiy** [comment]
@Alekarfes cpuld you please add a link to the commit which resolves this?
