### ISSUE TITLE
Wrong Barcode when using HTML Export

### ISSUE THREAD

**Issue by DavidCFreire** [FastReports/FastReport#589]
**Wrong Barcode when using HTML Export**
I'm using 2/5 interleaved barcode, if i use ImageExport it's okay, but when i use HTML Export i can't read the barcode generated and it's visual noticible that the barcode changed from Image Export to HTML Export.

**To Reproduce**
1. Make an report with 2/5 interleaved barcode
2. Run a image export
3. Run a HTML export
4. Compare the two generated barcode
5. Try read the barcode

**Device:**
 - OS: Windows
 - WPF Project
 - Using the latest version of Fast Report OpenSource 2023.2.12

**Comment by BogdanStegachev** [comment]
Hello!

Reproduced your problem, created a task and passed it to the development department

Best regards,
Bogdan
