### ISSUE TITLE
How to Add a GraphicPath object on FastReport.NET 

### ISSUE THREAD

**Issue by Kemeni** [FastReports/FastReport#59]
I have been searching how to do this for long but i couldn't get a support please for help

**Comment by Detrav** [comment]
You will be interested in how [PolyLineObject.cs](https://github.com/FastReports/FastReport/blob/master/FastReport.Base/PolyLineObject.cs) is made. You can make your own or use this one. At the moment we have no api which would allow adding you own GraphicsPath. But you can add one point at a time to this object.

```
polylineObject.AddPointToEnd(xPos, yPos);
```

**Comment by Detrav** [comment]
It seems that the API that allows you to change GraphicsPath for Polyline and Polygon is not part of OpenSource. 😨 I guess we will add something to add you own GraphicsPath.

**Comment by Detrav** [comment]
There is a new function `PolylineObject.SetPolyLine(PointF [] newPoints)` which allows you to set the path for a polyline or polygon objects.
