### ISSUE TITLE
Given Parameter not working

### ISSUE THREAD

**Issue by salmanshafiq00** [FastReports/FastReport#599]
I am using FastReport Opensource edition. I design a report with simple query,

SELECT *
FROM [Identity].Users
WHERE Id = @id

Define a parameter by name id.

then in controller action write following code:

                await Task.Delay(0);
                FastReport.Utils.Config.WebMode = true;
                Report report = new();
                var mssqlConnection = new MsSqlDataConnection();
                mssqlConnection.ConnectionString = _config.GetConnectionString("DefaultConnection");
                report.Dictionary.Connections.Add(mssqlConnection);
                string path = $@"{_env.WebRootPath}\reports\personalData.frx";
                report.Report.Load(path);
               var loginUserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                report.SetParameterValue("id", loginUserId);
                if (report.Report.Prepare())
                {
                    PDFSimpleExport pdfExport = new()
                    {
                        ShowProgress = true,
                        Subject = "User Personal Data",
                        Title = "User Personal Data"
                    };
                    using MemoryStream ms = new();
                    report.Report.Export(pdfExport, ms);
                    report.Report.Dispose();
                    pdfExport.Dispose();
                    ms.Flush();
                    return File(ms.ToArray(), "application/pdf", "personal-data.pdf");
                }

Problem is that, if I am using parameterized query report, any data not showing in the report But I use simple query without filter that works fine. What should to do now?

![ff](https://github.com/FastReports/FastReport/assets/103124821/9e5ea0fb-fde7-4ed2-bea3-32c8527a2a24)
![fff](https://github.com/FastReports/FastReport/assets/103124821/5375d42d-628d-43a3-b724-c778f0a4aced)
![ffff](https://github.c
![fffff](https://github.com/FastReports/FastReport/assets/103124821/fbb0582d-3476-484b-9e8c-87cc949241c3)
om/FastReports/FastReport/assets/103124821/d4902cbe-ea09-4d72-9cc0-610aa4234fbd)
![ffffff](https://github.com/FastReports/FastReport/assets/103124821/d117f183-df4c-4335-9dff-e3725c080795)
![fffffff](https://github.com/FastReports/FastReport/assets/103124821/5feb9b20-9014-4bcf-b0b9-49a6bfc85ea8)

**Comment by lipe123** [comment]
Your second picture shows an "Expression" box that is blank. 
In that field you need to put your parameter that is passed to the report.
![image](https://github.com/FastReports/FastReport/assets/835638/0c09b9b7-d846-44da-a8b7-a4d19ebafed9)

**Comment by Alekarfes** [comment]
@salmanshafiq00 Is this issue still relevant?
