### ISSUE TITLE
Задание пользователем параметров отчета

### ISSUE THREAD

**Issue by Bykiev** [FastReports/FastReport#602]
Здравствуйте, правильно ли я понимаю, что т.к. формы не поддерживаются в FastReports OpenSource, то пользователь не может задать параметры отчета? Параметры отчета в бесплатной версии задаются только кодом?

**Comment by alexsherkhan** [comment]
Hello, @Bykiev!
Yes, FastReport.OpenSource does not support dialog forms, but you can make your own custom dialog forms and call them before preparing a report by changing the necessary parameters.

To pass a value to the parameter, use the SetParameterValue method of the Report object:
```
report1.Load("report.frx");
report1.SetParameterValue("MyParam", 10);
report1.Prepare();
```

**Comment by Bykiev** [comment]
> Hello, @Bykiev! Yes, FastReport.OpenSource does not support dialog forms, but you can make your own custom dialog forms and call them before preparing a report by changing the necessary parameters.
> 
> To pass a value to the parameter, use the SetParameterValue method of the Report object:
> 
> ```
> report1.Load("report.frx");
> report1.SetParameterValue("MyParam", 10);
> report1.Prepare();
> ```

Unfortunately, it's not the best solution to make custom dialog form for each reports, Anyway, thank you!
