### ISSUE TITLE
High memory consumption during pdfSimpleExport to file, possible memory leak

### ISSUE THREAD

**Issue by bmajkut** [FastReports/FastReport#604]
**Describe the bug**
I am using FastReport.OpenSource 2023.2.3 in my C# .NET project. This project is supposed to load template .frx file from disk and export report to pdf and save it on the disk.

`                report.Prepare();

                PDFSimpleExport pdf = new PDFSimpleExport();
                Guid g = Guid.NewGuid();
                var filepath = Path.Combine(this._pathToTmp, g.ToString() + ".pdf");
                report.Export(pdf, filepath);`

When I want to generate pdf document with size around 300MB (In fact I need to generate a lot bigger reports, like 3 GB) my application is consuming around 12,5GB of memory and after saving report to the disk memory is not lowering.

**To Reproduce**
Just prepare template, load a lof data i.e. from the database and use PDFSimpleExport to export it to the file.

**Expected behavior**
Free used memory and ofc do not use so much memory during the pdf export.

**Stacktrace**

**Screenshots**

**Device (please complete the following information):**
 - OS: Linux in Docker, dotnet image https://hub.docker.com/_/microsoft-dotnet-aspnet/
 - Browser none
 - Version 2023.2.3

**Additional context**
Is there anything I forgot to implement after exporting PDF file? Should I somehow clear the report object?

Is commercial .NET version of fast-report handling such issues better? I would buy .NET Fast-report If I would have guarantee there will be no such errors.

**Comment by dettogni** [comment]
Hi!
I have the same problem, except with a small report (~2MB).
My application is also running on Docker, using the same image and FastReport 2023.2.17.
After generating 20 reports, the application consumes 1.5GB of memory and does not release it. I noticed that this only occurs on Linux. When running locally on Windows, memory consumption doesn't go over 600MB.

To support FastReport on this docker image we added this libs:
libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev libpango1.0-dev
and instaled libgdiplus from source

**Comment by bmajkut** [comment]
> Hi! I have the same problem, except with a small report (~2MB). My application is also running on Docker, using the same image and FastReport 2023.2.17. After generating 20 reports, the application consumes 1.5GB of memory and does not release it. I noticed that this only occurs on Linux. When running locally on Windows, memory consumption doesn't go over 600MB.
> 
> To support FastReport on this docker image we added this libs: libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev libpango1.0-dev and instaled libgdiplus from source

Hello,
recently I have found that there might a memory leak or something and I have to download libgdi source and compile it by myself:

https://github.com/FastReports/FastReport/issues/316#issuecomment-974017793

Now my container consume around 500MB of RAM and the memory is being freed after the job.
