### ISSUE TITLE
Problem with PictureBox object and ImageLocation

### ISSUE THREAD

**Issue by YonasMGM** [FastReports/FastReport#605]
I am using the opensource report designer to create an frx file. This file has a PictureObject as shown here:

       <TableCell Name="Cell9" Border.Lines="All" Border.Width="0.5" Text="[dtList.Surname]" VertAlign="Center" Font="Arial, 9pt"/>
          <TableCell Name="Cell25" Border.Lines="All" Border.Width="0.5" Font="Arial, 10pt" RowSpan="4">
            <PictureObject Name="PicBxPhoto" Width="75.6" Height="75.6" ImageLocation="[dtList.Photo]" ShowErrorImage="true"/>
          </TableCell>

dtList is a datatable and the Photo column contains the file path of an image, e.g. C:\img\pic1.png. This is done in C# (ASP.NET)

The problem is while the report  displays all 10 customers surnames, the picturebox  is empty. The photo (png) file path or image location is correctly formed. 

I have also tried setting the dtList.Photo with the byte array of the image and used Image="dtList.Photo" in the frx file,  that does not display any of the photos either. 

Can anyone shed some light on this? Can the Picture Object be used in the way that I am trying? 

Many thanks in advance.

**Comment by Alekarfes** [comment]
You need to set the DataColumn property of the Picture object if you want it to get pictures from the registered datasources. Like in one of our demo reports:

![image](https://github.com/FastReports/FastReport/assets/46153199/3946f672-f246-404f-8df0-1f0ff2efa1d1)
