### ISSUE TITLE
Using a parameter named Date will display current date instead of passed value

### ISSUE THREAD

**Issue by MohamedAliTera** [FastReports/FastReport#606]
**Describe the bug**
If I add a parameter in my report with the name 'Date', it will always ignore any value I pass to it and display the current date instead.

**To Reproduce**
1. Add a parameter with the name 'Date'.
2. Add this parameter to your report.
3. Pass any value to it while generating the report.

**Expected behavior**
The parameter should always use the passed value or an error should be thrown if creating a parameter with the name 'Date' isn't allowed.

**Device (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Chrome
 - Version 114

**Comment by alexsherkhan** [comment]
Hello @MohamedAliTera !
The solution to your problem is not to call your parameters system variables.

See here:
https://fastreports.github.io/FastReport.Documentation/SystemVariables.html
