### ISSUE TITLE
.NET 7+ only for windows platform ? (skiasharp rendering)

### ISSUE THREAD

**Issue by cyberdarius** [FastReports/FastReport#611]
Dear team,

Reading this: 
https://github.com/FastReports/FastReport/issues/554
https://github.com/FastReports/FastReport/issues/445
I understand that FastReport Opensource will hopefully receive (linux, osx) skiasharp rendering sometimes in the future (commercial product already has)

But reading this:
https://github.com/FastReports/FastReport/issues/563
https://github.com/FastReports/FastReport/issues/484
I understand that from .NET7+  FastReport Opensource will only support windows platform cause it will never receive skiasharp rendering.

Please write CLEAR this new issue/policy on readme page, because in our case FastReport Opensource will became a big "demo" repo for the commercial product. For some, it can be a blocking issue in adoption of fastreport not being able to support linux/linux containters other than using the commercial product.

Thank for your works.

**Comment by xtanuiha** [comment]
Indeed, this question is also bothering me; 
I used the OpenSource version, but I had quite a few problems exporting PDF; 
Switch to FastReport .NET Trail version，There were also some issues running inside Docker; 
This seems to be because System.Drawing no longer supports the Linux platform

**Comment by BogdanStegachev** [comment]
Hello!

FastReport.Opensource does not support development for macOS. System.Drawing.Common, starting with version 7.0, will completely stop supporting non-Windows systems, so the examples of libgdiplus given above will soon not work at all.
Only the commercial version of FastReport.Core.Skia has support.
See here:
https://www.fast-report.com/en/blog/show/fastreport-core-skia/

Also expect the demo Nuget packages FastReport.Core.Skia and FastReport.Web.Skia to be released for testing with the demo FastReport .Net packages. 

Best regards,
Bogdan

**Comment by flier268** [comment]
Maybe we can migrate System,Drawing.Common to [Aspose.Drawing.Common](https://www.nuget.org/packages/Aspose.Drawing.Common)
