### ISSUE TITLE
PDFSimpleExport - Font Selection Ignored in PDF Export

### ISSUE THREAD

**Issue by Raffaele-Doti** [FastReports/FastReport#623]
I've encountered an issue while using FastReport.Export.PdfSimple.PDFSimpleExport . 
Even after changing the font in a text box through the desktop designer (e.g. from Arial to Comic Sans MS) the selected font is not applied when generating the PDF.
Instead a default font is being used.

**Steps to Reproduce:**
1. Open the FastReport Community Edition desktop designer.
2. Create a new report or open an existing one.
3. Add a text box to the report.
4. Change the font of the text box to a different font (e.g., Comic Sans MS).
5. Save the .frx template to a project folder.
6. Import the template by code using the Report class.
7. Export the report to PDF using the PDFSimpleExport class.
8. Observe that the exported PDF does not have the font applied as expected.

**Environment:**
- FastReport.Export.PdfSimple.PDFSimpleExport version: 2023.2.23
- Operating System: Docker Linux Container

**Expected Behavior:**
The PDF export should use the font selected in the designer for the text boxes.

**Actual Behavior:**
The PDF export is using a default font, ignoring the font selected in the designer.

**Code Snippet:**
```csharp
// This is a simplified version of the method from my codebase.
try
{
  // Create a new report and load the FRX template
  Report report = Report.FromFile(@"path/to/file");
  // Update existing connection from the report with our json data source.
  var jsonConnection = report.Dictionary.FindByName("existingConnectionName") as FastReport.Data.DataConnectionBase;
  var builder = new FastReport.Data.JsonConnection.JsonDataSourceConnectionStringBuilder(jsonConnection.ConnectionString)
  {
      Json = jsonDataSource
  };
  jsonConnection.ConnectionString = builder.ConnectionString;
  // Prepare the report by compiling the data
  report.Prepare();
  // Export the report to the specified output file path with the provided filename (e.g., PDF)
  report.Export(simplyPdfExporter, exportFilePath);
  // Dispose of the report after use
  report.Dispose();
  // Report generation successful
  return true; 
}
catch (Exception e)
{
   // Handle any exceptions that might occur during report generation
   logger.LogError(e.Message);
   // Report generation failed
   return false; 
}

**Comment by BogdanStegachev** [comment]
Hello!

To work correctly, you will need to install fonts in your Image Docker as follows: sudo apt-get install ttf-mscorefonts-installer

Best regards,
Bogdan
