### ISSUE TITLE
FastReport.Community.2023.2.0 broken for json

### ISSUE THREAD

**Issue by dex252** [FastReports/FastReport#626]
**Describe the bug**
List box, object from json data source not rendering properly

**To Reproduce**
1. create a json file report.json
2. Run Designer.exe in FastReport.Community.2023.2.0
3. Go to the Data tab and right-click on DataSource => New Data Source
4. Select new connection, specify the JSON Database connection type, select the previously created report.json file
5. Click next, on the Data Wizard tab expand the list of fields
6. The Info field is represented as a number, not a list

**Expected behavior**
The field information must be a list, not a number. The same thing happens if Info is an object

**Screenshots**
bug(?):
![11](https://github.com/FastReports/FastReport/assets/38129962/55f84ce7-e0a0-4c42-bf03-fe835da46b2e)
json:
![22](https://github.com/FastReports/FastReport/assets/38129962/b43e5490-24a3-4e90-92b4-35b690df823b)
Json in text:
{
	"documents": [{
			"DocumentDate": "09.09.2023",
			"LastName": "Korgi",
			"FirstName": "Dog",
			"MiddleName": "Dog",
			"Info": [{
					"Company": "IBM",
					"CountActions": 2500,
					"Cost": "28.13",
					"TransactionDate": "09.09.2023 18:05:15"
				}
			]
		}
	]
}

**Device (please complete the following information):**
 - Windows 10 Home Edition

**Comment by BogdanStegachev** [comment]
Hello!

To solve your problem, please install FastReport.OpenSource 2023.3.0 version.

Screenshot of correct work: 

![image](https://github.com/FastReports/FastReport/assets/46090791/3ad85f3f-6ec5-4dcb-a1a5-408cbc9f3a80)


Best regards,
Bogdan
