### ISSUE TITLE
Cannot move or add objects to Report

### ISSUE THREAD

**Issue by alexandredsimoes** [FastReports/FastReport#628]
**Describe the bug**
Cannot add or move any objects to the report. 
It appears that the drawing surface is locked.

**To Reproduce**
1. Go to File ->New... -> Select blank report and click Add
2. Try to select a Text object and drag to design surface

**Expected behavior**
The select object should be inserted into design surface

**Device (please complete the following information):**
 - OS: Windows 11

**Additional context**
The behavior also occurs with previously created reports.
I would like to attach a video demonstrating the problem.

**Comment by BogdanStegachev** [comment]
Hello!

To solve your problem please upgrade your FastReport.OpenSource to the current version and then follow the steps:
View -> Options -> Reset config 
after clicking on Reset config please restart your FastReport.OpenSource completely.

Best regards,
Bogdan

**Comment by alexandredsimoes** [comment]
> Hello!
> 
> To solve your problem please upgrade your FastReport.OpenSource to the current version and then follow the steps: View -> Options -> Reset config after clicking on Reset config please restart your FastReport.OpenSource completely.
> 
> Best regards, Bogdan

It works like a charm.
