### ISSUE TITLE
Bug in FastReport Designer Community Edition

### ISSUE THREAD

**Issue by mi-khatri** [FastReports/FastReport#629]
Hello, everyone,
How are you all ?

i am using fastreport for my .net winform applications.
i use fastreport opensource and it work very well.
but there is some bugs when i design my reports in community edition designer.

When i add TableObject in my report and i tryig to run it then it throw below error...

"the 'ReferenceAssemblies' property cannot contain null or empty string
Parameter name: Options"

report is run ok when i remove TableObject
what is solution for it...

please help

Here is preview ..
https://gifyu.com/image/S4RNr

**Comment by mi-khatri** [comment]
hi, i found what is problem,

when i choose script language to VisualBasic.Net then error occurred.
But when i choose C# then there is no error...

Why?
Please give solution for it ASAP

**Comment by Yamasiash** [comment]
I have notified the developers about this problem. When there will be news, we will let you know.

**Comment by BogdanStegachev** [comment]
Hello!

In the new version of FastReport Community Edition 2024.1.3 this issue has been fixed, you will be able to upgrade and see the changes

Best regards,
Bogdan
