### ISSUE TITLE
I'm having a problem using mysql and parameters query

### ISSUE THREAD

**Issue by ArthurCR12** [FastReports/FastReport#632]
Hello, in the FastReport Community

I'm having a problem, I use mysql and I created a connection. It works, but
when I try to add parameters to my query it gives me a problem .
__

Parameter type Variant is not supported; see
https://fl.vu/mysql-param-type. Value:
__

Here is how I configured the parameter.
_______

(Name) = paramName
DataType = VarChar
DefautValue =
Expression = [pName]
Size = 0
________

Always give me this problem. I have already chosen each of the data types
but it always gives the same error

Could I be doing something wrong?

**Comment by BogdanStegachev** [comment]
Hello!

Reproduced your issue, created a task and passed it to the development department, as soon as the task is completed I will let you know right away

Best regards,
Bogdan

**Comment by sbkomurcu** [comment]
I can confirm that I'm experiencing the same issue. I was actually about to open a new issue until I noticed that someone else had already reported it.

**Comment by BogdanStegachev** [comment]
As soon as the task is completed, I will let you know right away

Best regards,
Bogdan

**Comment by ArthurCR12** [comment]
good news coming soon ?

**Comment by oracertified** [comment]
Hello. I am having the same issue. Has there been a release?
