### ISSUE TITLE
The type or namespace name 'Imaging' does not exist in the namespace 'System.Drawing'

### ISSUE THREAD

**Issue by jajalecapouet** [FastReports/FastReport#636]
Hello
I'd like to build this project in visual studio, but i got this error :
CS0234	The type or namespace name 'Imaging' does not exist in the namespace 'System.Drawing' (are you missing an assembly reference?)	FastReport.OpenSource.Export.PdfSimple (netstandard2.0)	C:\dev\fastReportGitHubRepo\FastReport\Extras\OpenSource\FastReport.OpenSource.Export.PdfSimple\FastReport.OpenSource.Export.PdfSimple\PDFSimpleExport.Images.cs	line 7

Same with using ./pack.bat, i got this error : "C:\dev\fastReportGitHubRepo\FastReport\Extras\OpenSource\FastReport.OpenSource.Export.PdfSimple\FastReport.OpenSource.E
xport.PdfSimple\PDFSimpleExport.Images.cs(7,22): error CS0234: The type or namespace name 'Imaging' does not exist in the namespace 'System.Drawing' (are you missing an assembly reference?) [C:\dev\fastReportGitHubRepo\Fas
tReport\Extras\OpenSource\FastReport.OpenSource.Export.PdfSimple\FastReport.OpenSource.Export.PdfSimple\FastReport.Open
Source.Export.PdfSimple.csproj::TargetFramework=netstandard2.0]"
and 15 more errors.

**Comment by Yamasiash** [comment]
In what actions do you get errors? Can you describe the steps to reproduce the problem?
