### ISSUE TITLE
MongoDB Example

### ISSUE THREAD

**Issue by alberk8** [FastReports/FastReport#644]
**Is your feature request related to a problem? Please describe.**
I am trying out the Demo in this repository and it works.  But when I try to create a simple report (with community Report Designer) where the data source is from MongoDB.  How do I add it in the ASP.net?

**Describe the solution you'd like**
An example of how a sample MongoDB or other database source can be included in the Demo.

**Comment by BogdanStegachev** [comment]
Hello!

I am sending you an example of adding MongoDB via the code below for this you will also need our nuget package FastReport.Data.MongoDB:

How to use it:
- execute the following code once at the application start:
`FastReport.Utils.RegisteredObjects.AddConnection(typeof(MongoDBDataConnection));`
- now you should be able to create a new MongoDB data connection from code:
```
Report report = new Report(); 
report.Load(@"YourReport.frx");
```
//... 
```
MongoDBDataConnection conn = new MongoDBDataConnection();
conn.ConnectionString = "your connection string";
conn.CreateAllTables();
report.Dictionary.Connections.Add(conn);
```

Best regards,
Bogdan

**Comment by BogdanStegachev** [comment]
Hello!

Use the following lines to solve your problem:

MongoDBDBDataConnection conn = new MongoDBDataConnection();
conn.ConnectionString = "your connection string";
conn.CreateAllTables();
conn.Name = "Test";
report.Dictionary.Connections.Add(conn);

Best regards,
Bogdan
