### ISSUE TITLE
Deprecated options on Mongodb Drivers

### ISSUE THREAD

**Issue by kelwinxd** [FastReports/FastReport#646]
When i try no connect to **Atlas Mongodb**, the connection was succesful. Although, the following message appeared on terminal:

**
> error in authentication man! [Function: error]
> (node:9712) [MONGODB DRIVER] Warning: useNewUrlParser is a deprecated option: useNewUrlParser has no effect since Node.js Driver version 4.0.0 and will be removed in the next major version
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:9712) [MONGODB DRIVER] Warning: useUnifiedTopology is a deprecated option: useUnifiedTopology has no effect since Node.js Driver version 4.0.0 and will be removed in the next major version**

The connection coding:
`const { error } = require('console');
const { MongoClient } = require('mongodb');

const uri = "mongodb+srv://kelwinesechiel8:<password>@cluster0.vxfjhgw.mongodb.net/?retryWrites=true&w=majority";

async function run() {
  const client = new MongoClient(uri, { useNewUrlParser: true, useUnifiedTopology: true });

  try {
    await client.connect();

    const dbo = client.db('keldb');
    const obj = { name:'Kaleb' };
    const colecao = 'names';
    
    await dbo.collection(colecao).insertOne(obj);
    console.log('succesfully inserted');
  } finally {
    await client.close();
  }
}

run().catch(console.log('error in authentication man!', error));
`

Config:
**Node 20.8.1
Mongodb ^6.3.0**

**Comment by BogdanStegachev** [comment]
Hello!

I am sending you a test example of correct connection to MongoDB via code:

How to use it:
- execute the following code once at the application start:
FastReport.Utils.RegisteredObjects.AddConnection(typeof(MongoDBDataConnection));
- now you should be able to create a new MongoDB data connection from code:
Report report = new Report(); 
report.Load(@"YourReport.frx");
//... 
MongoDBDataConnection conn = new MongoDBDataConnection();
conn.ConnectionString = "your connection string";
conn.CreateAllTables();
report.Dictionary.Connections.Add(conn);


Best regards,
Bogdan
