### ISSUE TITLE
Install/reference Microsoft.CodeAnalysis.Common 4.0.0 directly to project Web.MVC to resolve this issue.

### ISSUE THREAD

**Issue by marcosmarchette** [FastReports/FastReport#647]
When trying to add the FastReport package to the project
the following error is reported:

Severity Code Description Project File Line Suppression State
Error NU1107 Version conflict detected for Microsoft.CodeAnalysis.Common.

Install/reference Microsoft.CodeAnalysis.Common 4.0.0 directly to project Web.MVC to resolve this issue.

 
  Web.MVC -> Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 6.0.7 -> Microsoft.CodeAnalysis.Razor 6.0.7 -> Microsoft.CodeAnalysis.Common (>= 4.0.0)
  Web.MVC -> FastReport.OpenSource 2023.3.13 -> FastReport.Compat 2023.3.1 -> Microsoft.CodeAnalysis.VisualBasic 3.3.1 -> Microsoft.CodeAnalysis.Common (= 3.3.1).
  Web.MVC C:\Projetos\ERP\ERP-Desenvolvimento-branch-Relatorios-Testes-MPMarchette\Web.MVC\Web.MVC.csproj 1

Package Version: 2023.3.13

Project create in Net6

OS: Window 10

How to solve?

**Comment by Bohdandn** [comment]
Same issue, referencing `Microsoft.EntityFrameworkCore.Design 8.0.0` together with `FastReport.OpenSource 2024.1.1` resulting in this error. Override `<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.5.0" NoWarn="NU1107,NU1608" />` breaks fast report.

```
NU1107: Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.5.0 directly to project XXX to resolve this issue. 
 XXX -> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0) 
 XXX -> FastReport.OpenSource 2024.1.1 -> FastReport.Compat 2024.1.0 -> Microsoft.CodeAnalysis.VisualBasic 3.3.1 -> Microsoft.CodeAnalysis.Common (= 3.3.1).
```

**Comment by Yamasiash** [comment]
Are you reproducing the problem with the latest version of the package?

**Comment by Bohdandn** [comment]
Since we do not generate reports with a code we just enforced version required by EF Core.

**Comment by JPScerri** [comment]
Getting the same issue. Working on version 2025.2.0
When we inject a footer programmatically, it throws the attached error. Seems that it does not work with the latest CodeAnalysis.Common and CodeAnalysis.CSharp

![Image](https://github.com/user-attachments/assets/d92617d9-cf78-4cf4-8655-e2be3c42f273)
