### ISSUE TITLE
Report.Prepare() takes too much time to compile the report

### ISSUE THREAD

**Issue by frontlook-admin** [FastReports/FastReport#648]
``               
var report = new WebReport();
report.Report.Load(ReportFilePath);
report.Report.RegisterData(ds, DatabaseName);
if (parameters != null && parameters.Count > 0)
{
         parameters.ForEach(e =>
         {
                  report.Report.SetParameterValue(e.Name, e.Value);
          });
}
report.EmbedPictures = true;
report.Report.Prepare();
//return report;

``

It takes too much time to prepare the report. minimum 30 secs after providing all the data in a DataSet. Am I doing any thing wrong?

**Comment by alberk8** [comment]
Interesting,  How big is your dataset?

**Comment by Yamasiash** [comment]
This behavior usually occurs because of a large dataset or a complex report.
