### ISSUE TITLE
.Net 7 throw 'System.TypeInitializationException' in FastReport.dll

### ISSUE THREAD

**Issue by Coder7777** [FastReports/FastReport#651]
A piece of very simple code,  Report invoiceReport = new Report();

then application throw an exception. 

It looks like causing by using GDI+  in MacOS,  the error log mentioned 'libgdiplus'.

Any idea about that?

Thanks

**Expected behavior**
Report invoiceReport = new Report();
// throw the exception once I new a instance.

**Stacktrace** 
Exception thrown: 'System.TypeInitializationException' in FastReport.dll
[08:51:40 ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {},
  "validationErrors": null
}

[08:51:40 ERR] The type initializer for 'FastReport.Report' threw an exception.
System.TypeInitializationException: The type initializer for 'FastReport.Report' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'FastReport.Utils.Config' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'FastReport.TypeConverters.FontConverter' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:

**Screenshots**

**Device (please complete the following information):**
 - OS: MacOS 13.4.1 

**Additional context**

**Comment by igorilyichyov** [comment]
Try to install  libgdiplus 
brew install mono-libgdiplus

**Comment by Coder7777** [comment]
> Try to install libgdiplus `brew install mono-libgdiplus`

It does no work. I tried it before.

**Comment by Yamasiash** [comment]
You need to use FastReport Core Skia. You can read more in this article 
https://www.fast-report.com/en/blog/show/fastreport-core-skia/
