### ISSUE TITLE
Issue Adding MySQL Connection in Designer (Version 2024.1.0)

### ISSUE THREAD

**Issue by sbkomurcu** [FastReports/FastReport#653]
I recently upgraded to version 2024.1.0, and I'm encountering an issue when attempting to add a MySQL connection. The error message is displayed in the screenshot linked below:
  
![image](https://github.com/FastReports/FastReport/assets/19965011/e7960156-c984-43ed-ba72-6465570fa3cd)

Environment Details:
    Operating System: Windows
    Application Version: 2024.1.0

I would appreciate any assistance or guidance to resolve this matter. Thank you!

**Comment by BogdanStegachev** [comment]
Hello!

Reproduced your problem created a task and passed it to the development department, expect a fix in the next version of FastReport Open Source

Best regards,
Bogdan

**Comment by BogdanStegachev** [comment]
Hello!

Our developers managed to solve the problem according to your request, expect changes in the next version of Fastreport Community Edition

Best regards,
Bogdan
