### ISSUE TITLE
Does fastreport support AOT ?

### ISSUE THREAD

**Issue by jianliulin** [FastReports/FastReport#655]
Does fastrrport support AOT ?

**Comment by Detrav** [comment]
Need to check, but probably not.

**Comment by Detrav** [comment]
A quick check of the demo application showed that it is not.

FastReport uses its own dll to build the script, so in order for AOT to work in the future, we need to move the build process from FastReport itself to a separate library.

This is quite a lot of work so don't expect it in the near future. This is the first request for an AOT build; if there are more requests, the developers will probably allocate time for this.

As always, we are open to pull requests.

Make more requests to increase the priority
