### ISSUE TITLE
Please set the default for paddingNonSeparatePages to 0 in ImageExport, as this currently is 10 and thus results in an image that has a bigger size than expected

### ISSUE THREAD

**Issue by nivle** [FastReports/FastReport#658]
**Is your feature request related to a problem? Please describe.**

I spent 5 hours looking why my image size was wrong, only to find out, that by default fast report adds a padding to the image, making the image bigger than it's supposed to be, which when printed is not the same as in the template.

![image](https://github.com/FastReports/FastReport/assets/16451772/c8ccb3dc-728f-4174-8a3a-0b4c44d0314a)

**Describe the solution you'd like**

Please set the above marked property in the image by default to 0!

**Comment by Yamasiash** [comment]
Hello!

I checked the export to picture and it looks pretty correct. Could you please attach more screenshots or steps to reproduce the problem?

**Comment by Yamasiash** [comment]
I've passed the information on to the developers. When new information is available, we will let you know.

**Comment by Alekarfes** [comment]
We've fixed the issue and the fix will appear in the following versions.
