### ISSUE TITLE
Mysql connection with .Net Core 2

### ISSUE THREAD

**Issue by psohm** [FastReports/FastReport#66]
How can I use a mysql database with FR .Net Pro edition on .Net Core 2.2
As soon as I have a odbc database, I have that error 
ClassException: Can't find object OdbcDataConnection

If i try to add FastReport.Utils.Registered
Objects.AddConnection(typeof(FastReport.Data.MySqlDataConnection));
I have that error :
ClassException: Can't find object OdbcDataConnection

**Comment by Detrav** [comment]
Hi!

For .NET Core you cannot use ODBC connector, please use [FastReport.Data.MySql](https://www.nuget.org/packages/FastReport.Data.MySql/) for PRO version or [FastReport.OpenSource.Data.MySql](https://www.nuget.org/packages/FastReport.OpenSource.Data.MySql) for opensource version

How to use it:
- execute the following code once at the application start:
```
FastReport.Utils.RegisteredObjects.AddConnection(typeof(MySqlDataConnection));
```
now you should be able to create a new MySQL data source from Designer (.Net 4) or from code:
```
Report report = new Report(); 
report.Load(@"YourReport.frx");
//... 
MySqlDataConnection conn = new MySqlDataConnection();
conn.ConnectionString = "your connection string";
conn.CreateAllTables();
report.Dictionary.Connections.Add(conn);
```

By the way, you can always get advice on the full version of the product in [the technical support](https://support.fast-report.com/).

**Comment by psohm** [comment]
Hello
Tks for your reply
I used another way to reconfigure my connection string:

```
foreach (FastReport.Data.DataConnectionBase item in report.Dictionary.Connections)
{
    item.ConnectionString = connectionString;
}
```

But now I have another problem : 
Exception: Font file not found on system
FastReport.Export.TTF.TrueTypeCollection.get_Item(Font index)

Do I have to install every fonts ?

**Comment by rbriguetto** [comment]
> I had another problem :
Exception: Font file not found on system
FastReport.Export.TTF.TrueTypeCollection.get_Item(Font index)
> 
I had this issue on Windows environment and I solve it removing "font.list" file from application root folder.
