### ISSUE TITLE
FastReport Community Report Designer 2024.1.0 cannot Run

### ISSUE THREAD

**Issue by alberk8** [FastReports/FastReport#660]
**Describe the bug**
The Designer can open an existing Report but when try to run the report the following error appears.

`Error CS1705: Assembly FastReport, Version=2024.1.0.1, Culture=nutral, PublicToken=xxxx users FastReport,Compat, Version2023.3.1.0 xxxx....`

**To Reproduce**

1. Steps to reproduce the behavior:
2. Download the FastReport [Designer](https://github.com/FastReports/FastReport/releases/download/v2024.1.0/FastReport.Community.2024.1.0.zip)
3. Open an existing Report
4. Click Run

**Expected behavior**
Runs report without error.

**Screenshots**
![image (3)](https://github.com/FastReports/FastReport/assets/12510130/ca8406cc-06a0-469f-b30d-21e772530457)

**Device (please complete the following information):**
 - OS:  Windows 10
 - Browser  chrome
 - Version latest

**Additional context**

**Comment by cmregazzo** [comment]
Good morning,

I have the same problem reported when opening the Issue, but in my case, it is occurring when a Script is created in the Code tab.

Thanks

**Comment by araujofrancisco** [comment]
For me it was working until I updated FastReport source code and recompiled, my guess is that after recompiling it updated some of the assemblies causing the issue.

**Comment by kofcwaorg00** [comment]
This is happening to me too.  Is there any resolution?

**Comment by kofcwaorg00** [comment]
Update:  This seems to happen only when I add the 1st Calculated Column.  Can anyone help?

**Comment by Yamasiash** [comment]
Hello!

Thank you for reporting this problem! We will try to fix it as soon as possible.

**Comment by kofcwaorg00** [comment]
@Yamasiash, if this is closed does that mean that the issue is fixed? If so, will there be a new download? Thanks!
(sorry for the duplicate, forgot the @)
