### ISSUE TITLE
Adjusting TextArea Size dynamically with HTML Tags - not working.

### ISSUE THREAD

**Issue by wagenheimer** [FastReports/FastReport#662]
![image](https://github.com/FastReports/FastReport/assets/315513/9f6fb1f7-179b-4956-b7b7-25b17e766c6d)

I have a scenario where I am utilizing Produto.descricao with the following settings: CanBreak=true, CanGrow=true, Clip=false, WordWrap=true, and TextRenderType=Default. In this configuration, everything works as expected.

It works as expected.

![image](https://github.com/FastReports/FastReport/assets/315513/da5351f1-6e88-4394-86dd-33052e749b9e)

But if I change  **TextRenderType=HtmlTags**
![image](https://github.com/FastReports/FastReport/assets/315513/d9b83057-299f-4bb2-973e-5038b5eb4a54)

The TextArea does not automatically resize to fit the content. It maintains the same size as the content without the HTML tags applied.

Is there a workaround for this issue? I'm looking for a solution to ensure the TextArea adjusts its size dynamically based on the content when using TextRenderType=HtmlTags.

I appreciate any guidance or suggestions to address this behavior.

**Comment by wagenheimer** [comment]
I've also conducted a testing with the Paid Version, and unfortunately, the same issues happen. This problem is consistent whether using the TEXT or HTML component.

**Comment by Yamasiash** [comment]
Hello!

Could you attach a test report with saved data? To save the data in the report, just set the StoreData property to true. Then save the report and attach it here.

**Comment by wagenheimer** [comment]
Where can I find the StoreData property?

`                // Registers the application dataset
                report.RegisterData(orcamento, "OrcamentoVenda");

                report.Dictionary.RegisterBusinessObject(orcamento, "Orcamento", 2, true);
                report.Dictionary.RegisterBusinessObject(orcamentoVenda.Produtos, "Produtos", 2, true);
                report.Dictionary.RegisterBusinessObject(orcamentoVenda.CondicoesComerciais, "CondicoesComerciais", 2, true);

                //       report.Save(relatoriosPath); //Salva Modelo de Dados

                if (report.Report.Prepare())
                {
                    report.Save(Path.Combine(webRoot, "Relatorios", "OrcamentoVendaComDados.frx")); //Salva Modelo de Dados
                    return CelmiUtils.ExportaPdf(report, "Orçamento de Venda.pdf");
                }
                else
                    return View();`
