### ISSUE TITLE
Images exported with HTMLExport are blurry

### ISSUE THREAD

**Issue by Wazrop** [FastReports/FastReport#663]
**Describe the bug**
When exporting a report containing images with HTML Export the images are blurred / low quality. If exporting the same report with SimplePDF Export the images are clear.

**To Reproduce**
1. Create a report containing an image.
2. Export the report with HTMLExport
3. Open the exported HTML
4. The blurred, low quality image is generated
5. For comparison export the same report with PDFSimpleExport where the image is clear, high quality

**Expected behavior**
Images generated with HTMLExport should look the same as images generated with PDFSimpleExport.

**Screenshots**
HTMLExport:
![image](https://github.com/FastReports/FastReport/assets/3672881/38a38a80-dcbd-4af4-b1f4-06a2030b3301)
SimplePDFExport:
![image](https://github.com/FastReports/FastReport/assets/3672881/66f61fa7-1206-4375-ad25-c4196fd89f06)

**Versions:**
 - FastReport.OpenSource version 2024.1.2

**Comment by Yamasiash** [comment]
Hello!

We have checked the exports and the problem is not reproduced. Could you please attach a test report where we can reproduce the problem?

**Comment by Wazrop** [comment]
Hello,

I have created an example project with this issue: [https://github.com/Wazrop/FastReportImageExportTest](https://github.com/Wazrop/FastReportImageExportTest)

The project is pretty straightforward. Endpoints are DownloadPdf and DownloadHtml which both generate either a pdf (PDFSimpleExport) or html (HTMLExport) from the [same report file](https://github.com/Wazrop/FastReportImageExportTest/blob/main/Report/ImageExportTest.frx) and download the file. 

The difference is even more noticeable if each file is printed onto paper.

Thank you for your time.

**Comment by Alekarfes** [comment]
Also, please try enabling the HighQualitySvg property of the export.
