### ISSUE TITLE
NETFramework,Version=v4.7.2

### ISSUE THREAD

**Issue by ViktorVohmin** [FastReports/FastReport#665]
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления	Подробности
Ошибка		Не удалось установить пакет «FastReport.OpenSource.Web 2024.1.3». Вы пытаетесь установить этот пакет в проект, требуемая версия платформы которого — «.NETFramework,Version=v4.7.2», но в пакете нет ссылок на сборки или файлов содержимого, совместимых с этой платформой. Дополнительную информацию можно получить у автора пакета.

**Comment by Yamasiash** [comment]
Hello!

Under what circumstances does this problem occur?
