### ISSUE TITLE
FastReport.OpenSource.Angular.OnlineDesigner

### ISSUE THREAD

**Issue by VohminV** [FastReports/FastReport#666]
Как в пример добавить поддержку PostgreSQL. Я в npm все пакеты PostgreSQL добавил или FastReport.Web не работает с PostgreSQL ?

**Comment by BogdanStegachev** [comment]
Hello!

To add PostgreSQL connectivity to your application, you will need to install the FastReport.Data.Postgres package from the nuget.org package source 

Then register this connection in the following way:

`FastReport.Utils.RegisteredObjects.AddConnection(typeof(PostgresDataConnection));`

Example of connection to PostgreSQL via code:

```
Report report = new Report(); 
report.Load(@‘YourReport.frx’);
//... 
PostgresDataConnection conn = new PostgresDataConnection();
conn.ConnectionString = ‘your connection string’;
conn.CreateAllTables();
report.Dictionary.Connections.Add(conn);
```

Best regards,
Bogdan
