### ISSUE TITLE
XmlDataConnection DataSet Improvement

### ISSUE THREAD

**Issue by chad-albrecht** [FastReports/FastReport#669]
**Is your feature request related to a problem? Please describe.**
If you build your report based on an XmlFile (think report template), then try to use the FRX in code to populate the report with data that cannot be found on disk (streams, message queues, webhook, etc.) it fails.  This is due to a limitation of the XmlDataConnection being bound to a file or URL only.

**Describe the solution you'd like**
Allow the XmlDataConnection to be populated with a DataSet from an unknown source.  This could be as simple as allowing the connection string to be the actual XML similar to the JsonDataSourceConnection.

**Describe alternatives you've considered**
1) Using the JsonDataSourceConnection and serializing my XML to JSON.  This creates undesirable index/array/fieldname conditions in the report designer.
2) Modifying the open source code to allow DataSet to be settable in DataConnectionBase
3) Implement a LoadDataSet event on the DataConnectionBase that would allow the DataSet to be injected by code (most promising path)

**Additional context**
None.

**Comment by Alekarfes** [comment]
Thank you for the suggestion, we'll look into it.
