### ISSUE TITLE
Save and Print buttons not working

### ISSUE THREAD

**Issue by kofcwaorg00** [FastReports/FastReport#674]
I have used the examples and built an application for my FastReports Reports. Everything seems to work fine except the browser rendering control you are using will not allow the PRINT or SAVE FILE buttons to work. I am using the most current version of Edge and Chrome. Is there something I need to be doing to enable these functions. Kind of silly that I can print a report from the report so I assume that I have missed something. I am using DotNet Core 8.0 and FastReports 2023.2.16

**To Reproduce**
1. Create a report using the open source designer
2. Run the report using DOTNET Core 8 MVC Project
3. The report is produced in the webpage
4. The PRINT and SAVE FILE buttons are not functional

**Expected behavior**
I would expect the SAVE button to produce a Save As dialog and the PRINT button to open t;he print dialogue.

![image](https://github.com/FastReports/FastReport/assets/143735743/b17c8c30-186b-414f-9507-32ff793f6703)

**Comment by Alekarfes** [comment]
I've reproduced this on a version 2023.2.x but not on 2024.1.0 and higher. So I would recommend you to update.

**Comment by kofcwaorg00** [comment]
This is the version of the Designer:

![image](https://github.com/FastReports/FastReport/assets/143735743/59f366df-d41c-4e5c-9d21-932f73d12a70)

and the version of the NewGet packages I am using:

![image](https://github.com/FastReports/FastReport/assets/143735743/6086a3e9-c39c-4304-8d7e-5a9e252debc9)

So I think I am using the current version of both

**Comment by Alekarfes** [comment]
The designer is irrelevant here, and the icon is not supposed to work as a button - it'll show a drop-down menu when hovered over. In your first message you've mentioned 2023.2.16, so I've checked a version close to that and the newest versions of FastReport OpenSource. I've tested both, the drop-down menu doesn't appear in 2023.2.x, but does appear in the latest version.
![image](https://github.com/FastReports/FastReport/assets/46153199/d5ecfb40-ed55-4267-9c07-0b50d6a16e79)

Could you please send a project in which this doesn't work?

**Comment by khalid2051** [comment]
https://github.com/FastReports/FastReport/tree/master/Demos/OpenSource/SPA/FastReport.OpenSource.Angular

Save and Print Button Not Firing in Demo Project!

@Alekarfes

**Comment by sdc8835** [comment]
when i hover over the save button i am not able to find the export to pdf,excel,word options how to achieve that
