### ISSUE TITLE
Refresh button click in WebReports 500 index out of range issue occur

### ISSUE THREAD

**Issue by Seenuvasanmohan** [FastReports/FastReport#680]
Open the Reports.
Navigate to any one report.
Extract the data.
After the data is moved to the 2nd page click the 'Refresh Report' button is click following issue occur.
"Error
500 - Internal Server Error
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') at FastReport.Web.WebReport.GetReportPageWidthInPixels() at FastReport.Web.WebReport.ReportInHtml() at FastReport.Web.WebReport.template_body(Boolean renderBody) at FastReport.Web.WebReport.template_render(Boolean renderBody) at FastReport.Web.WebReport.Render(Boolean renderBody) at FastReport.Web.Controllers.ReportController.<.ctor>b__0_0() at FastReport.Web.Controllers.BaseController.OnRequest(HttpContext httpContext) at FastReport.Web.FastReportMiddleware.RequestFastReportController(HttpContext httpContext) at FastReport.Web.FastReportMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context) HEADERS ======= Accept: */* Accept-Encoding: gzip, deflate, br Accept-Language: en-US,en;q=0.9 Connection: keep-alive Content-Length: 0 Cookie: .AspNetCore.Antiforgery.s5198RhDlHM=CfDJ8JoUc8u8xnJIocbOVMX8456hJTSdVsYytemo1u6Mol4AC32Rh7tHEk_qQ1habXKGyThCBAainO-oBcpBGHSrjwHHt60-Z67D2uwm8hlmXOVh6Di27VTTnDe3EdDEoBLYqp5OAQ_-EzBxx11nZhwCgFE; AngelCVCSSession=CfDJ8JoUc8u8xnJIocbOVMX8454XB3nWAxH58UMxSiET0riPv8IBO%2BDQZa0FbeQ51O7YvQQBCMnydu9CEzwROZcwd%2BRXywNChB5VVDwZeaPeOyzymcYCW6Bq9eEcBi2CJBFn9NzbWXAgEzQjCqFRO8OmBoX3K4NHaZcoWFz5%2Bhin1Cpz; .AspNetCore.Cookies=CfDJ8JoUc8u8xnJIocbOVMX8456vjqT40c5Vx2kRX1LOJvPdhW35DKq9kwjidB5eUy4_0A58uIkRvwVCQJJcLLqO_z0X66Ot4N1KYNQs5ohDWbhOjWlVOIUk0hFStxTeFp0MPikZqUQ4wjvhhjwueV1W-DRVfvxl6CwQfpw7DAwYt0ScyKSGnNvzjJEUd7_58olU0hz_ekvNjWWuauc-x56nPyHLUSB5R1U1TgAjk4h6iand31G7Hk89r7mjdtJKGNEHzo_88LOq8RwBvNwI26H7dvidJ2rsoSHzF9ujDF45YGN-5JI6fMCfODa7jGKN_tcEVrCeMjZxGMCR7RtZjffgInEJ2YACib_8gF-uPeBTy-UeES7O2D_UxTV64qP4qR7cubec8RcvYV6-MQ6flMbDjgZ2K0M8Ig8q1hzzcSLf34RFS60v1UVI4xefd9nQqyWcIsfkZHTzsOMNbaBrcfzNyfujLC5A1jNL_Pfz4FBilYZLXfkpsWCT5vSGUue-9_5bPKMLxYdTGzUqdiamI0si4WA; XSRF-TOKEN=CfDJ8JoUc8u8xnJIocbOVMX8456ykAsSPnxVpAZlzeiWcVGFJyc0PnDHKXzkcgOI9R2ZgfyDIW7sxm7yPXWZi3vbykjLvGvnOhDUG50GU_i1crXLNUpu9ALvZ4m2I8UdsxiwizUxMVVDqRiWYo4ka6dEXsUEyufPXuUSkFr7AVea1THYSFuhPGQgHze26UMFSTUaEw Host: localhost:9000 Referer: http://localhost:9000/ReportsView/ReportDetailView?ReportId=1 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121" sec-ch-ua-mobile: ?0 sec-ch-ua-platform: "Windows" Origin: http://localhost:9000 Sec-Fetch-Site: same-origin Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty"

**Comment by BogdanStegachev** [comment]
Hello!

When testing this issue on our application, this behaviour did not reproduce on the latest version of FastReport

Test application:  
[FastReport.Core.MVC.6.0.zip](https://github.com/user-attachments/files/18238945/FastReport.Core.MVC.6.0.zip)


Best regards,
Bogdan
