### ISSUE TITLE
Error CS0103: The name 'Produto' does not exist in the current context

### ISSUE THREAD

**Issue by eliezeralmeida** [FastReports/FastReport#682]
**Describe the bug**

With Designer.exe my Report works perfect!!!

![image](https://github.com/FastReports/FastReport/assets/2786448/76db07d5-1308-4529-a6d6-533939cb2d97)

**To Reproduce**
1. Create a FRX file using Designer.exe.
2. Add MSSQL Connection.
3. Create a .NET7 Project.
4. Create code from above image.

**Expected behavior**

**Stacktrace**
`   at FastReport.Code.AssemblyDescriptor.InternalCompile()
   at FastReport.Code.AssemblyDescriptor.Compile()
   at FastReport.Report.Compile()
   at FastReport.Report.Prepare(Boolean append)
   at FastReport.Report.Prepare()
   at Program.<Main>$(String[] args) in C:\Users\eliez\source\repos\FastReportCommunity\ConsoleApp\Program.cs:line 8`

**Screenshots**
![image](https://github.com/FastReports/FastReport/assets/2786448/557e1d90-50e2-4424-a439-f408c31570fb)

**Device (please complete the following information):**
 - OS: Windows 11
 - Browser: none
 - Version: 2024.1.7
 - NET7

**Additional context**

`<?xml version="1.0" encoding="utf-8"?>
<Report ScriptLanguage="CSharp" ReportInfo.Created="02/23/2024 17:50:17" ReportInfo.Modified="02/23/2024 18:55:25" ReportInfo.CreatorVersion="2023.2.18.0">
  <Dictionary>
    <MsSqlDataConnection Name="MSSQL_Connection" ConnectionString="rijcmlqN/jnmYfUwPzQdJg9KqaYWm+wHolLb6isIBHWICIv2aOF6wSKm1ywp1GzIKHeXmneBp/e1MmKaSILyQSYfPsxuEVIvY595epxXfzdpgkL6yz54cN7hvyHTRGTKtoi/VWTini6oFLP4zUbF8X/2TN5eyN8BN93GwFhHFJapDbMsZL55msqIe72b+u6ahowaU0iW6qH3OO2MCdsluuQIrGDZstZi+ziHY1lpKtkqTXi9rY=">
      <TableDataSource Name="Produto" DataType="System.Int32" PropName="Table" Enabled="true" SelectCommand="select &#13;&#10;	p.id as ProdutoCodigo,&#13;&#10;	p.nome as ProdutoNome,&#13;&#10;	p.tabelaNcm_id as NCM,&#13;&#10;	p.codigoCest as CEST,&#13;&#10;	rts.situacaoTributariaIcms_id as CST_ICMS,&#13;&#10;	rts.situacaoTributariaCsosn_id as CSOSN_ICMS,&#13;&#10;	p.aliquotaIcms as AliquotaICMS,&#13;&#10;	p.reducaoIcms as ReducaoICMS,&#13;&#10;	p.percentualMva MVA_ICMS,&#13;&#10;	p.situacaoTributariaIpi_id as CST_IPI,&#13;&#10;	p.aliquotaIpi as AliquotaIPI,&#13;&#10;	p.situacaoTributariaPis_id as CST_PIS,&#13;&#10;	p.aliquotaPis as AliquotaPIS&#13;&#10;from produto p&#13;&#10;inner join regra_tributacao_saida rts on rts.id = p.regraTributacaoSaida_id;">
        <Column Name="ProdutoCodigo" DataType="System.Int32"/>
        <Column Name="ProdutoNome" DataType="System.String"/>
        <Column Name="NCM" DataType="System.String"/>
        <Column Name="CEST" DataType="System.String"/>
        <Column Name="CST_ICMS" DataType="System.String"/>
        <Column Name="CSOSN_ICMS" DataType="System.String"/>
        <Column Name="AliquotaICMS" DataType="System.Decimal"/>
        <Column Name="ReducaoICMS" DataType="System.Decimal"/>
        <Column Name="MVA_ICMS" DataType="System.Decimal"/>
        <Column Name="CST_IPI" DataType="System.String"/>
        <Column Name="AliquotaIPI" DataType="System.Decimal"/>
        <Column Name="CST_PIS" DataType="System.String"/>
        <Column Name="AliquotaPIS" DataType="System.Decimal"/>
      </TableDataSource>
    </MsSqlDataConnection>
    <Parameter Name="NomeEmpresa" DataType="System.String" AsString=""/>
    <Parameter Name="LogoEmpresa" DataType="System.Byte[]" AsString=""/>
  </Dictionary>
  <ReportPage Name="Page1" Watermark.Font="Arial, 60pt">
    <ReportTitleBand Name="ReportTitle1" Width="718.2" Height="103.95">
      <PictureObject Name="Picture1" Left="18.9" Top="9.45" Width="94.5" Height="85.05" Image=""/>
      <TextObject Name="Text1" Left="113.4" Top="9.45" Width="567" Height="28.35" Text="[NomeEmpresa]" Font="Arial, 14pt"/>
    </ReportTitleBand>
    <DataBand Name="Data1" Top="133.3" Width="718.2" Height="22.68" DataSource="Produto">
      <TextObject Name="Text6" Left="359.1" Width="94.5" Height="18.9" Text="[Produto.ProdutoCodigo]" Font="Arial, 10pt"/>
      <TextObject Name="Text7" Width="359.1" Height="18.9" Text="[Produto.ProdutoNome]" Font="Arial, 10pt"/>
      <DataHeaderBand Name="DataHeader1" Top="107.28" Width="718.2" Height="22.68">
        <TextObject Name="Text3" Width="359.1" Height="18.9" Text="ProdutoNome" Font="Arial, 10pt"/>
        <TextObject Name="Text5" Left="359.1" Width="94.5" Height="18.9" Text="ProdutoCodigo" Font="Arial, 10pt"/>
      </DataHeaderBand>
    </DataBand>
    <PageFooterBand Name="PageFooter1" Top="159.31" Width="718.2" Height="30.24"/>
  </ReportPage>
</Report>
`

**Comment by BogdanStegachev** [comment]
Hello!

This error occurs because you are using MS Sql connection in your report, but you do not register the connection before loading the report with the data source.

To solve your problem, you will need to use the following code before the Report declaration:

`FastReport.Utils.RegisteredObjects.AddConnection(typeof(MsSqlDataConnection));`

I am also sending you an example of adding a connection through the code:

```
Report report = new Report(); 
report.Load(@‘YourReport.frx’);
//... 
MsSqlDataConnection conn = new MsSqlDataConnection();
conn.ConnectionString = ‘your connection string’;
conn.CreateAllTables();
report.Dictionary.Connections.Add(conn);
```

Best regards,
Bogdan
