### ISSUE TITLE
Adding/Editing/Testing Connection Error

### ISSUE THREAD

**Issue by wnono-cu** [FastReports/FastReport#684]
Error occurred when adding/editing/testing a connection using JSON database. When I attempt to click finish button, it shows an error dialog showing different missing dll everytime.

![image](https://github.com/FastReports/FastReport/assets/91782846/592dbbb9-c144-4626-b44e-6f5c6f43f3d0)
![image](https://github.com/FastReports/FastReport/assets/91782846/79a4f226-77e2-4e01-b898-6fc532906368)
![image](https://github.com/FastReports/FastReport/assets/91782846/a18ba1cd-4e16-48ca-8e33-104f49dfcda6)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\DJXCDS\AppData\Local\Temp\wkhuczbh.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\Users\DJXCDS\AppData\Local\Temp\wkhuczbh.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, Evidence assemblySecurity)
   at System.CodeDom.Compiler.CompilerResults.get_CompiledAssembly()
   at FastReport.Utils.CompileHelper.GenerateAssemblyInMemory(String sourceCode, String[] assemblyPaths)
   at FastReport.Json.JsonCompiler.Compile(String json)
   at FastReport.Data.JsonDataConnection.CreateDataSet()
   at FastReport.Data.DataConnectionBase.CreateRelations()
   at FastReport.Forms.DataWizardForm.Done()
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Designer
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
FastReport
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
FastReport.Bars
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
FastReport.Editor
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
FastReport.Compat
    Assembly Version: 2024.1.0.0
    Win32 Version: 2024.1.0.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/FastReport.Compat.DLL
----------------------------------------
FastReport.DataVisualization
    Assembly Version: 2024.1.0.0
    Win32 Version: 2024.1.0.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/FastReport.DataVisualization.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FastReport.Data.Couchbase
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
FastReport.Data.Json
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/FastReport.Data.Json.DLL
----------------------------------------
FastReport.Data.Json
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Newtonsoft.Json.DLL
----------------------------------------
FastReport.Data.MongoDB
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
FastReport.Data.MySql
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
FastReport.Data.OracleODPCore
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
FastReport.Data.Postgres
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
FastReport.Data.SQLite
    Assembly Version: 2024.1.3.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
FastReport.DataVisualization
    Assembly Version: 2024.1.0.0
    Win32 Version: 2024.1.3.0
    CodeBase: file:///C:/Users/DJXCDS/Downloads/FastReport.Community.2024.1.3/Designer.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
rwp51ysa
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Data.Entity.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Entity.Design/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Entity.Design.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

is this a program error or just in my pc lacking required DLL file??

**Comment by Alekarfes** [comment]
Hello! I can't reproduce your issue using Community Designer 2024.1.10. Can you reproduce it on the last version?

**Comment by BogdanStegachev** [comment]
Hello!

When testing on the latest FastReport Community Edition this problem did not occur, you can upgrade to the current version 2025.1.0 and test again

If you still have questions, you can create a ticket for faster resolution of the problem at the following link: https://www.fast-report.com/support.

Best regards,
Bogdan
