### ISSUE TITLE
Unable to add Nuget package FastReport.OpenSource to .NET 8 project

### ISSUE THREAD

**Issue by exedor** [FastReports/FastReport#685]
**Is your feature request related to a problem? Please describe.**
When I try to add the Nuget package FastReport.OpenSource to my .NET 8 project, I get a lot of Version conflicts. Here is the output:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.5.0 directly to project SimManager to resolve this issue. 
 SimManager -> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0) 
 SimManager -> FastReport.OpenSource 2024.1.7 -> FastReport.Compat 2024.1.0 -> Microsoft.CodeAnalysis.VisualBasic 3.3.1 -> Microsoft.CodeAnalysis.Common (= 3.3.1).	SimManager	C:\Users\Jared\source\VoyagerPlatform\SimManager\SimManager.csproj	1	

**Describe the solution you'd like**
Support the latest development and keep up with Microsoft.

**Describe alternatives you've considered**
Other reporting frameworks.

**Additional context**
![Screenshot 2024-03-16 112550](https://github.com/FastReports/FastReport/assets/6391864/f4413992-ae33-40a6-9825-81b13f083474)

**Comment by NunesEvandrus** [comment]
The same thing happened to me, I just updated the packages and it worked normally

**Comment by Alekarfes** [comment]
If you're encountering this issue, update your packages.
