### ISSUE TITLE
The Title property of PDFSimpleExport is not setting the title on the resulting PDF page as expected.

### ISSUE THREAD

**Issue by wagenheimer** [FastReports/FastReport#686]
**Describe the bug**
The Title property of PDFSimpleExport is not setting the title on the resulting PDF page as expected.

**To Reproduce**
```
 public static FileContentResult ExportaPdf(Report report, string reportName)
  {
    FastReport.Export.PdfSimple.PDFSimpleExport pdfSimpleExport = new FastReport.Export.PdfSimple.PDFSimpleExport();
    pdfSimpleExport.ShowProgress = true;
    pdfSimpleExport.Subject = SanitizeName(reportName);
    pdfSimpleExport.Name = SanitizeName(reportName);
    pdfSimpleExport.Title = SanitizeName(reportName);

    MemoryStream stream = new MemoryStream();

    report.Report.Export(pdfSimpleExport, stream);
    stream.Flush();
    report.Dispose();
    pdfSimpleExport.Dispose();
    stream.Position = 0;

    return new FileContentResult(stream.ToArray(), "application/pdf");
  }
```

**Observed behavior**
The title on the PDF page displays strange characters.

Expected Behavior:

The title on the PDF page should match the value assigned to the Title property of the PDFSimpleExport object.

**Screenshots**
![image](https://github.com/FastReports/FastReport/assets/315513/7c54f4ba-123d-4f4f-a796-2cda15766ca1)

**Comment by BogdanStegachev** [comment]
Hello!

At the moment our developers are working on solving a similar problem, expect changes in the next versions of FastReport Community Edition

Best regards,
Bogdan
