### ISSUE TITLE
Some Chinese characters in the ubuntu system are displayed incorrectly

### ISSUE THREAD

**Issue by naruto1227** [FastReports/FastReport#687]
**Describe the bug**
When I used fastreport to generate a picture of the report, some Chinese characters were not displayed, but I added a few other characters in the middle of these characters that could not be displayed

**Device (please complete the following information):**
 - OS:Linux version 5.15.0-97-generic (buildd@lcy02-amd64-033) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024
 - version：      FastReport.OpenSource.Export.PdfSimple  2024.1.7

**Additional context**
![image](https://github.com/FastReports/FastReport/assets/43592384/fe333884-785d-4632-9099-f9ecc5ca386e)
![image](https://github.com/FastReports/FastReport/assets/43592384/778bf782-55d7-4f51-8242-378d3b9d420a)
![image](https://github.com/FastReports/FastReport/assets/43592384/81458ba7-5705-482a-afd3-3fd5920b3f6f)
I want to show 语言 These two Chinese characters，I can't display it directly, but I can display it if I insert a few characters in between

**Comment by Yamasiash** [comment]
Hello!

In your case I would recommend you to use Skia packages. The thing is that some characters may not be displayed correctly when using libgdiplus. You can read more here: 
https://www.fast-report.com/en/blog/show/fastreport-core-skia/
