### ISSUE TITLE
Container em Linux RadHat - .Net 8 - One or more errors occurred. (The type initializer for 'FastReport.Report' threw an exception.)

### ISSUE THREAD

**Issue by NunesEvandrus** [FastReports/FastReport#689]
**Describe the bug**
When I try to run FastReport in a RedHat Linux container I am getting the following error

{
"title": "Server Error",
"status": 500,
"detail": "One or more errors occurred. (The type initializer for 'FastReport.Report' threw an exception.)",
"errors": null
}

I'm using FastReport Community with .Net 8.0

Can anyone help?

**Comment by tiagovbp** [comment]
Fala @NunesEvandrus , voce conseguiu solucionar seu problema?

**Comment by PoomBE** [comment]
i use mac os have same problem. I use FastReport.Core.Skia.Demo and FastReport.OpenSoure.Export.PdfSimple is have bug version [CS0012](classifiedtextelementview-invokeaction:0): The type 'ExportBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'FastReport, Version=2024.2.1.0, Culture=neutral, PublicKeyToken=5ceb240df42bf6e8'. ( i am fix test Not use PDFSimpleExport and use baseexport  result is "" null )can help me or Which nuget do I need to install?

**Comment by BogdanStegachev** [comment]
Hello!

To work correctly under Linux, use FastReport.Core.Skia.Demo in your application
The packages you will need are:
FastReport.Core.Skia.Demo
then switch the package source to nuget.org for the packages you need:
HarfBuzzSharp.NativeAssets.Linux
SkiaSharp.NativeAssets.Linux

Best regards,
Bogdan
