### ISSUE TITLE
Add new Datasource mysql in designer.exe

### ISSUE THREAD

**Issue by ElvisHotz** [FastReports/FastReport#690]
**Describe the bug**
when creating a new datasource connection with mysql database I receive an error

**Screenshots**
![image](https://github.com/FastReports/FastReport/assets/11537876/b65f7604-617e-4734-94e2-f62b58f5ae93)

**Device (please complete the following information):**
 - OS: W11 64

**Comment by Yamasiash** [comment]
Hello!

We are aware of this problem and are trying to solve it. Keep an eye on the updates.
