### ISSUE TITLE
VisibleExpression on a Page is not working

### ISSUE THREAD

**Issue by Justin4fun** [FastReports/FastReport#691]
**Describe the bug**
The Property VisibleExpression on a Page is not working

**To Reproduce**
1. Go to Page2 set the Page VisibleExpression to 1==0
2. Preview Page (Crtl+P)

**Expected behavior**
Is that the Page is not visible. 

**Screenshots**

**Device (please complete the following information):**
 - OS: wininwos 10

 - Version fast report.net 2012.4.15

**Additional context**
Note there is no difference if page property visibility is set to true or false.
VisibleExpression to 1==1 also does not work if is visibility is set to  false.

Id also be interested in a workaround since i am suck with this version please mail to justin@fun.builders

**Comment by Alekarfes** [comment]
Cannot be reproduced on v2021.1.10
