### ISSUE TITLE
TextObject Automatic line wrapping one more-character

### ISSUE THREAD

**Issue by fzwu** [FastReports/FastReport#696]
We found a problem when using fastreport. When the text content is continuous English, automatic line wrapping will automatically add a-character.

Previously, using .NET Core 3.1, automatic line wrapping was correct. After upgrading to .NET 6, automatic line wrapping automatically adds a-character at the end of the line.

I learned that fastreport depends on System.Drawing.Common, but .NET 6 does not support it on non-windows platforms. 
Is it caused by this problem? 
What plan do we have to deal with this problem?

**Comment by fzwu** [comment]
![image](https://github.com/FastReports/FastReport/assets/16144784/7b2b8123-0dc6-4ad8-a55b-ff6fe5d8beba)

**Comment by BogdanStegachev** [comment]
Hello!

To solve your problem you can use FastReport.Core.Skia in your application (if you are using FastReport on Linux).

And also additional packages:

HarfBuzzSharp.NativeAssets.Linux
SkiaSharp.NativeAssets.Linux

I also send you the application for testing

Application: https://drive.google.com/file/d/1qkO0mOYJMvDba0QlBPApJazmRaPKlZOF/view?usp=sharing

If you have additional questions, you can create a ticket for a faster response at the following link: https://www.fast-report.com/support.

Best regards,
Bogdan
