### ISSUE TITLE
Only authenticationclearpassword And authenticationMD5password are supported for now,received 10. when try to connect to postgres db

### ISSUE THREAD

**Issue by gghattis** [FastReports/FastReport#697]
**Authentication with postgres issue**
Only authenticationclearpassword And authenticationMD5password are supported for now,received 10. when try to connect to postgres db
![image](https://github.com/FastReports/FastReport/assets/120364037/a881f1ad-5523-4e92-81cd-f28d7df58b9b)

**To Reproduce**
1. Go to 'Add Data Source'
2. Click on 'New Connection'
3. Scroll down to 'postgres'
4. See configuration attached below 
5. 
![image](https://github.com/FastReports/FastReport/assets/120364037/795e3483-1fd2-481a-b987-26d68fdd9701)

**Expected behavior**
Fastreport should open the connection with the database and show me the tables

**Stacktrace**
- ...
- ...

**Screenshots**
![image](https://github.com/FastReports/FastReport/assets/120364037/7152da7e-b1de-4fbe-a0c4-bb73d3e7f577)

**Device (please complete the following information):**
 - OS: windows 10 64bits
 - Browser [Chrome]

**Additional context**

**Comment by BogdanStegachev** [comment]
Hello!

When testing on the new FastReport Community Edition, this problem was not reproduced on our test connection

Could you please update and if this problem is reproduced create a ticket on the following path for faster response: https://www.fast-report.com/support.

Best regards,
Bogdan
