### ISSUE TITLE
FastReport.OpenSource

### ISSUE THREAD

**Issue by VladislavChastnokov** [FastReports/FastReport#698]
I installed FastReport.OpenSource NuGet package for a net6.0 WinForms Application
Trying to show empty report as a test, but there aren't methods Show or ShowPrepared, despite them being referenced in the commentary to Report class.

**Comment by BogdanStegachev** [comment]
Hello!

For testing using the report designer and report preview, you will be able to install the built application at the link: https://github.com/FastReports/FastReport/releases/tag/v2025.1.0.

In your application you will be able to use the FastReport.Net.Demo nuget package

Best regards,
Bogdan
