### ISSUE TITLE
how to change style of loading animation

### ISSUE THREAD

**Issue by ahuiiiiiii** [FastReports/FastReport#700]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

when report is init loading or refresh report. this style of loading animation how to change in code?

**Comment by BogdanStegachev** [comment]
Hello!

At the moment animeyu downloading a report or downloading the total number of prepared pages is not available in FastReport

Best regards,
Bogdan
