### ISSUE TITLE
error datasource MySQL connection for MariaDB

### ISSUE THREAD

**Issue by anovsiradj** [FastReports/FastReport#701]
**Describe the bug**
i am trying to connect to MariaDB datasource using `MySQL Connection` using `Designer.exe` from `FastReport.Community.2024.2.0.zip`.

but i dont know why, i can connect to MariaDB using `Designer.exe` from `FastReport.Community.2023.3.0.zip`.

**To Reproduce**
- Data
- Add Data Source
- New Connection
- choose MySQL Connection
- (fill host,user,pass,dbname)
- click Ok or "Test Connection"

**Expected behavior**

**Stacktrace**
- ...
- ...

**Screenshots**
![image](https://github.com/FastReports/FastReport/assets/6737021/df41d371-235a-4d55-9baa-3e2b29b3fe84)

**Device (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: FastReport.Community.2024.2.0.zip
 - MariaDB: 11.3.1-MariaDB

**Additional context**

**Comment by netenken** [comment]
I got the same problem here..
![Snipaste_2024-05-27_18-07-31](https://github.com/FastReports/FastReport/assets/71846631/46b55c93-d8ba-4129-ab70-e23b1c51ec86)

Device (please complete the following information):

OS: Windows 10 Pro
Version: FastReport.Community.2024.2.0.zip
DB: even no need to enter server address, just press test button , the error occured

**Comment by sifaqes** [comment]
In fact, I have the same problem. I suspect that the program is unable to read the MySQL Data client

**Comment by luizppuhl** [comment]
Estou com o mesmo problema, alguém chegou a alguma concluisão
