### ISSUE TITLE
PDF Rendering Issue in all versions after 2024.1.3 on Linux

### ISSUE THREAD

**Issue by mohamedalrshah** [FastReports/FastReport#703]
PDF Rendering Issue in all versions 2024.1.10, 2024.2.0, and 2024.2.1 on Linux (some of the report content is not rendered)

**To Reproduce**
when I use version 2024.1.3 everything works fine but when I change to version 2024.1.10, 2024.2.0 or 2024.2.1 some parts of the reports disappear without any change in other code

**Expected behavior**
It is supposed to work properly on all versions.

**Screenshots**
with version 2024.1.3
![Version 2024 1 3 - OK](https://github.com/FastReports/FastReport/assets/24998514/d97a228c-838b-415f-ac4c-5bad03ced77d)

with versions 2024.1.10, 2024.2.0 and 2024.2.1
![Versions after 2024 1 3 - NOT OK](https://github.com/FastReports/FastReport/assets/24998514/d4fc5201-2a7c-4591-addb-ca73e978c603)

**Device (please complete the following information):**
 - OS: Rocky Linux 9.4
 - Browser Chrome and Edge
 - Version; all

**Comment by BogdanStegachev** [comment]
Hello!

Could you please send us your test report for testing and also the font used in your report, if you can also upgrade to the current version of FastReport and let us know the results

Also, to get a faster response you can create a ticket for our support department: https://www.fast-report.com/support.

Best regards,
Bogdan

**Comment by mohamedalrshah** [comment]
Hi Bogdan

Oh! you remembered to reply now! It has been about 6 months since we
suffered from the problem and we waited with no response.
So, we did our own solution.

Anyway, thanks for the response.

Regards.




*Assis. Prof. Dr. Mohamed A. Alrshah.IEEE Senior Member.Senior Lecturer at
the Department of Networks,Faculty of Computer Science and Information
Technology,*
*AL Asmarya Islamic University, Zliten, Libya*

***@***.*** ***@***.***>***@***.***
***@***.***>*
*+218-91-320-6229*
