### ISSUE TITLE
Unable to deploy fast report open source in linux

### ISSUE THREAD

**Issue by m3dbedb** [FastReports/FastReport#707]
**Describe the bug**
I have created ASP web app, added packages `FastReport.OpenSource` and `FastReport.OpenSource.Web` but it does not start.

**To Reproduce**
1. install dotnet 8 ($ sudo apt-get install -y dotnet-sdk-8.0)
2. create project (~ $ mkdir asp-fastreport && cd asp-fastreport && dotnet new wabapp)
3. add fastreport (asp-fastreport $ dotnet add package FastReport.OpenSource --version 2024.2.1 && dotnet add package FastReport.OpenSource.Web --version 2024.2.1)
4. asp-fastreport $ dotnet run
5. I see default AST NET we app home page

**Expected behavior**
I expect to see default fastreport home page

**Device:**
 - OS: debian 12
 - Browser: chrome
 - Version: 2024.2.1

**Comment by m3dbedb** [comment]
update: now I follow steps 1-4, the project starts successfully, bu I see only asp net default home page. How to see fasreport demo report?

**Comment by m3dbedb** [comment]
Also if I download nuget packages from https://github.com/FastReports/FastReport/releases 

mkdir ~/fastreport-compiled && cd fastreport-compiled && dotnet new webapp

~/downloads $ wget https://github.com/FastReports/FastReport/releases/download/v2024.2.0/FastReport.OpenSource.2024.2.0.nupkg
~/downloads $ wget https://github.com/FastReports/FastReport/releases/download/v2024.2.0/FastReport.OpenSource.Web.2024.2.0.nupkg

dotnet add package ~/downloads/FastReport.OpenSource.2024.2.0.nupkg

info : Adding PackageReference for package '/home/username/downloads/FastReport.OpenSource.2024.2.0.nupkg' into project '/home/gagarin/fastreport-compiled/fastreport-compiled.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2//home/username/downloads/fastreport.opensource.2024.2.0.nupkg/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2//home/username/downloads/fastreport.opensource.2024.2.0.nupkg/index.json 962 мс
info :   GET https://api.nuget.org/v3/registration5-gz-semver2//home/username/downloads/fastreport.opensource.2024.2.0.nupkg/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2//home/username/downloads/fastreport.opensource.2024.2.0.nupkg/index.json 286 мс
error: There are no versions available for the package '/home/username/downloads/FastReport.OpenSource.2024.2.0.nupkg'.

**Comment by BogdanStegachev** [comment]
Hello!

I am sending you a test application with FastReport.MVC.6.0 application working correctly and using FastReport.Core.Skia.Demo and Online Designer Trial test suites

Application: https://drive.google.com/file/d/1qkO0mOYJMvDba0QlBPApJazmRaPKlZOF/view?usp=sharing

You can also see how to correctly run FastReport.Core on Linux in our article: https://www.fast-report.com/blogs/use-fastreport-core-linux.

Best regards,
Bogdan
