### ISSUE TITLE
Unable to add user-compiled package to asp web application project

### ISSUE THREAD

**Issue by m3dbedb** [FastReports/FastReport#708]
**Describe the bug**
Error while importing user-compiled fast report package

**To Reproduce**
1. ~ $ git clone https://github.com/FastReports/FastReport.git
2. cd ~/FastReport
3. ~/FastReport $ chmod 777 ./pack.sh && ./pack.sh 
_original guide is wrong (chmod 777 Tools/pack.sh && Tools/pack.sh)_
4. $ mkdir ~/project1 && cd ~/project1 && dotnet new webapp && dotnet add package ~/FastReport/fr_packages/FastReport.OpenSource.2021.4.15.nupkg
5. See error 

Determining projects to restore...
  Writing /tmp/tmp6I5jga.tmp
info : Adding PackageReference for package '../FastReport/pack/FastReport.OpenSource.2021.4.15.nupkg' into project '/home/username/frep/frep.csproj'.
info :   GET https://api.nuget.org/v3/fastreport/pack/fastreport.opensource.2021.4.15.nupkg/index.json
info :   NotFound https://api.nuget.org/v3/fastreport/pack/fastreport.opensource.2021.4.15.nupkg/index.json 5496 мс
info :   GET https://api.nuget.org/v3/fastreport/pack/fastreport.opensource.2021.4.15.nupkg/index.json
info :   NotFound https://api.nuget.org/v3/fastreport/pack/fastreport.opensource.2021.4.15.nupkg/index.json 266 мс
error: There are no versions available for the package '../FastReport/pack/FastReport.OpenSource.2021.4.15.nupkg'.

**Expected behavior**
I expect compiled package to be added to project like it happens when I add it from web 
`dotnet add package FastReport.OpenSource --version 2024.2.1`

**Device (please complete the following information):**
 - OS: debian 12
 - Browser: chrome
 - Version: latest on branch master

**Comment by BogdanStegachev** [comment]
Hello!

Could you please let me know if this behaviour is reproduced on the current version of FastReport Community Edition?

Best regards,
Bogdan
