### ISSUE TITLE
Unable to run FastReport/Demos/OpenSource/MVC/FastReport.OpenSource.MVC.6.0

### ISSUE THREAD

**Issue by m3dbedb** [FastReports/FastReport#710]
**Describe the bug**
Build errors

**To Reproduce**
1. ~ $ git clone https://github.com/FastReports/FastReport.git
2. cd ~/FastReport/Demos/OpenSource/MVC/FastReport.OpenSource.MVC.6.0
3. dotnet add package FastReport.OpenSource --version 2024.2.1
4. dotnet add package FastReport.OpenSource.Web --version 2024.2.1
4. FastReport.OpenSource.MVC.6.0 $ dotnet run
5. See errors:

> Unhandled exception. System.Exception: Please, register FastReport services in DI container. Use services.AddFastReport()
>   at Microsoft.AspNetCore.Builder.FastReportBuilderExtensions.FastReportServicesCheck(IServiceProvider serviceProvider)
>   at Microsoft.AspNetCore.Builder.FastReportBuilderExtensions.SetupFastReport(Action`1 setupAction, IServiceProvider serviceProvider)
>   at Microsoft.AspNetCore.Builder.FastReportBuilderExtensions.UseFastReport(IApplicationBuilder app, Action`1 setupAction)
>   at Demo.MVC.Net6.Program.Main(String[] args) in /home/username/FastReport/Demos/OpenSource/MVC/FastReport.OpenSource.MVC.6.0/Program.cs:line 35

**Expected behavior**
I expect to see demo report in web browser

**Device (please complete the following information):**
 - OS: debian 12 amd64
 - Browser: chrome
 - Version: 2024.2.1

**Comment by MOHAMEDALEEM** [comment]
Yes getting same issue do you  get any solution or any other reporting tool to use

**Comment by BogdanStegachev** [comment]
Hello!

I am sending you a test application with FastReport.MVC.6.0 application working correctly and using FastReport.Core.Skia.Demo and Online Designer Trial test suites

Application: https://drive.google.com/file/d/1qkO0mOYJMvDba0QlBPApJazmRaPKlZOF/view?usp=sharing

You can also see how to correctly run FastReport.Core on Linux in our article: https://www.fast-report.com/blogs/use-fastreport-core-linux.

Best regards,
Bogdan

**Comment by JGuerrero238** [comment]
Hi, you need to place the sentence " builder.Services.AddFastReport();" before the  sentence "var app = builder.Build();" into program.cs
