### ISSUE TITLE
Problem with report by Dot Matrix printer

### ISSUE THREAD

**Issue by Mydeartp** [FastReports/FastReport#712]
Hi,

" I have problem with pdf report when I create report with FastReport and print by Dot Matrix printer. "

I create report from FastReport Avalonia Designer and saved the .frx file.

Then, I create pdf report from .frx file (FastReport.OpenSource.Export.PdfSimple).

This is downloaded pdf file
<img width="974" alt="ภาพถ่ายหน้าจอ 2567-08-06 เวลา 22 10 32" src="https://github.com/user-attachments/assets/040af656-d281-412d-bb7e-f2dd8a87bdee">

But this is report from printer
![IMG_9943](https://github.com/user-attachments/assets/bb927262-2096-4972-8e1c-c451240ed0ed)

The report from printer is dots lined up but I need obvious report look like a laser printer.

Please help me ﻿😥﻿😬

- Printer : Fujitsu DL7600 pro (continuous paper)

- Designer : Avalonia V 11.0

- MacOS 14.1.1, M2

- FastReport.OpenSource.Export.PdfSimple 2024.2.1

**Comment by BogdanStegachev** [comment]
Hello!

Could you please test your report on the FastReport .NET Avalonia demo application

Download link: https://www.fast-report.com/downloads/fast-report-net

We will be looking forward to your feedback!


Best regards,
Bogdan
