### ISSUE TITLE
I am getting an error: Can't find object MsSqlConnection.

### ISSUE THREAD

**Issue by krisbvega** [FastReports/FastReport#715]
**Describe the bug**
I used the Load function to open an frx file and I kept getting the said error message.

**To Reproduce**
1. Create a Windows application project with target framework .NET 8.0 (I am using VS 2022 Community Edition)
2. Get NuGet Package FastReport.Opensource v.2024.2.14
3. Write a code load a frx report design in Designer app where the Data Source connection used is MS SQL.

**Expected behavior**

**Screenshots**
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/d8bf554e-5a0a-4af6-aec2-4efd776828a7">
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/bce1f9eb-fbdb-4d5a-81db-4cb25bbaf88a">
<img width="1316" alt="image" src="https://github.com/user-attachments/assets/711fb97e-5112-4262-9d71-a66fe6049a57">
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/c23b741b-09bc-4c35-b9b3-9ac15454591d">
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/306aa144-5bc1-4508-81e7-a6aafa45609f">

**Device (please complete the following information):**
 - OS: MacOS (I am using Parallels Virtualization app)
 - Visual Studio 2022 Community Edition
 - Fastreport.Opensource (2024.2.14)

**Comment by ferriforty** [comment]
Did you find a solution for this problem?

**Comment by ferriforty** [comment]
If you want, i solved the problem.
You just need to add before the Report.Load() this line here.

RegisteredObjects.AddConnection(typeof(MsSqlDataConnection));

**Comment by krisbvega** [comment]
I’ll give it a try. Thanks for reaching out, very much appreciated.

Best Regards,

Kristoferson Vega
