### ISSUE TITLE
.NET 8 support

### ISSUE THREAD

**Issue by Bykiev** [FastReports/FastReport#718]
Hi, I see only .net 6 is supported, it will reach EOL on November, 12. Will be the community edition updated to support .net 8 LTS version? `System.Drawing.Common` library is not supported anymore on Linux.

**Comment by Bykiev** [comment]
I did some research and `System.Drawing` part can be copied from [mono](https://github.com/mono/mono/tree/main/mcs/class/System.Drawing) project. It relies on GDI+ and works on Windows and Linux. In the future it can be rewritten with `ImageSharp` or `SkiaSharp`

**Comment by WBHWebDev** [comment]
Hi there,

could you please explain how you managed to get FastReport OpenSource working with Blazor? 
Did you use .NET 8 or an earlier version? 

Did you just copy the .dll files into your application folder, or were there additional steps or configurations involved?
Also, on which Linux distribution did you test this setup? 

Thanks in advance!

**Comment by Bykiev** [comment]
@WBHWebDev, hi! 
You seems misunderstood my issue, I didn't make it working on Linux. I'm asking the developers why did they decided to support only Windows, while the open-source implementation of System.Drawing in mono is exists.

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by BogdanStegachev** [comment]
Hello!

In the near future there are no plans to implement SkiaSharp in FastReport Open Source, you can implement this functionality yourself or use our commercial version of FastReport.Core.Skia and FastReport.Web.Skia packages.

For testing you can use demo packages that you can install from nuget.org package source.

You will be able to create a PR after which our developers will review it

Best regards,
Bogdan
