### ISSUE TITLE
Is there any way to use FastReport OpenSource on linux with .net8 ?

### ISSUE THREAD

**Issue by jianliulin** [FastReports/FastReport#726]
Is there any way to use FastReport OpenSource on linux with .net8 ?

**Comment by klindger** [comment]
UP

**Comment by BogdanStegachev** [comment]
Hello!

FastReport.Opensource does not support development for Linux. System.Drawing.Common, starting with version 7.0, will completely stop supporting non-Windows systems, so the examples of libgdiplus given above will soon not work at all.
Only the commercial version of FastReport.Core.Skia has support.
See here:
https://www.fast-report.com/en/blog/show/fastreport-core-skia/

You will be able to test demo Nuget packages FastReport.Core.Skia and FastReport.Web.Skia in your application for correct work under Linux, you will also need additional packages:

HarfBuzzSharp.NativeAssets.Linux
SkiaSharp.NativeAssets.Linux

Best regards,
Bogdan

**Comment by printferlang** [comment]
you just need install `libgdiplus` in your linux.

**Comment by WBHWebDev** [comment]
> you just need install `libgdiplus` in your linux.

Have you tried this successfully? Does this works with .NET 8?

**Comment by BogdanStegachev** [comment]
Hello!

I am sending you a test application with FastReport.MVC.6.0 application working correctly and using FastReport.Core.Skia.Demo and Online Designer Trial test suites

Application: https://drive.google.com/file/d/1qkO0mOYJMvDba0QlBPApJazmRaPKlZOF/view?usp=sharing

You can also see how to correctly run FastReport.Core on Linux in our article: https://www.fast-report.com/blogs/use-fastreport-core-linux.

Best regards,
Bogdan
