### ISSUE TITLE
For DataBand in .frx saves the DataSource, not the Alias

### ISSUE THREAD

**Issue by mon4github** [FastReports/FastReport#728]
![DS1](https://github.com/user-attachments/assets/1a562ccb-32b6-4f62-8ad4-b30806abbc02)

The example is made for demonstration.
DataSources were created for oracle, then they were renamed, the name was registered in Alias.
In .frx, Alias appears everywhere except DataBand, the original name is written into it, but fields are accessed by alias:
```
<DataBand Name="Data2" Top="187.1" Width="1047.06" Height="18.9" DataSource="GET_EMPLOYEES_BY_SALARY_WRAP">
...
  <TableCell Name="T4Cell1" Border.Lines="All" Text="[EmployeesBySalary5_10.EMPLOYEE_ID]" Font="Arial, 10pt"/>
```     
Sometimes it is necessary to add a procedure call with the same name, but with different parameters, with data output to a different DataBand. But when saving a report, the same DataSource is registered to both DataBands.

На русском:
Пример сделан для демонстрации.
Созданы DataSource к oracle, затем они были переименованы, имя прописалось в Alias.
На скриншоте и в frx везде фигурирует Alias в том числе для полей в TextObject и TableCell.
А в DataBand в frx в него записывается первоначальное имя: 
```
<DataBand Name="Data2" Top="187.1" Width="1047.06" Height="18.9" DataSource="GET_EMPLOYEES_BY_SALARY_WRAP">
...
  <TableCell Name="T4Cell1" Border.Lines="All" Text="[EmployeesBySalary5_10.EMPLOYEE_ID]" Font="Arial, 10pt"/>
```      
Иногда требуется добавить вызов процедуры с тем же именем, но с другими параметрами с выводом данных в другой DataBand. Но при сохранении отчета в оба DataBand прописывается один и тот же DataSource.

**Comment by BogdanStegachev** [comment]
Hello!

This behaviour is not an error as the report only saves the changes that occurred in the report itself and related data from the ‘database’.
All other changes to data not related to the report are updated to system values.

Best regards,
Bogdan
