### ISSUE TITLE
Report designer error on mysql add Source

### ISSUE THREAD

**Issue by pam60** [FastReports/FastReport#729]
**Describe the bug**
Creating a new datasource connection on Designer (offline) produces error

**To Reproduce**
1. Go to 'Data'
2. Click on 'Add Datasource'
3. Fullfill connection info
4. Click on Test Connection
5.  See Error

**Expected behavior**
A Connection to a database added

**Screenshots**
![image](https://github.com/user-attachments/assets/6510c8ea-4a93-4b5f-a12e-69f06202791d)

**Device (please complete the following information):**
 - OS: Windows 
 - Version 11

**Comment by pam60** [comment]
My apologies, I just now realized there was another thread on the same subject.

**Comment by BogdanStegachev** [comment]
Hello!

Thank you for your request, I have reproduced the problem described above and started a task in our development department, expect changes in the next versions of FastReport Community Edition

Best regards,
Bogdan
