### ISSUE TITLE
I wanna to set a custom font in fastreport by C#.net. I can set the font by  FastReport.FontManager.AddFont , but How I can config the font in my report?

### ISSUE THREAD

**Issue by machavo** [FastReports/FastReport#730]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BogdanStegachev** [comment]
Hello!

Our developers have solved this problem in the latest versions of FastReport, after adding a font using FontManager it will appear in the list of available fonts 

You will be able to test on the latest version of FastReport.Net.Demo. 

Best regards,
Bogdan
