### ISSUE TITLE
SVG picture with gradient

### ISSUE THREAD

**Issue by VVKot** [FastReports/FastReport#77]
Does FastReport support SVG images with a gradient?

I have the following [image](https://drive.google.com/open?id=1DAHV7lQv3DCOA38KlyrhfJ4Q0Cm0tcVc) with `linearGradient` in it. If I add it to the template, I can see it in Preview. But when I generate the actual report - there is no picture, only a blank space. Is it some limitation of a trial version?

**Comment by Detrav** [comment]
Hi, I do not understand the question a bit.
Currently, SVG is only supported in the full version.

**Comment by 8VAid8** [comment]
Hello!
Do you use web-report or desktop application?
What do you mean by "generate the actual report ": preview on desktop, preview on Web, or some export(which one)?

**Comment by VVKot** [comment]
@Detrav I'm using the trial version for this one.
@8VAid8 I use a desktop designer. It is okay in preview on the desktop. By "actual report" I mean the export, I rechecked, and I believe this issue is specific to export to PDF.

**Comment by VVKot** [comment]
UPD. It works if I use:
```
new PDFExport {
    SvgAsPicture = true
}
```
Is this an intended way to use it?

**Comment by 8VAid8** [comment]
Yes, you can use it in this way. You'll get svg as a picture (not a vector).
We'll debug this behavior for specified SVG and fix it.
