### ISSUE TITLE
Header and footer in *.docx

### ISSUE THREAD

**Issue by VVKot** [FastReports/FastReport#78]
Is it possible to create "native" header and footer in the designer? For now, I am only able to place the content in the top or the bottom of the page within the table.

**Comment by fediachov** [comment]
Hi!

FastReport Open Source does not have an export in DOCX, but you can create "native" header/footer in Word 2007 export in full version of FastReport .NET. You need select the "Paragraphs" option or set from code:
`Word2007Export.ParagraphBased = true;`
![изображение](https://user-images.githubusercontent.com/43993341/55535229-3639a300-56bf-11e9-8cde-010cf7779a74.png)

The paragraph based export in Word may have some inaccuracies in the appearance of the document.
