### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by khoshroomahdi** [FastReports/FastReport#79]
Is there any road map?

**Comment by fediachov** [comment]
Hi,

We will publish our road map shortly. I'll inform you when it be ready.

**Comment by fediachov** [comment]
Our product road map:

- [ ] FIrebird Database Support
- [ ] System.Drawing.Common instead CoreCompat.System.Drawing
- [ ] Direct Print
- [ ] SVG Support
- [ ] Maps Support
- [ ] Charts Support

**Comment by marcosgerene** [comment]
@fediachov
> Direct Print 

Has a forecast for this?

**Comment by fediachov** [comment]
> Has a forecast for this?

This feature will available for implementation after release of .NET CORE 3.0

**Comment by viegasfh** [comment]
@fediachov , is anyone working on the Firebird Database Connector? If no one is working on it, I would like to start implementing support for it.

**Comment by 8VAid8** [comment]
@viegasfh, have you seen this - https://github.com/FastReports/FastReport/tree/master/Extras/Core/FastReport.Data/FastReport.Data.Firebird ?

**Comment by viegasfh** [comment]
@8VAid8 , thanks for the pointer! I cloned the repository and loaded the solution in Visual Studio, but unfortunately the Firebird Connector wasn't loaded. 

Thanks once again! I will have a look at it.

**Comment by marcosgerene** [comment]
@fediachov 

What is the current status?

Did you mention that DirectPrint was waiting for .Net Core 3 ... anything new?

**Comment by calFSA** [comment]
Hi,

Any predictions for charts in the open source version, even if it is simple?

**Comment by araujofrancisco** [comment]
What is the current status for blazor support? Any estimates on when it will be available?

**Comment by germgh0st** [comment]
Is there any update on Blazor support, do you have a timeframe in mind for this?

Also as of .Net 6 System.Drawing.Common is no longer supported on anything but Windows, as I imagine you already know. However when deploying apps to the likes of Azure the environment may not always be a Windows server, so we avoid using System.Drawing.Common in any web app that we develop and we avoid any component that depends upon it. Could the road map for this assembly be expanded to include all development platforms?

**Comment by BogdanStegachev** [comment]
Hello!

Blazor support is not planned in the current version of FastReport.Community, System.Drawing.Common is used in our FastReport.Core and FastReport.Net applications except FastReport.Core.Skia which will get its demo package soon

Best regards,
Bogdan
