### ISSUE TITLE
I could not download designer.exe

### ISSUE THREAD

**Issue by eliezeralmeida** [FastReports/FastReport#8]
![design-download](https://user-images.githubusercontent.com/2786448/47608786-cd604780-da09-11e8-96b8-4fb4f0c61982.png)

![design-download-2](https://user-images.githubusercontent.com/2786448/47608828-68592180-da0a-11e8-8752-a1e89e050838.png)

![defender](https://user-images.githubusercontent.com/2786448/47608830-6e4f0280-da0a-11e8-9895-bf9fe3c59c19.png)

### translation of the above image

Alert Level: Severe
Status: In Quarantine
Date: 10/27/2018

Action: Remove the threat now.

Category: Trojan horse
Details: This program is dangerous and runs the commands of an attacker.

**Comment by fediachov** [comment]
Hi,

The Designer works fine for me. This is a false antivirus reaction. I have checked the just downloaded file with online antivirus. It found nothing.
![capture-jotti-designer](https://user-images.githubusercontent.com/43993341/47609056-b1c46380-da40-11e8-9a09-d31eb5ccfc4b.PNG)

**Comment by eliezeralmeida** [comment]
thx, i will make other attempts.

**Comment by fediachov** [comment]
What browser did you use?

**Comment by eliezeralmeida** [comment]
chrome, i tried in firefox. I will try another internet, it my be vulnerability in the current

**Comment by fediachov** [comment]
The problem may be due to the lack of digital signature of executable file and packed internal structure (all libraries in one executable).

**Comment by Detrav** [comment]
Hi, our certificates for signing exe files are now on renewal, at the moment I have packed the exe files into the archive, as soon as we receive the new certificate, we will sign the exe files.

Scanned files with antivirus:

[Designer](https://www.virustotal.com/en/file/af9f7db2b19aca9d8fa64e0fa99dd7f8fd5fb2493ee40703feade118da87984e/analysis/1540797357/)
[Viewer](https://www.virustotal.com/en/file/19df3f82b0c8347eff75f0d07f9c67ee2c2c0a029c2bf1863d91e9e9e71a6b99/analysis/1540797525/)

**Comment by eliezeralmeida** [comment]
cool, I will disable the antivirus and download them
