### ISSUE TITLE
Export.PdfSimple should have a net40 target

### ISSUE THREAD

**Issue by Yitzchok** [FastReports/FastReport#81]
PdfSimple targets only netstandard2.0 which causes it to have a dependency on CoreCompact even for .Net framework builds.

Adding a net40 target will fix this by changing 

```
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
</PropertyGroup>
```

to 

```
<PropertyGroup>
    <TargetFrameworks>net40;netstandard2.0</TargetFrameworks>
</PropertyGroup>
```

**Comment by fediachov** [comment]
Hi,

Thanks for your message. I did it https://github.com/FastReports/FastReport/commit/bbad9e3416c6a14a3fd31229442f6ca49fce5b5f

**Comment by Yitzchok** [comment]
You need to change it to end with s like TargetFrameworks

Also probably add it to the rest project.

**Comment by Detrav** [comment]
Fixed <https://github.com/FastReports/FastReport/commit/15a39059d73fd48a02b741714805cdf551b9052e>
```
<PropertyGroup>
  <TargetFrameworks>net40;netstandard2.0</TargetFrameworks>
</PropertyGroup>
