### ISSUE TITLE
Question: PDFSimpleExport results in an image-pdf

### ISSUE THREAD

**Issue by miseeger** [FastReports/FastReport#86]
First of all: Thank you very much for the PDFSimpleExport in your Open Source version of FastReport :-) But I've got a question: Is it intended that the exported PDF results in a non-searchable image-dump, wrapped into a PDF, or did I miss some important things to configure?

**Comment by Detrav** [comment]
Hello! Sorry for the late reply. Yes, there are many limits for Simple PDF. No search, minimum properties, exported for preview. Full-featured export to PDF is available in a commercial version.
