### ISSUE TITLE
Error in Preview of QR Barcode

### ISSUE THREAD

**Issue by andrewva** [FastReports/FastReport#87]
I receive an error if I choose `Preview` and my report contains QR Barcode with Nullable Enum Value.

![1](https://user-images.githubusercontent.com/6544702/56499506-5ebefb00-650f-11e9-818f-9fab80c6de00.PNG)

Here is the exception that I'm getting.
![3333](https://user-images.githubusercontent.com/6544702/56499507-5ebefb00-650f-11e9-94cf-668f2ef91473.PNG)

`Result` is a pretty simple object with one property `Result` that has Nullable Enum Type with `NULL` value (value by default).

Is it an issue or I'm missing something?

**Comment by Detrav** [comment]
Hi! I think this is a bug. Thank you for contacting.  We'll test and fix this.

**Comment by andrewva** [comment]
@Detrav great, thank you!

**Comment by KirillKornienko** [comment]
@andrewva Hi, sorry for the long wait. Tell me more about your problem in more detail with examples in the code with the definition Result.Result. If you use the Nullable Enum type as data, you must refer to the Value field.
![image](https://user-images.githubusercontent.com/40214463/60704944-83235480-9f0e-11e9-9a66-b6116db73d90.png)
