### ISSUE TITLE
Watermark in PDFSimpleExport doesn't fill the page

### ISSUE THREAD

**Issue by idaviddesmet** [FastReports/FastReport#88]
As the title says, the watermark is not filling the entire page, the exported pdf result is as follows:

![report as pdf](https://user-images.githubusercontent.com/2607383/57737758-6b4bf480-7672-11e9-92f1-8e999e9d8bb3.png)

While exporting as html results in:

![report as html](https://user-images.githubusercontent.com/2607383/57737762-70a93f00-7672-11e9-933e-643947b7b4a7.png)

**Comment by Detrav** [comment]
Hi, this is a bug, we will fix it

**Comment by idaviddesmet** [comment]
@Detrav could you take a look at PR #90 
It would mean a lot if you could push the update to Nuget after the merge is done.

Thanks in advance!

**Comment by idaviddesmet** [comment]
Here's a report frx repro.
[report.zip](https://github.com/FastReports/FastReport/files/3183430/report.zip)

**Comment by Detrav** [comment]
The package have just passed all test stages and published on nuget, it will be available in the next few hours.
<https://www.nuget.org/packages/FastReport.OpenSource.Export.PdfSimple/2019.3.1>

**Comment by idaviddesmet** [comment]
Excellent news,
Thank you very much! 🙂
