### ISSUE TITLE
What is FastReport Designer Community Edition

### ISSUE THREAD

**Issue by Tviljan** [FastReports/FastReport#9]
What is FastReport Designer Community Edition?

In the  [readme file](https://github.com/FastReports/FastReport#working-with-report-templates) it says that FastReport Designer Community Edition can be used to create the templates. What is it? How does it compare to online designer?

What is the license on it and what are the requirements to use it?

**Comment by fediachov** [comment]
Hi,

FastReport Designer Community Edition is created specially for working with FastReport Open Source templates. It works only in Windows. FastReport Designer Community Edition is based on retail sources but it have some limitations: printing and exporting features, [some objects are missing](https://fastreports.github.io/FastReport.Documentation/COMPARISON.html).  You can you FastReport Designer Community Edition and Viewer Community Edition for free.

FastReport Online Designer is commercial product for working with reports in the web browser. It have not Community edition at the moment.

**Comment by ilivecoding** [comment]
it's a desptop application(.exe)
