### ISSUE TITLE
Get Fast Report.NET Data Sources meta data after that saved

### ISSUE THREAD

**Issue by MrShaghaghi** [FastReports/FastReport#91]
In normal case everything is good,But if user in designer form, add new connection with new data source, that not exists in my first dataset, after saved ".frx" file, In next time when i load that changed ".frx" file,I am getting this error:

Table is not connected to the data. Register the data using Report.RegisterData method.

Because i don't know which data source was added by user out of may dataset and could not registered them completely. I have to do read ".frx" file as XML, and create datasouce from TableDataSource tag attributes. Is there a simpler way for recover and fill Get Report DataSource and Relations meta data after saved by user and registered them easily in RegisterData method?

**Comment by fediachov** [comment]
Hi!

Initially, the full version of the product could open the report template designer directly from the Wiindows Forms application with already registered data using Report.RegisterData. A similar trick is possible with an online designer. 

At the moment we cannot yet offer a convenient mechanism for editing such reports in an external designer. Thank for issue! We will think about this problem.

**Comment by MrShaghaghi** [comment]
Thank's a lot.
