### ISSUE TITLE
Can you give me the  example of chart with .net framework

### ISSUE THREAD

**Issue by yuhangli1991** [FastReports/FastReport#95]

**Comment by fediachov** [comment]
Hi,
FastReport Open Source don't have chart support yet/ But you can use it in FastReport .NET
https://fastreports.github.io/FastReport.Documentation/COMPARISON.html

Also you can read about Charts in users manual https://www.fast-report.com/public_download/html/UserManFrNET-en/chartreports.htm

Our Demo.exe (included in FastReport .NET demo) contains some reports with Charts https://www.fast-report.com/en/download/public_files/5/

![изображение](https://user-images.githubusercontent.com/43993341/60647701-f6619380-9e46-11e9-98bc-0bd4c4a5824b.png)

**Comment by yuhangli1991** [comment]
Thanks

**Comment by siarheiskalaban** [comment]
@fediachov Does FastReport allows charts on dotnet core?
`FastReport.Utils.ClassException : Can't find object MSChartObject`

**Comment by fediachov** [comment]
> @fediachov Does FastReport allows charts on dotnet core?
> `FastReport.Utils.ClassException : Can't find object MSChartObject`

@siarheiskalaban Unfortunately charts not supported yet

**Comment by GabrielMartinMoran** [comment]
Hi, are you expecting to implement this feature in the short term? Thanks.
