### ISSUE TITLE
How to pass business object to nested parameter.

### ISSUE THREAD

**Issue by NuwanCT** [FastReports/FastReport#96]
Hi,

I want to pass a instance of class to parameter and access them in report using nested parameters.
Ex:
**public class Employee
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}**

**var employee = new Employee { FirstName = "Name1", LastName = "Last1" };
report.SetParameterValue("Employee", employee);**

In my report, I tried to access them like this,
**[Employee.FirstName] [Employee.LastName]**
and that didn't work.

how can i do this. can i pass objects to parameters.

**Comment by fediachov** [comment]
Hi,

Unfortunately this type of parameters is not supported yet.

**Comment by andrelec1** [comment]
So, how this work ?

**Comment by fediachov** [comment]
You can set any plain parameter name and value pair.

```
report1.Load("report.frx");
report1.SetParameterValue("MyParam", 10);
report1.Prepare();
```

**Comment by andrelec1** [comment]
so ...

```
report1.Load("report.frx");
report1.SetParameterValue("somevar.a", somevar.a);
report1.SetParameterValue("somevar.a", somevar.a);
report1.SetParameterValue("somevar.a", somevar.a);


report1.Prepare();

```

**Comment by 8VAid8** [comment]
Hi, @andrelec1
If you had not succeed with parameters, please, check out [this article](https://fastreports.github.io/FastReport.Documentation/ReportParameters.html).
And [this one](https://www.fast-report.com/documentation/UserManFrNET-en/index.html?parameterpassvalueto.htm).
