### ISSUE TITLE
How to add internal data source?

### ISSUE THREAD

**Issue by yuhangli1991** [FastReports/FastReport#97]
I try to  add tableDataSource in report template,but I can't preview datasource in your fastreport.
It hinted to use  report.RegisterData ,but your template can show datasource  in your fastreport
directly.

**Comment by jeftegoesdev** [comment]
I didn't understand your doubt...

Look, for example, when I want to make a new report, I enter the datasource so I can "draw", but when I go to the code I dynamically inform the path whatever the datasoruce

webReport.Report.Dictionary.Connections[0].ConnectionString = "Json=http://" + url + "/Api/MyApi/" + id;

This way works for most connections.
