### ISSUE TITLE
Error BC35000: Requested operation is not available because the runtime library function 'Microsoft.VisualBasic.CompilerServices.Operators.CompareString' is not defined

### ISSUE THREAD

**Issue by Eisenstein** [FastReports/FastReport#98]
I've created netcoreapp2.1 project from scratch and referenced FastReport.OpenSource.
In my report I can reference DataSource fields just fine: `[Model.SomeField]`, however when I try to put in any expression like `[[Model.SomeField].Substring(1, 1)]` I get the following error:
```
An unhandled exception of type 'FastReport.Utils.CompilerException' occurred in FastReport.dll
(): Error BC35000: Requested operation is not available because the runtime library function 'Microsoft.VisualBasic.CompilerServices.Operators.CompareString' is not defined.
(Cell57): Error BC35000: Requested operation is not available because the runtime library function 'Microsoft.VisualBasic.CompilerServices.Conversions.ToString' is not defined.
```
It looks like I missed some another reference. Could you guide me please?

**Comment by 8VAid8** [comment]
Hello! It's .Net Core related issue. Fix will be available soon after this merge - https://github.com/FastReports/FastReport/pull/99
